//! Provenance for the persistent `stls/` output folder.
//!
//! The folder is never cleared. A selective export writes one STL beside
//! nine it did not touch, and nothing on disk tells them apart — a plug
//! regenerated today sits next to cup halves from a cast three months and
//! several design edits ago, same folder, same extension.
//!
//! [`record_run`] stamps every export with a run number and writes
//! `stls/manifest.toml`, so both a later run and a person reading the
//! folder can separate what this export produced from what was already
//! there.
//!
//! **Run numbers, not timestamps.** The question the folder cannot answer
//! is "same export or not?", and a counter answers exactly that. A cast's
//! writes span minutes, so timestamps do not group cleanly into runs; and
//! the wall-clock date is already on the file, from the filesystem. Run
//! numbers also survive the one case where mtime does not — a folder
//! copied or restored from backup carries its manifest and loses its
//! mtimes.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Filename of the manifest, written inside the `stls/` directory.
pub const MANIFEST_FILENAME: &str = "manifest.toml";

/// Run number for an STL already in the folder when the manifest was first
/// written, or dropped in by hand.
///
/// Its vintage is genuinely **unknown**, which is not the same as old: it
/// may be the current design's or three designs stale, and the manifest
/// cannot tell. Reported as unknown rather than guessed.
pub const UNKNOWN_RUN: u32 = 0;

/// Header comment written above the TOML, so the folder explains itself to
/// whoever opens it without the app.
const MANIFEST_HEADER: &str = "\
# Which export wrote which STL in this folder.
#
# The folder is never cleared, so it can hold files from several exports at
# once. `run` is the export that wrote a file; `latest_run` is the most
# recent one. A file whose `run` is below `latest_run` was NOT regenerated
# by the latest export and may not match the current design.
#
# run = 0 means the file was already here when this manifest was first
# written — its vintage is unknown.
#
# Written by cf-cast-cli. Safe to delete; it will be rebuilt, and every
# file then present is recorded as run = 0.
";

/// Where a cast's STLs live under its output directory.
///
/// ⚠ The ONE definition. A message that names a different folder than the one
/// [`folder_provenance`] read is a warning pointing at a directory the files
/// are not in — which is exactly what the warning exists to prevent.
///
/// Named `_in` because `stls_dir` is the parameter name in five functions
/// below, and a binding of that name would shadow this in every one of them.
#[must_use]
pub fn stls_dir_in(out_dir: &Path) -> PathBuf {
    out_dir.join(cf_cast::STLS_SUBDIR)
}

/// One STL in the folder, and the export that wrote it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ManifestEntry {
    /// Filename only (the manifest sits in the same directory).
    pub file: String,
    /// The export that wrote it, or [`UNKNOWN_RUN`].
    pub run: u32,
}

/// On-disk shape of `stls/manifest.toml`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
struct StlManifest {
    /// The most recent export's run number.
    latest_run: u32,
    /// One entry per STL in the folder, sorted by filename.
    #[serde(default, rename = "part")]
    parts: Vec<ManifestEntry>,
}

/// What an export produced, against what the folder already held.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RunProvenance {
    /// This export's run number.
    pub run: u32,
    /// STLs in the folder that this export did **not** write, with the run
    /// that did (or [`UNKNOWN_RUN`]). Sorted by filename.
    pub stale: Vec<ManifestEntry>,
}

impl RunProvenance {
    /// A one-line warning naming the not-regenerated files, or `None` when
    /// this export wrote everything in the folder.
    ///
    /// ⚠ `stls_dir` is the folder this roster was read from — the same
    /// argument `record_run` was given. It is named in the message because
    /// "this folder" identifies nothing on a terminal, and a warning that
    /// lists files without saying where they are sends the reader looking.
    ///
    /// The caller decides where it goes; nothing in this module prints.
    #[must_use]
    pub fn warning_line(&self, stls_dir: &Path) -> Option<String> {
        if self.stale.is_empty() {
            return None;
        }
        let names: Vec<&str> = self.stale.iter().map(|e| e.file.as_str()).collect();
        Some(format!(
            "{n} STL(s) in {dir} were NOT regenerated by this run \
             (run {run}) and may not match the current design: {list}",
            n = self.stale.len(),
            dir = stls_dir.display(),
            run = self.run,
            list = names.join(", "),
        ))
    }
}

/// Stamp `written` with the next run number and rewrite `stls_dir`'s
/// manifest, returning what the folder holds that this run did not write.
///
/// Reconciles three sets, because all three occur in practice:
///
/// - **Written this run** — stamped with the new run number.
/// - **In the folder, unlisted** — recorded as [`UNKNOWN_RUN`]. This is
///   every file in a folder that predates the manifest.
/// - **Listed, no longer in the folder** — dropped. Without this the
///   manifest accumulates entries for files a user deleted, and every
///   later run reports them as stale forever.
///
/// Only `.stl` files are tracked; `procedure.md` is regenerated by every
/// run and lives a directory up, so it is never stale.
///
/// # Errors
/// If `stls_dir` cannot be listed, or the manifest cannot be written. An
/// unparseable manifest is **not** an error — it is replaced (its content
/// was unrecoverable either way), and every file present becomes
/// [`UNKNOWN_RUN`].
pub fn record_run(stls_dir: &Path, written: &[PathBuf]) -> Result<RunProvenance> {
    let previous = load(stls_dir);
    let run = previous.latest_run.saturating_add(1);

    // Seeded with what the manifest knew, so a file this run did not touch
    // keeps the run that wrote it.
    let mut runs = seed(previous);
    for path in written {
        if let Some(name) = stl_file_name(path) {
            runs.insert(name, run);
        }
    }

    let parts = reconcile(stls_dir, runs)?;
    let stale = not_from_run(&parts, run);

    save(
        stls_dir,
        &StlManifest {
            latest_run: run,
            parts,
        },
    )?;

    Ok(RunProvenance { run, stale })
}

/// What the output folder holds **now**, without touching it.
///
/// The read-only sibling of `record_run` (private — a caller outside this
/// crate reads the folder, it never stamps one): same reconcile, no write, no
/// run number burned. `stale` is everything not from the manifest's `latest_run`,
/// so [`RunProvenance::warning_line`] reads the same as it does after a cast.
///
/// `None` means **unknown**, which is not the same as clean: no readable
/// manifest, or one recording nothing usable. Callers must not report a
/// folder as current on the strength of it.
#[must_use]
pub fn folder_provenance(out_dir: &Path) -> Option<RunProvenance> {
    let stls_dir = stls_dir_in(out_dir);
    let manifest = load_existing(&stls_dir)?;
    let run = manifest.latest_run;
    // ⚠ [`UNKNOWN_RUN`] is 0, so a manifest claiming 0 as its latest run would
    // make every unknown-vintage part compare EQUAL to it — a folder of
    // entirely unknown parts reported as current. 0 means unknown here too.
    if run == UNKNOWN_RUN {
        return None;
    }
    // A read must not repair the folder, so a reconcile failure is unknown
    // rather than an error to report.
    let parts = reconcile(&stls_dir, seed(manifest)).ok()?;
    Some(RunProvenance {
        run,
        stale: not_from_run(&parts, run),
    })
}

/// The manifest's entries as a filename → run map.
fn seed(manifest: StlManifest) -> BTreeMap<String, u32> {
    manifest
        .parts
        .into_iter()
        .map(|e| (e.file, e.run))
        .collect()
}

/// Reconcile `runs` against what `stls_dir` actually holds: entries whose file
/// is gone leave, files the seed does not name arrive as [`UNKNOWN_RUN`].
///
/// ⚠ Shared by [`record_run`] and [`folder_provenance`] on purpose. Two paths
/// deciding separately what the folder holds is how they come to disagree
/// about which parts are stale.
///
/// `BTreeMap` iterates sorted, so the manifest stays diff-stable across runs.
///
/// # Errors
/// If `stls_dir` cannot be listed.
fn reconcile(stls_dir: &Path, mut runs: BTreeMap<String, u32>) -> Result<Vec<ManifestEntry>> {
    let on_disk = list_stls(stls_dir)?;
    runs.retain(|file, _| on_disk.contains(file));
    for file in on_disk {
        runs.entry(file).or_insert(UNKNOWN_RUN);
    }
    Ok(runs
        .into_iter()
        .map(|(file, run)| ManifestEntry { file, run })
        .collect())
}

/// The entries not written by `run`.
fn not_from_run(parts: &[ManifestEntry], run: u32) -> Vec<ManifestEntry> {
    parts.iter().filter(|e| e.run != run).cloned().collect()
}

/// Read the manifest, or a default when it is absent or unparseable.
///
/// Unparseable is deliberately not an error: the manifest is advisory
/// bookkeeping, and its content is unrecoverable in that case anyway.
/// [`record_run`] then rebuilds it from the folder.
fn load(stls_dir: &Path) -> StlManifest {
    load_existing(stls_dir).unwrap_or_default()
}

/// The manifest, or `None` when there is not a readable one.
///
/// Distinct from [`load`]'s default: a folder with no manifest and a folder
/// with an empty one are the same to [`record_run`], which rebuilds either
/// way, but not to [`folder_provenance`], which must say **unknown** rather
/// than report a clean folder it has never seen.
fn load_existing(stls_dir: &Path) -> Option<StlManifest> {
    let path = stls_dir.join(MANIFEST_FILENAME);
    let text = std::fs::read_to_string(&path).ok()?;
    toml::from_str(&text).ok()
}

/// Serialize the manifest under [`MANIFEST_HEADER`].
///
/// Written to a temp file and renamed, the way `save_design_toml` writes the
/// design: [`load`] discards an unparseable manifest whole, so a half-written
/// one costs every file its recorded run, not just the tail.
fn save(stls_dir: &Path, manifest: &StlManifest) -> Result<()> {
    let path = stls_dir.join(MANIFEST_FILENAME);
    let body = toml::to_string_pretty(manifest)
        .with_context(|| format!("serialize {}", path.display()))?;

    let tmp = path.with_extension("toml.tmp");
    std::fs::write(&tmp, format!("{MANIFEST_HEADER}\n{body}"))
        .with_context(|| format!("write {}", tmp.display()))?;
    if let Err(e) = std::fs::rename(&tmp, &path) {
        // Best-effort, so a failed rename does not leave the .tmp behind.
        let _ = std::fs::remove_file(&tmp);
        return Err(e)
            .with_context(|| format!("rename {} \u{2192} {}", tmp.display(), path.display()));
    }
    Ok(())
}

/// The `.stl` filenames directly in `stls_dir`.
///
/// # Errors
/// If the directory cannot be listed.
fn list_stls(stls_dir: &Path) -> Result<std::collections::BTreeSet<String>> {
    let entries =
        std::fs::read_dir(stls_dir).with_context(|| format!("list {}", stls_dir.display()))?;
    let mut names = std::collections::BTreeSet::new();
    for entry in entries {
        let path = entry
            .with_context(|| format!("read an entry in {}", stls_dir.display()))?
            .path();
        // A directory named `foo.stl` is not a part. `cf-viewer`'s scan of
        // this same folder skips non-files explicitly; so does this.
        if !path.is_file() {
            continue;
        }
        if let Some(name) = stl_file_name(&path) {
            names.insert(name);
        }
    }
    Ok(names)
}

/// `path`'s filename, when it is a `.stl`.
fn stl_file_name(path: &Path) -> Option<String> {
    if path.extension().and_then(|e| e.to_str()) != Some("stl") {
        return None;
    }
    path.file_name()
        .and_then(|n| n.to_str())
        .map(str::to_string)
}

/// Record this run in the output folder's manifest and warn about STLs it
/// did not regenerate.
///
/// **Never fails the run.** The STLs are the product and are already on
/// disk by the time this is called; losing a minutes-long cast to a
/// bookkeeping write would be the worse outcome. A failure is reported and
/// returns `None`, which callers carry as "not known" rather than
/// flattening to "nothing stale".
pub(crate) fn stamp_output_folder(out_dir: &Path, written: &[PathBuf]) -> Option<RunProvenance> {
    let stls_dir = stls_dir_in(out_dir);
    match record_run(&stls_dir, written) {
        Ok(provenance) => {
            if let Some(warning) = provenance.warning_line(&stls_dir) {
                eprintln!("[cf-cast-cli] \u{26a0} {warning}");
            }
            Some(provenance)
        }
        Err(e) => {
            eprintln!(
                "[cf-cast-cli] \u{26a0} could not record {dir}/{MANIFEST_FILENAME}, so this \
                 run's output cannot be told from what was already there: {e:#}",
                dir = stls_dir.display(),
            );
            None
        }
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    /// A fresh `stls/` directory holding `existing` files.
    fn stls_dir(label: &str, existing: &[&str]) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "cf-cast-cli-manifest-test-{}-{label}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        for f in existing {
            std::fs::write(dir.join(f), b"solid\n").unwrap();
        }
        dir
    }

    /// The run recorded for `file`, by reading the manifest back off disk
    /// rather than the returned value — the file is what a later run and a
    /// person both read.
    fn run_of(dir: &Path, file: &str) -> Option<u32> {
        let text = std::fs::read_to_string(dir.join(MANIFEST_FILENAME)).unwrap();
        let manifest: StlManifest = toml::from_str(&text).unwrap();
        manifest
            .parts
            .into_iter()
            .find(|e| e.file == file)
            .map(|e| e.run)
    }

    /// Sorted file names in `dir`, so "a read left something behind" is
    /// checkable by more than the one name I expected it to use.
    fn listing(dir: &Path) -> Vec<String> {
        let mut names: Vec<String> = std::fs::read_dir(dir)
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().to_string())
            .collect();
        names.sort();
        names
    }

    fn stale_names(p: &RunProvenance) -> Vec<String> {
        p.stale.iter().map(|e| e.file.clone()).collect()
    }

    /// The hazard itself: one plug regenerated into a folder of nine files
    /// from an earlier cast. The run that wrote each is now on disk, and
    /// the nine are named as not-this-run.
    #[test]
    fn a_selective_run_names_every_file_it_did_not_write() {
        let dir = stls_dir(
            "selective",
            &[
                "mold_layer_0_piece_0.stl",
                "mold_layer_0_piece_1.stl",
                "plug_layer_0.stl",
                "plug_layer_1.stl",
                "platform.stl",
            ],
        );

        let p = record_run(&dir, &[dir.join("plug_layer_0.stl")]).unwrap();

        assert_eq!(p.run, 1, "first run in a folder with no manifest is run 1");
        assert_eq!(run_of(&dir, "plug_layer_0.stl"), Some(1), "regenerated");
        assert_eq!(
            stale_names(&p),
            vec![
                "mold_layer_0_piece_0.stl",
                "mold_layer_0_piece_1.stl",
                "platform.stl",
                "plug_layer_1.stl",
            ],
            "the four the run did not write, sorted",
        );
        // Pre-existing files are UNKNOWN, not "old" — the manifest has never
        // seen them and must not invent a vintage.
        assert_eq!(run_of(&dir, "plug_layer_1.stl"), Some(UNKNOWN_RUN));

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Across two runs a file keeps the run that wrote it — the property
    /// mtime cannot give, since a cast's own writes span minutes.
    #[test]
    fn a_file_keeps_the_run_that_wrote_it_across_later_runs() {
        let dir = stls_dir("keeps", &["plug_layer_0.stl", "platform.stl"]);

        let first = record_run(
            &dir,
            &[dir.join("plug_layer_0.stl"), dir.join("platform.stl")],
        );
        assert!(first.unwrap().stale.is_empty(), "run 1 wrote both");

        let second = record_run(&dir, &[dir.join("plug_layer_0.stl")]).unwrap();

        assert_eq!(second.run, 2, "the counter advances");
        assert_eq!(run_of(&dir, "plug_layer_0.stl"), Some(2), "rewritten");
        assert_eq!(run_of(&dir, "platform.stl"), Some(1), "kept run 1, not 0");
        assert_eq!(stale_names(&second), vec!["platform.stl"]);

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A deleted file leaves the manifest. Without the prune its entry
    /// survives forever and every later run reports a file that is gone.
    #[test]
    fn a_deleted_file_is_dropped_rather_than_reported_stale_forever() {
        let dir = stls_dir("pruned", &["plug_layer_0.stl", "funnel.stl"]);
        record_run(&dir, &[dir.join("plug_layer_0.stl")]).unwrap();
        assert_eq!(
            run_of(&dir, "funnel.stl"),
            Some(UNKNOWN_RUN),
            "listed first"
        );

        std::fs::remove_file(dir.join("funnel.stl")).unwrap();
        let p = record_run(&dir, &[dir.join("plug_layer_0.stl")]).unwrap();

        assert_eq!(run_of(&dir, "funnel.stl"), None, "entry dropped");
        assert!(p.stale.is_empty(), "nothing left it did not write");

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A full cast writes everything in the folder — no warning, because
    /// there is nothing to warn about. A warning that fires every run is
    /// one nobody reads.
    #[test]
    fn a_run_that_writes_every_file_reports_nothing_stale() {
        let dir = stls_dir("full", &["a.stl", "b.stl"]);

        let p = record_run(&dir, &[dir.join("a.stl"), dir.join("b.stl")]).unwrap();

        // ⚠ Both claims below are ABSENCES, and "nothing tracked" satisfies
        // them just as well as "nothing stale". Pin the presence first.
        assert_eq!(run_of(&dir, "a.stl"), Some(1));
        assert_eq!(run_of(&dir, "b.stl"), Some(1));

        assert!(p.stale.is_empty());
        assert_eq!(
            p.warning_line(&dir),
            None,
            "silent when the folder is current"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The warning names the files, not just a count — the count alone
    /// sends the reader back to the folder it could not read.
    #[test]
    fn the_warning_line_names_the_files() {
        let dir = stls_dir("warn", &["plug_layer_0.stl", "plug_layer_1.stl"]);

        let p = record_run(&dir, &[dir.join("plug_layer_0.stl")]).unwrap();
        let line = p.warning_line(&dir).expect("one file was not regenerated");

        assert!(
            line.contains(&dir.display().to_string()),
            "it must say WHERE — \"this folder\" names nothing on a terminal: {line}"
        );

        assert!(line.contains("plug_layer_1.stl"), "names it: {line}");
        assert!(
            !line.contains("plug_layer_0.stl"),
            "not the fresh one: {line}"
        );
        assert!(line.contains("1 STL(s)"), "counts it: {line}");

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Non-STL neighbours are not parts. `procedure.md` in particular is
    /// rewritten by every run, so reporting it stale would be a lie.
    #[test]
    fn non_stl_files_are_not_tracked() {
        let dir = stls_dir("nonstl", &["plug_layer_0.stl", "procedure.md", "notes.txt"]);

        let p = record_run(&dir, &[dir.join("plug_layer_0.stl")]).unwrap();

        // ⚠ As above: the STL must be tracked, or "the .md is not tracked"
        // is a claim about a manifest that tracks nothing at all.
        assert_eq!(run_of(&dir, "plug_layer_0.stl"), Some(1), "the STL is");
        assert!(p.stale.is_empty(), "got: {:?}", stale_names(&p));
        assert_eq!(run_of(&dir, "procedure.md"), None);
        assert_eq!(run_of(&dir, "notes.txt"), None);

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A corrupt manifest must not fail a cast that already succeeded —
    /// the STLs are the product, the bookkeeping is not.
    #[test]
    fn an_unparseable_manifest_is_rebuilt_rather_than_failing_the_run() {
        let dir = stls_dir("corrupt", &["plug_layer_0.stl", "platform.stl"]);
        std::fs::write(dir.join(MANIFEST_FILENAME), b"} not toml {").unwrap();

        let p = record_run(&dir, &[dir.join("plug_layer_0.stl")]).unwrap();

        assert_eq!(p.run, 1, "numbering restarts; the old count was unreadable");
        assert_eq!(run_of(&dir, "plug_layer_0.stl"), Some(1));
        assert_eq!(run_of(&dir, "platform.stl"), Some(UNKNOWN_RUN));

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The header is what makes the folder self-explaining to someone who
    /// opens it without the app — and the file must still parse with it.
    #[test]
    fn the_written_manifest_carries_its_header_and_still_parses() {
        let dir = stls_dir("header", &["plug_layer_0.stl"]);
        record_run(&dir, &[dir.join("plug_layer_0.stl")]).unwrap();

        let text = std::fs::read_to_string(dir.join(MANIFEST_FILENAME)).unwrap();
        assert!(text.starts_with("# Which export wrote which STL"), "{text}");
        let parsed: StlManifest = toml::from_str(&text).unwrap();
        assert_eq!(parsed.latest_run, 1);
        assert_eq!(parsed.parts.len(), 1);
        // ⚠ Not `!manifest.toml.tmp.exists()` — that passes just as well if
        // the temp file is named something else entirely. Name what the
        // folder MAY hold, so any leftover fails whatever it is called.
        let mut left: Vec<String> = std::fs::read_dir(&dir)
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().to_string())
            .collect();
        left.sort();
        assert_eq!(left, vec!["manifest.toml", "plug_layer_0.stl"]);

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The whole point of the non-fatal policy: a cast that already wrote
    /// its STLs must survive a folder it cannot record.
    ///
    /// ⚠ `record_run` on the same path is an `Err` (the gate below), so
    /// this is the wrapper's own decision being tested, not the absence of
    /// a failure to swallow.
    #[test]
    fn a_folder_that_cannot_be_recorded_does_not_fail_the_run() {
        let missing = Path::new("/no/such/cast/out");
        assert!(
            record_run(&missing.join(cf_cast::STLS_SUBDIR), &[]).is_err(),
            "the fixture must actually fail, or this gate proves nothing"
        );

        assert_eq!(
            stamp_output_folder(missing, &[]),
            None,
            "reported as not-known; the run carries on"
        );
    }

    /// The other side of it — a folder it CAN record comes back populated,
    /// so `None` means "could not record" and never "nothing to say".
    #[test]
    fn a_folder_it_can_record_comes_back_populated() {
        let out = std::env::temp_dir().join(format!(
            "cf-cast-cli-manifest-test-{}-stamp",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&out);
        let stls = out.join(cf_cast::STLS_SUBDIR);
        std::fs::create_dir_all(&stls).unwrap();
        std::fs::write(stls.join("left_behind.stl"), b"solid\n").unwrap();

        let provenance = stamp_output_folder(&out, &[]).expect("a writable folder records");

        assert_eq!(provenance.run, 1);
        assert_eq!(
            provenance.stale,
            vec![ManifestEntry {
                file: "left_behind.stl".to_string(),
                run: UNKNOWN_RUN,
            }],
        );

        let _ = std::fs::remove_dir_all(&out);
    }

    /// A directory named `something.stl` is not a part.
    ///
    /// ⚠ `cf-viewer`'s equivalent scan skips non-files explicitly; this one
    /// filtered on the extension alone.
    #[test]
    fn a_directory_that_looks_like_an_stl_is_not_a_part() {
        let dir = stls_dir("phantom", &["plug_layer_0.stl"]);
        std::fs::create_dir_all(dir.join("phantom.stl")).unwrap();

        let p = record_run(&dir, &[dir.join("plug_layer_0.stl")]).unwrap();

        assert_eq!(run_of(&dir, "plug_layer_0.stl"), Some(1), "the real one is");
        assert_eq!(run_of(&dir, "phantom.stl"), None, "the directory is not");
        assert!(p.stale.is_empty(), "got: {:?}", stale_names(&p));

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// An `out/` with an `stls/` inside, the shape `folder_provenance` takes.
    fn out_dir(label: &str, existing: &[&str]) -> PathBuf {
        let out = std::env::temp_dir().join(format!(
            "cf-cast-cli-manifest-test-{}-{label}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&out);
        let stls = out.join(cf_cast::STLS_SUBDIR);
        std::fs::create_dir_all(&stls).unwrap();
        for f in existing {
            std::fs::write(stls.join(f), b"solid\n").unwrap();
        }
        out
    }

    /// Reading the folder must not repair, renumber, or rewrite it.
    ///
    /// ⚠ The bytes, not just `latest_run` — a rewrite that happened to
    /// reproduce the same run number would still have burned one, and would
    /// still be a write where a read was promised.
    #[test]
    fn reading_the_folder_does_not_touch_it() {
        let out = out_dir("read-only", &["plug_layer_0.stl", "platform.stl"]);
        let stls = out.join(cf_cast::STLS_SUBDIR);
        record_run(&stls, &[stls.join("plug_layer_0.stl")]).unwrap();

        let before = std::fs::read(stls.join(MANIFEST_FILENAME)).unwrap();
        let listing_before = listing(&stls);

        let first = folder_provenance(&out).expect("the folder has a manifest");
        let second = folder_provenance(&out).expect("and reading it again is fine");

        assert_eq!(
            std::fs::read(stls.join(MANIFEST_FILENAME)).unwrap(),
            before,
            "the manifest was rewritten by a read"
        );
        assert_eq!(listing(&stls), listing_before, "the folder gained a file");
        assert_eq!(first, second, "two reads of one folder must agree");
        assert_eq!(first.run, 1, "and must not advance the run");

        let _ = std::fs::remove_dir_all(&out);
    }

    /// The read reports the same thing the cast reported, read back off disk
    /// instead of returned from the run.
    #[test]
    fn folder_provenance_names_what_the_last_run_did_not_write() {
        let out = out_dir("read-stale", &["plug_layer_0.stl", "platform.stl"]);
        let stls = out.join(cf_cast::STLS_SUBDIR);
        let from_run = record_run(&stls, &[stls.join("plug_layer_0.stl")]).unwrap();

        let from_disk = folder_provenance(&out).expect("a manifest is there");

        assert_eq!(
            stale_names(&from_disk),
            vec!["platform.stl"],
            "the one the run did not write"
        );
        assert_eq!(from_disk, from_run, "the disk and the run agree");

        let _ = std::fs::remove_dir_all(&out);
    }

    /// ⚠ A folder last cast by a build that did not stamp is of UNKNOWN
    /// provenance. Reporting it clean would be the original bug, dressed up
    /// as an answer.
    #[test]
    fn a_folder_with_no_manifest_is_unknown_not_clean() {
        let out = out_dir("no-manifest", &["plug_layer_0.stl", "plug_layer_1.stl"]);

        assert_eq!(folder_provenance(&out), None);

        let _ = std::fs::remove_dir_all(&out);
    }

    /// As above for a manifest that cannot be parsed — and unlike
    /// `record_run`, which rebuilds one, a read has nothing to say.
    #[test]
    fn an_unparseable_manifest_reads_as_unknown() {
        let out = out_dir("read-corrupt", &["plug_layer_0.stl"]);
        let stls = out.join(cf_cast::STLS_SUBDIR);
        std::fs::write(stls.join(MANIFEST_FILENAME), b"} not toml {").unwrap();

        assert_eq!(folder_provenance(&out), None);

        let _ = std::fs::remove_dir_all(&out);
    }

    /// A part deleted outside the app is gone, not stale — the read
    /// reconciles against the folder, it does not trust the manifest alone.
    #[test]
    fn a_part_deleted_outside_the_app_is_not_reported() {
        let out = out_dir("read-deleted", &["plug_layer_0.stl", "funnel.stl"]);
        let stls = out.join(cf_cast::STLS_SUBDIR);
        record_run(&stls, &[stls.join("plug_layer_0.stl")]).unwrap();
        assert_eq!(
            stale_names(&folder_provenance(&out).unwrap()),
            vec!["funnel.stl"],
            "stale while it is there"
        );

        std::fs::remove_file(stls.join("funnel.stl")).unwrap();

        assert!(
            folder_provenance(&out).unwrap().stale.is_empty(),
            "gone is not stale"
        );

        let _ = std::fs::remove_dir_all(&out);
    }

    /// ⚠⚠ `UNKNOWN_RUN` is 0, and 0 must never also mean "the latest run".
    /// A manifest claiming `latest_run = 0` would otherwise make every
    /// unknown-vintage part compare EQUAL to the latest run — reporting a
    /// folder of entirely unknown parts as current, which is silence exactly
    /// where this feature exists to speak.
    #[test]
    fn a_manifest_whose_latest_run_is_the_unknown_sentinel_is_unknown() {
        let out = out_dir("run-zero", &["a.stl", "b.stl"]);
        let stls = out.join(cf_cast::STLS_SUBDIR);
        std::fs::write(
            stls.join(MANIFEST_FILENAME),
            format!(
                "latest_run = {UNKNOWN_RUN}\n\n[[part]]\nfile = \"a.stl\"\nrun = \
                 {UNKNOWN_RUN}\n\n[[part]]\nfile = \"b.stl\"\nrun = {UNKNOWN_RUN}\n"
            ),
        )
        .unwrap();

        assert_eq!(
            folder_provenance(&out),
            None,
            "a folder of entirely unknown parts is unknown, not current"
        );

        let _ = std::fs::remove_dir_all(&out);
    }

    /// A missing directory is a real error — the caller passed a path that
    /// is not the cast's output, and silently succeeding would record
    /// nothing while reporting success.
    #[test]
    fn a_missing_directory_is_an_error() {
        assert!(record_run(Path::new("/no/such/stls"), &[]).is_err());
    }
}
