//! Slice 9.6c — post-process `cf-cast`'s `procedure.md` to surface
//! design-level metadata cf-cast itself doesn't see.
//!
//! `cf-cast::write_procedure_v2` runs against [`cf_cast::CastSpec`],
//! which is the workshop-level geometry contract — it doesn't know
//! about `cf-device-design`'s `cavity.inset_m` (the press-fit
//! reservation): that value drove the plug-inward-offset geometry
//! upstream in [`crate::derive::derive_spec_and_ribbon`] but isn't
//! preserved on the spec data carrier.
//!
//! cf-cast-cli knows it (lifted from `.design.toml`) and is the right
//! place to weave it into the procedure markdown without expanding
//! cf-cast's public surface. So we post-process: read the procedure
//! file back, splice a new `## Press-Fit Reservation` section in
//! above the existing `## Materials Summary` anchor, write the
//! patched file back. No-op when `cavity_inset_m == 0.0`.

use std::path::Path;

use anyhow::{Context, Result, bail};

/// The h2-header anchor `cf-cast`'s `generate_procedure_markdown_v2`
/// emits via `write_materials_table` — see
/// `design/cf-cast/src/procedure.rs:100` and `:352`. We inject the
/// `## Press-Fit Reservation` section above this line so it sits as
/// the first content section after the header prose.
const MATERIALS_ANCHOR: &str = "## Materials Summary";

/// Inject a `## Press-Fit Reservation` section into `procedure.md`
/// when `cavity_inset_m > 0`.
///
/// No-op for `cavity_inset_m == 0.0` (the inline-layers path), so
/// procedure markdown produced by cast.toml configs predating
/// slice 9.6 is bit-exact-preserved.
///
/// # Errors
///
/// - propagates filesystem read/write errors with file-path context.
/// - bails with a clear message if the `## Materials Summary` anchor
///   isn't present (means cf-cast's procedure shape changed — caller
///   should regenerate test fixtures or update the anchor).
pub fn inject_press_fit_section(path: &Path, cavity_inset_m: f64) -> Result<()> {
    if cavity_inset_m == 0.0 {
        return Ok(());
    }
    let original = std::fs::read_to_string(path).with_context(|| {
        format!(
            "read procedure.md at {} for press-fit injection",
            path.display()
        )
    })?;
    let patched = inject_press_fit_into_markdown(&original, cavity_inset_m).with_context(|| {
        format!(
            "inject press-fit section into procedure.md at {}",
            path.display()
        )
    })?;
    std::fs::write(path, patched)
        .with_context(|| format!("write patched procedure.md at {}", path.display()))?;
    Ok(())
}

/// Pure-string variant of [`inject_press_fit_section`] — used by the
/// unit test and the live path equally so a regression in the anchor
/// detection or section template surfaces in the cheap test layer
/// before the integration test.
pub(crate) fn inject_press_fit_into_markdown(
    original: &str,
    cavity_inset_m: f64,
) -> Result<String> {
    if !original.contains(MATERIALS_ANCHOR) {
        bail!(
            "procedure.md missing the `{}` anchor (cf-cast shape changed?)",
            MATERIALS_ANCHOR
        );
    }
    let inset_mm = cavity_inset_m * 1e3;
    let section = format!(
        "## Press-Fit Reservation\n\
         \n\
         The plug + every silicone layer is offset inward by **{inset_mm:.2} mm** \
         from the scan surface. The cured part's inner cavity is correspondingly \
         {inset_mm:.2} mm smaller than the scan, leaving a press-fit interference \
         for the real device to snap into. This is baked into the mold geometry \
         by `cf-cast-cli` from `cf-device-design`'s `cavity.inset_m`.\n\
         \n",
    );
    // Splice the new section in BEFORE `## Materials Summary` — string
    // `replace_n(1)` works because the anchor appears exactly once in
    // the v2 procedure markdown (verified by the `single anchor` unit
    // test below).
    let patched = original.replacen(MATERIALS_ANCHOR, &format!("{section}{MATERIALS_ANCHOR}"), 1);
    Ok(patched)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::*;

    const FIXTURE_V2: &str = "\
# Cast Procedure\n\
\n\
Generated by `cf-cast` for a 1-layer cast (innermost-first).\n\
\n\
## Cast Geometry\n\
\n\
Some geometry prose.\n\
\n\
## Materials Summary\n\
\n\
| Layer | Material | Pour Mass |\n\
|------:|----------|----------:|\n\
| 0 | Ecoflex 00-30 | 142.0 g |\n\
\n\
## Generic Smooth-On Guidance\n\
\n\
Some guidance.\n";

    #[test]
    fn inject_press_fit_inserts_section_above_materials() {
        let patched = inject_press_fit_into_markdown(FIXTURE_V2, 0.002).unwrap();
        let press_fit_idx = patched
            .find("## Press-Fit Reservation")
            .expect("Press-Fit section present");
        let materials_idx = patched
            .find("## Materials Summary")
            .expect("Materials section preserved");
        assert!(
            press_fit_idx < materials_idx,
            "Press-Fit must precede Materials; got press_fit={press_fit_idx}, materials={materials_idx}",
        );
        assert!(
            patched.contains("**2.00 mm**"),
            "inset value (2 mm) must appear in mm with 2-dp formatting; got:\n{patched}",
        );
        // Original sections all preserved verbatim.
        assert!(patched.contains("## Cast Geometry"));
        assert!(patched.contains("## Generic Smooth-On Guidance"));
        assert!(patched.contains("Ecoflex 00-30"));
    }

    #[test]
    fn inject_press_fit_is_noop_at_zero_inset() {
        // The file-path path is the no-op gate; the string variant
        // pins behavior for non-zero inset values. inset = 0 doesn't
        // reach the string injection in normal flow, but if a caller
        // forces it, we still emit a section (with 0.00 mm — exact
        // semantics for an explicit zero is debatable but consistent
        // with the floor: callers who want no-op should use the
        // file-path version or check inset before calling).
        let patched = inject_press_fit_into_markdown(FIXTURE_V2, 0.0).unwrap();
        assert!(patched.contains("**0.00 mm**"));
    }

    #[test]
    fn inject_press_fit_missing_anchor_errors() {
        let no_materials = "# Cast Procedure\n\n## Just A Header\n";
        let err = inject_press_fit_into_markdown(no_materials, 0.002).unwrap_err();
        assert!(
            err.to_string().contains("Materials Summary"),
            "unexpected error message: {err}",
        );
    }

    #[test]
    fn materials_anchor_appears_once_in_fixture() {
        // Anchor uniqueness is what makes `replacen(1)` safe — if
        // cf-cast ever emits the header twice, this trips here.
        assert_eq!(FIXTURE_V2.matches(MATERIALS_ANCHOR).count(), 1);
    }
}
