# Funding links
#
# These appear as "Sponsor" button on the repository
# Uncomment and fill in when ready to accept sponsorship

# github: [jonhillesheim]
# patreon: cortenforge
# open_collective: cortenforge
# ko_fi: cortenforge
# custom: ["https://cortenforge.dev/sponsor"]
