//! F3 procedure-spec markdown generator.
//!
//! [`generate_procedure_markdown`] renders a workshop-ready Markdown
//! procedure for a [`CastSpec`]: per-layer pour masses (from F2),
//! mix ratio + pot life + cure time (from [`crate::cure::lookup`]),
//! generic Smooth-On guidance, and a mass-budget summary. The
//! generated markdown is the starting-point reference the workshop
//! user iterates against bench reality after iter-1.
//!
//! The function is pure (no IO) so tests can assert on its output
//! bit-exactly. [`CastSpec::write_procedure`] is the convenience
//! wrapper that writes the rendered string to disk.

// `writeln!`/`write!` on a `String` go through the `core::fmt::Write`
// trait, which returns `Result<(), fmt::Error>` for generality. The
// `String` impl never fails, so the workspace's
// `let_underscore_must_use` deny is structurally redundant on every
// `let _ = writeln!(md, …);` site in this generator. The
// alternatives (an `.expect("…")` chain, a `push_str(&format!(…))`
// rewrite at every site) trade one form of noise for another;
// scoping the allow to this single template module keeps the
// workspace-wide deny intact for code where Result-discarding
// genuinely could mask failures.
#![allow(clippy::let_underscore_must_use)]

use std::fmt::Write as _;

use crate::cure::lookup as lookup_cure;
use crate::flange::FlangeKind;
use crate::gasket_mold::GasketKind;
use crate::plug::PlugPinKind;
use crate::pour::{PourGateKind, PourGateLayout};
use crate::pour_volume::PourVolume;
use crate::prismatic_pin::PrismaticPinSpec;
use crate::ribbon::Ribbon;
use crate::spec::CastSpec;

/// Conversion factor — kilograms to grams. Pour masses surface in
/// the markdown table in grams because workshop scales read grams.
const KG_TO_G: f64 = 1000.0;

/// Placeholder text emitted in the materials table when a layer's
/// [`crate::MoldingMaterial::anchor_key`] is `None` or refers to a
/// material outside [`crate::cure::lookup`]'s anchor set
/// (interpolated, measured, or non-Smooth-On).
const TDS_LOOKUP_PLACEHOLDER: &str = "consult Smooth-On TDS";

/// Render the Markdown procedure for `spec` given the per-layer
/// `pour_volumes` (computed by [`CastSpec::compute_pour_volumes`]).
///
/// `pour_volumes` is taken by parameter (not recomputed) so callers
/// can render against a single pour-volume capture even when their
/// flow already has the values in hand (e.g., from a
/// [`crate::MoldExportReport`]).
///
/// The function is pure: no IO, no time-dependent fields. Tests can
/// pin the output bit-exactly.
///
/// # Panics
///
/// Length of `pour_volumes` must equal `spec.layers.len()`. The
/// caller is expected to pass a freshly-computed
/// `compute_pour_volumes` result; mismatched lengths are a programming
/// error and panic via the `length` assertion.
#[must_use]
pub fn generate_procedure_markdown(spec: &CastSpec, pour_volumes: &[PourVolume]) -> String {
    assert_eq!(
        pour_volumes.len(),
        spec.layers.len(),
        "pour_volumes must be parallel to spec.layers"
    );

    let mut md = String::new();
    write_header(&mut md, spec);
    write_materials_table(&mut md, spec, pour_volumes);
    write_generic_guidance(&mut md);
    write_per_layer_sections(&mut md, spec, pour_volumes);
    write_mass_budget_summary(&mut md, spec, pour_volumes);
    md
}

fn write_header(md: &mut String, spec: &CastSpec) {
    let _ = writeln!(md, "# Cast Procedure");
    md.push('\n');
    let _ = writeln!(
        md,
        "Generated by `cf-cast` for a {}-layer cast (innermost-first).",
        spec.layers.len()
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "Workshop procedure starting-point. Mix ratios, pot life, and \
         cure times are per Smooth-On Technical Data Sheets at 73 °F \
         (23 °C). Treat the steps below as a baseline — adjust against \
         bench reality after iter-1."
    );
    md.push('\n');
}

fn write_materials_table(md: &mut String, spec: &CastSpec, pour_volumes: &[PourVolume]) {
    let _ = writeln!(md, "## Materials Summary");
    md.push('\n');
    let _ = writeln!(
        md,
        "| Layer | Material | Pour Mass | Mix Ratio | Pot Life | Cure Time |"
    );
    let _ = writeln!(
        md,
        "|------:|----------|----------:|-----------|---------:|----------:|"
    );
    for (layer, pour) in spec.layers.iter().zip(pour_volumes) {
        let mass_g = pour.pour_mass_kg * KG_TO_G;
        let (mix, pot_life, cure_time) = cure_protocol_cells(layer.material.anchor_key);
        let _ = writeln!(
            md,
            "| {} | {} | {:.2} g | {} | {} | {} |",
            pour.layer_index, layer.material.display_name, mass_g, mix, pot_life, cure_time,
        );
    }
    md.push('\n');
}

fn write_generic_guidance(md: &mut String) {
    let _ = writeln!(md, "## Generic Smooth-On Guidance");
    md.push('\n');
    let _ = writeln!(
        md,
        "- Weigh Part A + Part B on a gram scale. 1A:1B is by weight or \
         volume per TDS — choose the more accurate path for the equipment \
         on hand (weight typically beats volume for low-viscosity \
         silicones)."
    );
    let _ = writeln!(
        md,
        "- Vacuum-degas the mixed silicone at ≥27 inHg for 2-3 minutes \
         before pouring. Bubbles trapped at cavity surfaces or layer \
         interfaces are the #1 first-cast failure mode."
    );
    let _ = writeln!(
        md,
        "- Apply mold release to printed surfaces before each pour. \
         Layer-to-layer adhesion between cured silicones is generally \
         strong without release, but printed-mold-to-silicone separation \
         needs it."
    );
    let _ = writeln!(
        md,
        "- Pour into the deepest point of the cavity and let the silicone \
         self-level outward; pouring across surfaces traps air."
    );
    let _ = writeln!(
        md,
        "- Cure at room temperature (≈23 °C). Cooler slows cure; warmer \
         accelerates. Heat-cure schedules can shorten demold time per \
         TDS but introduce thermal-shrink effects not modeled here."
    );
    md.push('\n');
}

fn write_per_layer_sections(md: &mut String, spec: &CastSpec, pour_volumes: &[PourVolume]) {
    let _ = writeln!(md, "## Per-Layer Procedure");
    md.push('\n');
    for (layer, pour) in spec.layers.iter().zip(pour_volumes) {
        let position = layer_position_label(pour.layer_index, spec.layers.len());
        let _ = writeln!(
            md,
            "### Layer {} — {} ({})",
            pour.layer_index, layer.material.display_name, position
        );
        md.push('\n');
        let mass_g = pour.pour_mass_kg * KG_TO_G;
        let half_g = mass_g / 2.0;
        // Looked up once per layer — both step 3 (mix) and step 6
        // (cure) branch on whether this material has an anchored
        // CureProtocol vs the TDS-fallback prose. Looking it up
        // directly here (rather than via `cure_protocol_cells`)
        // avoids substituting placeholder strings into duration /
        // ratio positions where they read as broken English
        // ("Cure for ≥consult Smooth-On TDS …").
        let protocol = layer.material.anchor_key.and_then(lookup_cure);
        let _ = writeln!(
            md,
            "1. Print STL `mold_layer_{}.stl`{}.",
            pour.layer_index,
            if pour.layer_index == 0 {
                " and the shared `plug.stl`"
            } else {
                ""
            }
        );
        let _ = writeln!(md, "2. Apply mold release to all printed surfaces.");
        if let Some(protocol) = protocol {
            let _ = writeln!(
                md,
                "3. Mix {half_g:.2} g Part A + {half_g:.2} g Part B {} ({} mix ratio). \
                 Total {mass_g:.2} g.",
                layer.material.display_name, protocol.mix_ratio_a_to_b,
            );
        } else {
            let _ = writeln!(
                md,
                "3. Mix Part A + Part B {} per the Smooth-On TDS \
                 (total pour mass: {mass_g:.2} g, split per the data-sheet mix ratio).",
                layer.material.display_name,
            );
        }
        let _ = writeln!(md, "4. Vacuum-degas the mix for 2-3 minutes at ≥27 inHg.");
        if pour.layer_index == 0 {
            let _ = writeln!(
                md,
                "5. Pour into the mold cup. Insert the plug from +z, \
                 displacing silicone to shape the inner cavity."
            );
        } else {
            let _ = writeln!(
                md,
                "5. Place the cured layer {} (from the previous pour) \
                 inside this mold cup as the plug. Pour around it.",
                pour.layer_index - 1,
            );
        }
        if let Some(protocol) = protocol {
            let _ = writeln!(
                md,
                "6. Cure for ≥{} hr at 73 °F (pot life: {} min).",
                protocol.cure_time_hours, protocol.pot_life_minutes,
            );
        } else {
            let _ = writeln!(
                md,
                "6. Cure per the Smooth-On TDS at 73 °F (pot life per TDS)."
            );
        }
        let _ = writeln!(
            md,
            "7. Demold from the mold cup{}.",
            if pour.layer_index == 0 {
                " and carefully extract the plug"
            } else {
                ""
            }
        );
        md.push('\n');
    }
}

fn write_mass_budget_summary(md: &mut String, spec: &CastSpec, pour_volumes: &[PourVolume]) {
    let _ = writeln!(md, "## Mass Budget");
    md.push('\n');
    let total_g: f64 = pour_volumes.iter().map(|p| p.pour_mass_kg * KG_TO_G).sum();
    let budget_g = spec.mass_budget_kg * KG_TO_G;
    let _ = writeln!(
        md,
        "- Total silicone mass across all layers: **{:.2} g** ({} layers).",
        total_g,
        spec.layers.len()
    );
    let _ = writeln!(
        md,
        "- Per-pour budget: **{:.2} g** ({:.4} kg). Every layer's pour mass \
         falls within budget per the F2 export gate.",
        budget_g, spec.mass_budget_kg,
    );
    let _ = writeln!(
        md,
        "- Same-material layers' aggregate may exceed user holdings even \
         when each per-pour mass fits — verify total holdings against \
         per-material sums in the summary table above."
    );
    md.push('\n');
}

/// Return `(mix_ratio, pot_life, cure_time)` rendered cells for a
/// layer. Materials without a Smooth-On anchor (or with an unknown
/// key) collapse all three cells to [`TDS_LOOKUP_PLACEHOLDER`].
fn cure_protocol_cells(anchor_key: Option<&'static str>) -> (String, String, String) {
    if let Some(key) = anchor_key {
        if let Some(protocol) = lookup_cure(key) {
            return (
                protocol.mix_ratio_a_to_b.to_string(),
                format!("{} min", protocol.pot_life_minutes),
                format!("{} hr", protocol.cure_time_hours),
            );
        }
    }
    (
        TDS_LOOKUP_PLACEHOLDER.to_string(),
        TDS_LOOKUP_PLACEHOLDER.to_string(),
        TDS_LOOKUP_PLACEHOLDER.to_string(),
    )
}

/// Label a layer's position for the per-layer procedure heading.
/// Innermost-first ordering means index 0 is "innermost"; the last
/// index is "outermost"; everything between is "middle".
const fn layer_position_label(layer_index: usize, layer_count: usize) -> &'static str {
    if layer_index == 0 {
        "innermost"
    } else if layer_index + 1 == layer_count {
        "outermost"
    } else {
        "middle"
    }
}

// ===== v2 — curve-following multi-piece procedure =================

/// Render the v2 curve-following multi-piece Markdown procedure for
/// `spec` + `ribbon` given the per-layer `pour_volumes`.
///
/// Parallel to [`generate_procedure_markdown`] but for v2's
/// 2-piece-per-layer geometry (per
/// `docs/CURVE_FOLLOWING_DESIGN.md` §"Output artifacts"). The
/// renderer references `mold_layer_{i}_piece_{0|1}.stl` filenames,
/// adds a "Cast Geometry" section that surfaces the centerline
/// arc length + max tangent rotation, replaces v1's
/// straight-pull demold prose with explicit piece-removal order
/// ("piece 0 first, then piece 1 — the part slides out along
/// the centerline"), and adds an iter-1 manual-clamping note
/// (registration uses §M-S2 symmetric dowel holes; v2 iter-1
/// hand-aligns + clamps with rubber bands when dowels disabled).
///
/// Materials table, generic Smooth-On guidance, and mass-budget
/// summary are shared verbatim with v1 (same pour-volume
/// computation drives the budget gate in both
/// [`CastSpec::export_molds`] and [`CastSpec::export_molds_v2`]).
///
/// The function is pure (no IO, no time-dependent fields) so tests
/// can pin output bit-exactly. [`CastSpec::write_procedure_v2`] is
/// the convenience FS wrapper.
///
/// # Panics
///
/// Length of `pour_volumes` must equal `spec.layers.len()`. The
/// caller is expected to pass a freshly-computed
/// `compute_pour_volumes` result; mismatched lengths are a programming
/// error and panic via the `length` assertion.
#[must_use]
pub fn generate_procedure_markdown_v2(
    spec: &CastSpec,
    pour_volumes: &[PourVolume],
    ribbon: &Ribbon,
) -> String {
    assert_eq!(
        pour_volumes.len(),
        spec.layers.len(),
        "pour_volumes must be parallel to spec.layers"
    );

    let apex_pour = matches!(
        &ribbon.pour_gate,
        PourGateKind::Default(s) if s.layout == PourGateLayout::ApexAxial
    );

    let mut md = String::new();
    write_header_v2(&mut md, spec, apex_pour);
    write_cast_geometry_v2(&mut md, ribbon);
    write_print_orientation_v2(&mut md, apex_pour);
    write_chamfer_recipe_v2(&mut md);
    write_target_fdm_floor_v2(&mut md);
    write_cfview_sanity_check_v2(&mut md, apex_pour);
    write_cap_plane_chamfer_v2(&mut md);
    write_seam_face_edge_v2(&mut md);
    write_materials_table(&mut md, spec, pour_volumes);
    write_generic_guidance(&mut md);
    write_v2_assembly_note(&mut md, ribbon);
    write_v2_cup_half_clamping_note(&mut md, ribbon);
    write_v2_pour_gate_note(&mut md, ribbon);
    write_per_layer_sections_v2(&mut md, spec, pour_volumes, ribbon);
    write_v2_post_cure_assembly(&mut md, spec);
    write_mass_budget_summary(&mut md, spec, pour_volumes);
    md
}

fn write_v2_post_cure_assembly(md: &mut String, spec: &CastSpec) {
    let _ = writeln!(md, "## Post-Cure Assembly + Disassembly");
    md.push('\n');
    let _ = writeln!(
        md,
        "After all {} layers cure + demold, you have {} standalone \
         silicone tubes — one per layer — each with the next-inner \
         tube's outer geometry as its inner cavity (innermost = \
         layer 0; outermost = layer {}).",
        spec.layers.len(),
        spec.layers.len(),
        spec.layers.len().saturating_sub(1),
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Assembly**: nest the tubes innermost-first. Slide layer 0 \
         into the inner cavity of layer 1; the cured silicone is \
         flexible enough to flex over the 0.5-1 mm inter-layer \
         interference fit. Apply Smooth-On Silicone Slip (or any \
         silicone-safe lubricant) sparingly to ease insertion if \
         needed. Repeat with each successive outer layer until all \
         tubes are stacked into a single multi-layer device."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Disassembly** (for cleaning or single-layer replacement): \
         reverse the assembly order. Working from the outermost \
         layer inward, peel each tube off the next-inner one. \
         Flexibility allows individual layer extraction without \
         disturbing the others — replace one worn-out layer without \
         re-casting the whole stack."
    );
    md.push('\n');
}

fn write_header_v2(md: &mut String, spec: &CastSpec, apex_pour: bool) {
    let _ = writeln!(
        md,
        "# Cast Procedure (v2.1 curve-following, detachable-shell)"
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "Generated by `cf-cast` for a {}-layer cast (innermost-first) \
         with v2.1 curve-following 2-piece molds + one printed plug \
         per layer. Each layer is cast independently against its own \
         plug, producing a detachable cured silicone tube that nests \
         with the other layers post-cure for assembly + disassembly.",
        spec.layers.len()
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "> **📁 Files.** This `procedure.md` sits at the cast-folder root; **every STL \
         to print is in the `stls/` subfolder.** Read this procedure first, then print \
         from `stls/` (filenames below are relative to it). `cf-viewer` pointed at \
         either the cast folder or `stls/` finds them."
    );
    md.push('\n');
    if apex_pour {
        let _ = writeln!(
            md,
            "**Orientation convention**: orient the assembled mold with \
             **+Z up** during pour + cure (dome apex on top). A single \
             straight pour bore sits at the dome apex on the seam (it \
             splits the flange, so it appears as a half-trough on each \
             cup half that re-registers into one round hole). Air vents \
             are hand-drilled (tiny ~0.3-1.0 mm holes) at the apex + any \
             high spots — see `## Pour Gate + Vent`."
        );
    } else {
        let _ = writeln!(
            md,
            "**Orientation convention**: orient the assembled mold with \
             **+Z up** during pour + cure. The pour gate + vent form a V \
             at the dome end of the centerline (opposite the cap plane); \
             both holes are visible at the TOP of the assembly. Pour leg \
             on the Positive piece (`_piece_1`, +binormal side of the \
             seam), vent leg on the Negative piece (`_piece_0`, -binormal \
             side)."
        );
    }
    md.push('\n');
    let _ = writeln!(
        md,
        "Workshop procedure starting-point. Mix ratios, pot life, and \
         cure times are per Smooth-On Technical Data Sheets at 73 °F \
         (23 °C). Treat the steps below as a baseline — adjust against \
         bench reality after iter-1."
    );
    md.push('\n');
}

fn write_cast_geometry_v2(md: &mut String, ribbon: &Ribbon) {
    let _ = writeln!(md, "## Cast Geometry");
    md.push('\n');
    let arc_length_mm = ribbon.arc_length() * 1000.0;
    let max_rotation_deg = ribbon.max_tangent_rotation_rad().to_degrees();
    let _ = writeln!(
        md,
        "- Centerline arc length: **{arc_length_mm:.1} mm** \
         (informs demold travel — pieces slide along this distance)."
    );
    let _ = writeln!(
        md,
        "- Max tangent rotation along the centerline: **{max_rotation_deg:.1}°** \
         (v2 ships 2 pieces; above 120° the cast is refused as un-demoldable \
         per `CURVE_FOLLOWING_DESIGN.md` §\"Piece count selection\")."
    );
    let _ = writeln!(
        md,
        "- Piece count per layer: **2** (`piece_0` = ribbon-negative side, \
         `piece_1` = ribbon-positive side)."
    );
    md.push('\n');
}

// ===== S6 — print-prep documentation ==============================
// Per-piece print orientation (recon-1 §G-4, S6-revised), first-layer
// chamfer recipe (§G-6 reframed under S6 orientation), Bambu A1 +
// default + Jayo target FDM floor (§G-3), and the cf-view sanity-
// check workflow gating §G-11 #3 before the workshop user starts
// slicing.

/// Recon-1 §G-4 originally locked cup pieces to "seam face on bed"
/// assuming registration pins lived entirely inside cup-wall
/// material. S3 shipped pins extending symmetrically along the
/// ribbon binormal across the seam plane, placing the workshop-
/// visible ridge ON THE EMPTY side of the seam — which under
/// seam-face-down would point INTO the bed (geometrically
/// impossible). S6 revised the cup orientation to seam-face-UP.
/// §M-S4 (2026-05-27) retired the prismatic-pin registration path
/// entirely; the seam-face-UP orientation remains preferred for the
/// dowel-hole pattern (holes carve straight through the seam face,
/// printable as recessed cavities without internal support when the
/// seam face is up).
fn write_print_orientation_v2(md: &mut String, apex_pour: bool) {
    let _ = writeln!(md, "## Per-Piece Print Orientation");
    md.push('\n');
    let _ = writeln!(
        md,
        "Each STL has one geometrically-correct print orientation \
         picked from the FDM-friendly geometry contract (recon-1 \
         §G-4 in `docs/CF_CAST_FDM_FRIENDLY_GEOMETRY_RECON.md`, \
         S6-revised — see §G-4 revision note at the end of this \
         section)."
    );
    md.push('\n');
    write_print_orientation_cup_pieces(md);
    write_print_orientation_plug_pieces(md);
    write_print_orientation_funnel_platform(md, apex_pour);
    write_print_orientation_g4_revision(md);
}

fn write_print_orientation_cup_pieces(md: &mut String) {
    let _ = writeln!(md, "### Cup pieces (`mold_layer_*_piece_{{0|1}}.stl`)");
    md.push('\n');
    let _ = writeln!(
        md,
        "**Orient seam face UP, outer curved cup surface DOWN on \
         bed.** Add a brim (5-8 mm, 1 layer) for curved-surface \
         adhesion; supports not required (cup walls build layer-\
         by-layer upward from a continuous bottom contour)."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "Seam-face-UP also fits the §M-S2 symmetric dowel-hole \
         pattern: dowel holes carve straight through the seam face \
         along the ribbon binormal (perpendicular to the seam \
         plane). With the seam face UP, each hole opens upward as a \
         shallow recessed cavity (printable without internal support \
         or bridging). Pre-§M-S4 this section described the now-\
         retired prismatic-pin registration ridge; the same \
         seam-face-UP orientation carries over for dowel holes \
         without modification."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "The cap-plane wall carrying the S4 plug-floor-lock socket \
         is a vertical wall in this orientation; the socket prints \
         as a horizontal SIDE recess into the vertical wall — no \
         first-layer adhesion concern at the socket interior."
    );
    md.push('\n');
}

fn write_print_orientation_plug_pieces(md: &mut String) {
    let _ = writeln!(md, "### Plug pieces (`plug_layer_*.stl`)");
    md.push('\n');
    let _ = writeln!(
        md,
        "**Orient dome end DOWN on bed, cap-plane face UP, the \
         truncated-pyramid lock pointing UP.** Add a brim (5-8 mm, \
         1 layer) for the dome contact patch; brief minor supports \
         may be needed for the first dome-curvature layers."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Cap-plane-face-DOWN is INVALID** — the S4 truncated \
         pyramid protrudes from the cap-plane face along \
         `cap_normal` (away from plug body), so cap-plane-face-\
         down would put the pyramid INTO the bed (geometrically \
         impossible). Side-orient (centerline horizontal) is \
         geometrically valid but requires extensive supports for \
         body curvature overhangs; not recommended."
    );
    md.push('\n');
}

fn write_print_orientation_funnel_platform(md: &mut String, apex_pour: bool) {
    let _ = writeln!(md, "### Funnel + platform (one-time prints)");
    md.push('\n');
    if apex_pour {
        let _ = writeln!(
            md,
            "`funnel.stl`: **straight-spout funnel** — a vertical bowl \
             with a straight (un-bent) vertical nipple, since the apex \
             pour bore points straight up when the mold is +Z up. Print \
             with the **bowl-mouth disk DOWN on the build plate** (mouth \
             disk = first layer; the bowl widens upward; the straight \
             nipple points down into the bed). No cantilever, so no \
             supports needed for the spout. Print once for the whole \
             multi-layer device — reuse across every layer's pour."
        );
    } else {
        let _ = writeln!(
            md,
            "`funnel.stl`: **bent-spout funnel** with a vertical bowl + \
             angled nipple matching the pour-gate's 30° splay (the cup \
             pour-gate cylinder is tilted 30° from the dome's outward \
             axis; the bent nipple lets the workshop user orient the \
             assembled mold +Z up with the bowl mouth facing straight up \
             for ladle-pouring). Print with the **bowl-mouth disk DOWN on \
             the build plate** (mouth disk = first layer; the bowl widens \
             upward from the mouth; the tilted nipple cantilevers ~7.5 mm \
             horizontally from the bowl side). **Enable auto-supports in \
             the slicer**: the cantilevered nipple needs supports to \
             print clean — cleaned off after the print. Alternative: \
             rotate the print so the nipple lies along the build plate \
             (bowl tilted on its side) to avoid supports — slicer choice; \
             STL is unchanged. Print once for the whole multi-layer \
             device — reuse across every layer's pour."
        );
    }
    md.push('\n');
    let _ = writeln!(
        md,
        "`platform.stl`: post-S4 bare flat slab (pre-S4 T-bar pocket \
         retired with the plug-shaft removal). Trivial orientation \
         — any face down works; no supports."
    );
    md.push('\n');
}

fn write_print_orientation_g4_revision(md: &mut String) {
    let _ = writeln!(md, "### §G-4 revision note");
    md.push('\n');
    let _ = writeln!(
        md,
        "Recon-1 §G-4 originally locked cup pieces to **seam face \
         on bed** on the assumption that registration pins lived \
         entirely inside cup-wall material. S3 shipped pins \
         extending symmetrically across the seam plane — ridge \
         points into bed under seam-face-down. S6 revised to \
         seam-face-UP as documented above. §M-S4 (2026-05-27) \
         retired the prismatic-pin registration path entirely in \
         favor of the §M-S2 symmetric dowel-hole pattern; the \
         seam-face-UP orientation carries over (dowel holes are \
         printable as upward-opening recesses without modification \
         to the orientation lock)."
    );
    md.push('\n');
}

fn write_chamfer_recipe_v2(md: &mut String) {
    let plug_chamfer_mm = PrismaticPinSpec::plug_lock_default().base_chamfer_m * 1000.0;
    let _ = writeln!(md, "## First-Layer Chamfer Recipe");
    md.push('\n');
    let _ = writeln!(
        md,
        "Recon-1 §G-6 envisioned the chamfer band on each \
         `PrismaticPin` as bed-adjacent FDM-elephant-foot relief. \
         Post-§M-S4 the cup-pin registration path is retired (see \
         `## v2 Mold Assembly` above for the symmetric dowel-hole \
         replacement); only the plug-floor-lock chamfer remains. \
         Under the dome-end-DOWN plug orientation the chamfer band \
         lives at the `-axis_unit` end of the lock pyramid — deep \
         inside the plug body, never at the bed-touching first \
         layer, never workshop-visible from outside the printed \
         part. The chamfer is **SDF/MC topology continuity at the \
         deepest-in-material corner**, retained at the §G-6 \
         typed-range default pending S7 caliper data."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Plug-lock chamfer** ({plug_chamfer_mm:.2} mm default per \
         `PrismaticPinSpec::plug_lock_default`, typed-range §G-6 / \
         pinned post-S7 §G-8): retained at default. Under the dome-\
         end-DOWN plug orientation `+axis_unit = +cap_normal` \
         points UP, so the chamfer band at `-axis_unit` lives \
         **inside the plug body** (below the cap-plane face). The \
         workshop-visible pyramid above the cap-plane is the \
         unchamfered main-taper portion only. The matching socket's \
         chamfer band on each cup-piece carves into the cup body \
         cavity (no-op subtract)."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Slicer-level elephant-foot compensation** (Bambu Studio \
         / PrusaSlicer / OrcaSlicer): set to **0.0 mm**. The \
         plug-lock pyramid/socket diametral + axial clearances are \
         tuned by `PrismaticPinSpec` (S7 caliper pass per §G-8); \
         the dowel-hole radial clearance is tuned by \
         `DowelHoleSpec` (§M-S2 / §M-S3). Adding slicer-level \
         compensation on top would tighten both fits past their \
         spec budgets and the per-layer cup-wall surface past spec \
         wall-thickness."
    );
    md.push('\n');
}

fn write_target_fdm_floor_v2(md: &mut String) {
    let _ = writeln!(md, "## Target FDM Floor (Bambu A1 + Default + Jayo)");
    md.push('\n');
    let _ = writeln!(
        md,
        "Recon-1 §G-3 picks **Bambu A1 + Bambu Studio default settings \
         + Jayo generic PLA** as the consumer-FDM tolerance floor for \
         the mating-feature geometry. Print mold + plug + funnel + \
         platform STLs against this baseline as the regression \
         target. Calibrated Bambu Lab (X1C / P1S with PEI sheet + \
         tuned profile + Bambu PLA) is acceptable as a side-\
         comparison reference but is NOT the regression target — \
         chasing calibrated-printer tolerances would let the geometry \
         drift past Bambu A1 + default capabilities."
    );
    md.push('\n');
    let _ = writeln!(md, "Slicer baseline:");
    md.push('\n');
    let _ = writeln!(
        md,
        "- **Layer height**: 0.2 mm (Bambu Studio default).\n\
         - **Wall loops**: 3 (default).\n\
         - **Infill**: 15% gyroid (default; mold pieces don't need \
         structural infill — silicone pour pressure is low).\n\
         - **Supports**: none for cup pieces (continuous bottom \
         contour); brim 5-8 mm 1-layer for cup outer-surface \
         adhesion; brim + brief dome-curvature supports for plug.\n\
         - **Elephant-foot compensation**: 0.0 mm (geometry \
         includes chamfer bands per the previous section).\n\
         - **Filament**: Jayo PLA generic profile (~220 °C nozzle, \
         60 °C bed); equivalent generic-PLA profile if Jayo \
         unavailable."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "`PrismaticPinSpec::cup_pin_default` + \
         `PrismaticPinSpec::plug_lock_default` diametral + axial \
         clearances default to the §G-6 typed-range mid-points; \
         exact values are pinned to caliper data from the S7 \
         workshop-physical Bambu A1 calibration pass."
    );
    md.push('\n');
}

fn write_cfview_sanity_check_v2(md: &mut String, apex_pour: bool) {
    let _ = writeln!(md, "## cf-view Sanity-Check Workflow");
    md.push('\n');
    let _ = writeln!(
        md,
        "Before slicing, open each STL in cf-view (workshop laptop \
         viewer) and verify the recon-1 §G-11 #3 visual gate:"
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "1. **Cup pieces** (`mold_layer_*_piece_0.stl` + `_piece_1.stl`):\n   \
         - Dowel holes: cylindrical recessed cavities in BOTH \
         halves' seam faces, placed by the seam-placement solver at \
         the body's long-axis extremes in the flange band (§M-S2). \
         The hole pattern is symmetric — the two halves should \
         mirror each other exactly along the seam plane.\n   \
         - No trapezoidal / truncated-pyramid pin remnants on the \
         seam face (the §M-S4-retired prismatic-pin registration \
         path).\n   \
         - No cylindrical pin remnants (pre-S3 cylinder primitive \
         retired).\n   \
         - No T-bar / stem / T-slot remnants on the cap-plane wall \
         (pre-S4 plug-shaft mechanism retired).\n   \
         - Cap-plane wall carries a clean rectangular plug-floor-\
         lock socket recess (S4) — recessed cavity, NOT a through-\
         hole."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "2. **Plug pieces** (`plug_layer_*.stl`):\n   \
         - Cap-plane face carries a single truncated-pyramid lock \
         protruding from the cap-plane face along `cap_normal` \
         (S4); flat tapered lateral faces, sharp edges.\n   \
         - No T-bar / stem / cylindrical-shaft remnants (pre-S4 \
         geometry retired); no separate dome-pin (pre-S4 dome-pin \
         gone too).\n   \
         - Dome end is smooth and closed; the workshop-visible \
         pyramid above the cap-plane is the unchamfered main-taper \
         only (the chamfer band lives inside the plug body and is \
         not visible from outside)."
    );
    md.push('\n');
    if apex_pour {
        let _ = writeln!(
            md,
            "3. **Funnel** (`funnel.stl`): straight-spout funnel — \
             vertical bowl + straight (un-bent) vertical nipple as one \
             connected body, joined at the bowl-bottom shoulder. Nipple \
             Ø matches the cup pour-gate Ø minus the funnel's asymmetric \
             diametral clearance (`cf-cast` \
             `funnel::NIPPLE_DIAMETRAL_CLEARANCE_M`). Interior bore \
             tapers smoothly from the bowl mouth down to the nipple bore \
             (single conical lumen). No flat flange disk; no floating \
             components; the nipple points straight down (no tilt)."
        );
    } else {
        let _ = writeln!(
            md,
            "3. **Funnel** (`funnel.stl`): bent-spout funnel — vertical \
             bowl + 30°-tilted nipple as one connected body, joined at \
             the bowl-bottom shoulder. Nipple Ø matches the cup pour-gate \
             Ø minus the funnel's asymmetric diametral clearance \
             (`cf-cast` `funnel::NIPPLE_DIAMETRAL_CLEARANCE_M`). Interior \
             bore tapers smoothly from the bowl mouth down to the nipple \
             bore (single conical lumen). No flat flange disk; no \
             floating components."
        );
    }
    md.push('\n');
    let _ = writeln!(
        md,
        "4. **Platform** (`platform.stl`): bare flat slab (post-S4 \
         pocket retirement). If the slab shows ANY pocket / cavity \
         / protrusion, flag a regression — S4 retired all features."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "If any of the above checks fail, do NOT proceed to print — \
         file a regression issue with a cf-view screenshot. \
         §G-11 #1 (§R1 connectivity inspector) + §G-11 #2 \
         (`PrismaticPin` bit-precise fit invariant) pass on cargo \
         tests; this cf-view gate is the workshop-user-physical \
         third gate before the Bambu A1 print gate (§G-11 #4)."
    );
    md.push('\n');
}

fn write_cap_plane_chamfer_v2(md: &mut String) {
    let _ = writeln!(md, "## Cap-Plane Edge Chamfer (Expected MC Quantization)");
    md.push('\n');
    let _ = writeln!(
        md,
        "When inspecting STLs in cf-view, you will see a ~3 mm-wide \
         ring of slightly-rounded triangulation at the cap-plane \
         EDGE — where the flat cap-plane meets the curving body \
         wall. On plug pieces this is the cap-plane face perimeter \
         (cap-plane × curving plug body wall). On cup pieces this \
         is the body-cavity opening perimeter on the cap-plane wall \
         (cap-plane × curving cup body cavity wall). It does NOT \
         appear at the plug-lock socket recess perimeter (the \
         truncated-pyramid socket has FLAT lateral walls, no \
         derivative discontinuity with the cap-plane). This is \
         **expected geometry, not a defect.**"
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "- **Cap-plane CENTER is bit-precise flat.** 70-95% of \
         cap-face triangles land within 10 µm of the cap-plane \
         (`Solid::plane`'s linear SDF placed exactly by \
         marching-cubes linear interpolation — same mechanism as the \
         seam-face flatness invariant per recon-4 (P) §F-4).\n\
         - **Cap-plane EDGE has a ≤100 µm chamfer band.** \
         The sharp ~90° corner between flat cap-plane and curving \
         body wall is a derivative discontinuity in the \
         piecewise-defined SDF (`max(shell_sdf, plane_sdf)`); MC \
         cells straddling the corner interpolate vertices across \
         the branch boundary, producing one-cell-wide (~3 mm) \
         chamfering. Intrinsic to marching-cubes on any \
         piecewise-SDF max-corner; cannot be eliminated SDF-side at \
         any cell size short of adaptive-mesh infrastructure."
    );
    md.push('\n');
    let _ = writeln!(md, "**Workshop guidance:**");
    md.push('\n');
    let _ = writeln!(
        md,
        "- **Do NOT sand the cap-plane edge flat.** The chamfer \
         band's max deviation (~100 µm) is below the §G-3 target \
         FDM floor's slicer-to-print quantization (Bambu A1 default \
         0.4 mm extrusion / 0.2 mm layer height; typical 0.1-0.2 mm \
         dimensional tolerance). Sanding the STL-level chamfer \
         would not change the printed plug-to-cup-floor mating \
         interface — the printer quantizes the edge to its own \
         grid regardless.\n\
         - **PR #255 era shipped with the same chamfer band**, and \
         the workshop iter-2 print on calibrated Bambu was \
         workshop-accepted. Verified 2026-05-25 via git-bisect — \
         cap-plane edge geometry is bit-precisely identical \
         between PR #255 (`aadcfed6`) and current dev; see \
         `docs/CF_CAST_CAP_PLANE_FLATNESS_BOOKMARK.md` for the \
         measurement protocol + the spatial-radial-bin probe that \
         distinguished the invariant edge ring from the \
         mating-mechanism-dependent interior.\n\
         - **The chamfer is at the EDGE not the CENTER.** If \
         cf-view shows the WHOLE cap-face faceted (not just the \
         ~3 mm-wide perimeter ring), THAT would be a regression — \
         file an issue with a cf-view screenshot. The center-flat \
         vs edge-chamfered distinction is the diagnostic."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Distinct from `## First-Layer Chamfer Recipe`** above: \
         that section concerns the SDF-side first-layer chamfer \
         BAND on pin/lock features (a deliberate `PrismaticPin` \
         geometry primitive for FDM topology continuity at the \
         deepest-in-material corner). The cap-plane edge chamfer \
         documented here is an MC-quantization byproduct of the \
         body × cap-plane derivative discontinuity, NOT a \
         deliberately-emitted feature."
    );
    md.push('\n');
}

// Linear writeln!s + a single bullet-list block; factoring out subsections would
// just shuffle the prose into helper names without reducing complexity.
#[allow(clippy::too_many_lines)]
fn write_seam_face_edge_v2(md: &mut String) {
    let _ = writeln!(
        md,
        "## Seam-Face Edge Non-Flatness (Expected Centerline Curvature + MC)"
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "When inspecting cup-piece STLs in cf-view, you will see what \
         looks like seam-face non-flatness at the **dome end** (high Z, \
         where the seam plane meets the cup body's dome cap) and the \
         **cap-plane end** (low Z, where the seam plane meets the \
         cap-plane wall). This is **expected geometry, not a defect.**"
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "- **The seam face follows the curved centerline.** It is NOT a \
         single flat plane — it is a curved ribbon swept along the \
         centerline polyline (per-segment binormal frame). Even with \
         `max tangent rotation: 0.1°` (typical for sock-shaped scans), \
         the centerline translates ~5-7 mm in the binormal direction \
         across the Z extent of the cup body. What looks like \
         seam-face non-flatness in cf-view is mostly this translation \
         — at any single Z, the seam face is **per-tri flat to within \
         one MC cell width** (~200 µm at 3 mm cells).\n\
         - **At the dome+cap ENDS the centerline curvature is more \
         visible** because the cup body cavity is smaller there, so \
         the seam face's binormal-direction Y range stands out against \
         the narrow cavity. At the cup's mid-section, the cavity is \
         wider so the seam-face curvature is proportionally less \
         noticeable in cf-view.\n\
         - **Per-tri max deviation ≤ 200 µm** across all seam-face \
         regions (verified empirically 2026-05-25 against \
         `~/scans/cast_iter1*/mold_layer_*_piece_*.stl`). Same \
         below-print-resolution argument as `## Cap-Plane Edge \
         Chamfer` above: a 200 µm STL-level deviation does not \
         survive the Bambu A1 default 0.4 mm extrusion / 0.2 mm layer \
         height quantization."
    );
    md.push('\n');
    let _ = writeln!(md, "**Workshop guidance:**");
    md.push('\n');
    let _ = writeln!(
        md,
        "- **Do NOT try to flatten the seam face globally.** The seam \
         face is intentionally curved (follows the centerline). \
         Flattening to a single plane would break the recon-4 (P) \
         §F-4 bit-precise SDF-halfspace invariant + the workshop fit \
         between the two cup halves (which fit because both halves' \
         seam faces follow the SAME curved ribbon).\n\
         - **Workshop user has empirical acceptability precedent.** \
         The PR #255 era (`aadcfed6`) shipped with the same \
         curved-centerline seam face + iter-2 print on calibrated \
         Bambu was workshop-accepted. The 2026-05-25 (5') bisect on \
         the cap-plane edge applies the same logic here — the seam \
         face geometry is driven by `Ribbon::halfspace_solid` + \
         pre-arc body derivation, both of which are continuous since \
         2026-05-19.\n\
         - **Registration-independent: no remediation via \
         registration geometry.** A 2026-05-25 no-pins regen \
         (`registration_pins.enabled = false` at \
         `~/scans/cast_iter1_nopins/`) confirmed the dome-edge + \
         cap-edge seam-face triangulation is bit-precisely identical \
         with-pins vs without-pins. The cup-pin mesh-CSG (since \
         retired in §M-S4) and the §M-S2 dowel-hole subtracts only \
         remesh the INTERIOR of the seam face (around each feature), \
         NOT the dome or cap-plane edges. So registration-geometry \
         tweaks cannot mitigate the dome/cap-edge appearance."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Distinct from `## Cap-Plane Edge Chamfer` above:** that \
         section concerns the cap-plane × curving-body-wall corner on \
         plug + cup-floor faces (~3 mm-wide chamfer ring at the \
         cap-plane perimeter). The seam-face edge non-flatness here \
         is on the cup-piece SEAM faces and is driven by \
         centerline-curvature × MC quantization at the dome+cap ends. \
         Different root causes, both below print resolution, both \
         (4')-pattern accepted."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Plug-lock socket mouth (cup-piece cap-plane wall):** the \
         `SubtractTruncatedPyramid` mesh-CSG carve of the plug-lock \
         socket recess inherits ~100 µm cap-plane edge chamfer at the \
         socket mouth perimeter (manifold3d boolean subtract on an \
         already-MC-quantized cap-plane face). Workshop user 2026-05-24 \
         night cf-view flagged this as \"matter obstructing the \
         opening\" (Finding C in `docs/CF_CAST_POST_SALVAGE_TRIAGE.md`). \
         Expected magnitude is ~100 µm — well below the triage doc's \
         <0.5 mm workshop-acceptability threshold. If cf-view shows \
         the obstruction is < 0.5 mm thick, accept it (workshop user \
         can file off any visible artifact in 30 seconds before \
         pressing the plug into the socket). If the obstruction is \
         visibly > 0.5 mm thick, file a regression issue with a \
         cf-view screenshot — that would warrant a separate recon arc \
         on the boolean-junction geometry."
    );
    md.push('\n');
}

// Mostly prose writeln!s describing dowel placement + bolt-pattern
// interleave; the v2 assembly note grew past clippy's 100-line default
// once the §M dowel section landed alongside the §B bolt section.
// Factoring per-subsection into helpers would just shuffle the prose
// into named functions without reducing complexity.
#[allow(clippy::too_many_lines)]
fn write_v2_assembly_note(md: &mut String, ribbon: &Ribbon) {
    let _ = writeln!(md, "## v2 Mold Assembly");
    md.push('\n');
    // §M-S4 (2026-05-27) retired the legacy prismatic-pin
    // registration prose (RegistrationKind::Pins arm). Dowel holes
    // (§M-S2) are the sole inter-piece registration mechanism; the
    // workshop user inserts loose printed dowels through matching
    // holes at assembly time. Per
    // [[project-cf-cast-unified-mating-plane-recon]] §M-S4.
    match ribbon.dowel_hole.spec() {
        None => {
            let _ = writeln!(
                md,
                "Each layer's mold is two ribbon-cut pieces \
                 (`_piece_0` + `_piece_1`) that meet along the \
                 curve-following seam. This cast has no integral \
                 registration features (`DowelHoleKind::None`); \
                 align the pieces by hand and clamp with rubber bands \
                 or wide tape during pour + cure. Each piece's seam \
                 face is bit-precise flat to the ribbon plane via \
                 the cup-piece SDF halfspace intersect with \
                 `overlap_m = 0` (post-§M-S1 flush mating; MC's \
                 linear-SDF interpolation places seam-cap vertices \
                 exactly on the plane), so the two halves butt flush \
                 at the seam with zero gap and hand alignment only \
                 needs to bring the cup outlines into registration."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "If silicone leaks through the seam during pour, add a \
                 small fillet of mold release or putty along the outside \
                 of the seam before the next layer. Document the leak \
                 position for the post-iter-1 registration-feature \
                 decision (enable dowel holes, dovetails, or magnets)."
            );
        }
        Some(spec) => {
            // §M-S2 of the unified-mating-plane arc: SubtractCylinder
            // holes per dowel, placed by the seam-placement solver at
            // the body's long-axis extremes (count emergent per layer),
            // identical on both cup-halves. Workshop user supplies loose
            // printed PLA dowels and inserts them through matching holes
            // at assembly time.
            let diameter_mm = spec.diameter_m * 1000.0;
            let clearance_mm = spec.clearance_m * 1000.0;
            let depth_mm = spec.depth_m * 1000.0;
            let hole_diameter_mm = 2.0_f64.mul_add(clearance_mm, diameter_mm);
            let _ = writeln!(
                md,
                "Each layer's mold is two ribbon-cut pieces \
                 (`_piece_0` + `_piece_1`) that meet along the \
                 curve-following seam. **Symmetric dowel holes** \
                 ({hole_diameter_mm:.2} mm Ø — \
                 {diameter_mm:.1} mm nominal dowel × \
                 2 × {clearance_mm:.2} mm radial clearance, \
                 {depth_mm:.1} mm deep per half) are carved through \
                 BOTH cup-halves' mating faces. The seam-placement \
                 solver positions the dowels at the body's long-axis \
                 extremes (maximum moment arm, so a registration pair \
                 resists lateral skew most effectively); the per-layer \
                 count is emergent — typically two (one at each \
                 long-axis end), dropping only where the flange band \
                 cannot host a feasible hole. The hole pattern is \
                 identical on both halves.",
            );
            md.push('\n');
            // §M-S2 followup: total tip slack is the SUM of the
            // dowel's own insertion slack + the hole's axial slack
            // (cold-read 2026-05-27 caught the prose understating
            // this by half by counting only one).
            let dowel_insertion_slack_mm = crate::dowel::DOWEL_INSERTION_SLACK_M * 1000.0;
            let hole_axial_slack_mm = crate::dowel_hole::HOLE_AXIAL_SLACK_M * 1000.0;
            let dowel_length_mm = depth_mm.mul_add(2.0, -2.0 * dowel_insertion_slack_mm);
            let total_cavity_mm = depth_mm.mul_add(2.0, 2.0 * hole_axial_slack_mm);
            let tip_slack_mm = (total_cavity_mm - dowel_length_mm) / 2.0;
            let insert_depth_mm = depth_mm + hole_axial_slack_mm - tip_slack_mm;
            let _ = writeln!(
                md,
                "**Print `dowel.stl` first.** The export emits a \
                 single `dowel.stl` containing all printable \
                 PLA dowels ({diameter_mm:.1} mm Ø × \
                 {dowel_length_mm:.1} mm long — sized so each dowel \
                 inserts ~{insert_depth_mm:.1} mm into each cup-half \
                 with {tip_slack_mm:.1} mm assembly slack at each \
                 tip). Print the dowels VERTICAL (cylindrical axis \
                 perpendicular to the build plate; cf-view loads them \
                 oriented this way) so the cylindrical walls print \
                 clean without overhangs. Insert one dowel through \
                 each pair of matching holes to register the two \
                 halves laterally before clamping."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "Each dowel cylinder is centered on the seam plane \
                 along the ribbon binormal (perpendicular to the seam \
                 plane at the dowel position). Holes are gravity-held \
                 with the dowel friction-fit absorbed by the radial \
                 clearance — no latching action. Per recon-4 (P) the \
                 seam face is bit-precise flat via the cup-piece SDF \
                 halfspace intersect (MC's linear-SDF interpolation \
                 places seam-cap vertices exactly on the plane), so \
                 the pieces seat flush around the dowel pattern."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "If a dowel breaks during assembly or the holes drift \
                 out of register on a given print, swap to a fresh \
                 PLA rod cut to {depth_total:.1} mm; the symmetric \
                 dowel-hole pattern means no asymmetry to worry about \
                 between halves. Document fit issues for the post-\
                 iter-3 dowel-spec decision (revisit \
                 `DowelHoleSpec::iter1` diameter / clearance defaults).",
                depth_total = depth_mm * 2.0,
            );
        }
    }
    write_v2_bolt_pattern_note(md, ribbon);
    md.push('\n');
    write_v2_plug_anchor_note(md, ribbon);
}

fn write_v2_bolt_pattern_note(md: &mut String, ribbon: &Ribbon) {
    let Some(spec) = ribbon.bolt_pattern.spec() else {
        return;
    };
    // §B of the unified-mating-plane bolt-pattern arc: SubtractCylinder
    // holes per bolt, placed by the seam-placement solver (even spacing
    // at ≤30 mm pitch, bracketing the pour gate, variable radial offset
    // from the flange band + washer clearance — count emergent per
    // layer). M5 through-bolts + flat washers (×2 per bolt) + hex nuts
    // clamp the two halves at the flange (across a gasket when one is
    // present; iter-1 ships gasketless with mold release + PLA-on-
    // PLA contact under bolt-induced clamp pressure as the seal).
    let clearance_mm = spec.clearance_diameter_m * 1000.0;
    // Minimum bolt length the workshop should source: 2 × flange
    // thickness (the bolt traverse) + 2 × washer (~1 mm each) + nut
    // (~4 mm M5) + bolt-head (~3 mm M5). With 4 mm flange thickness
    // default that's 8 + 2 + 4 + 3 = 17 mm — round up to M5×20 mm
    // (standard stock length, gives ~3 mm thread excess past the nut
    // which is workshop-friendly).
    // Cold-read I3 fix 2026-05-27: prefer FlangeSpec::iter1() over a
    // hard-coded magic number when the ribbon has no flange. In
    // practice the cf-cast-cli validator forbids bolt_pattern without
    // flange + `write_v2_bolt_pattern_note` is gated on
    // `ribbon.bolt_pattern.spec().is_some()`, so this fallback only
    // matters for hand-built test ribbons bypassing the validator.
    let flange_thickness_mm = ribbon.flange.spec().map_or_else(
        || crate::flange::FlangeSpec::iter1().flange_thickness_m * 1000.0,
        |f| f.flange_thickness_m * 1000.0,
    );
    let bolt_traverse_mm = flange_thickness_mm * 2.0;
    // Minimum exact length = traverse + 2 × washer (~1 mm each) + nut
    // (~4 mm M5) + head (~3 mm M5). Round UP to the nearest 5 mm
    // since fastener catalogs stock M5 in 5 mm increments above 10 mm
    // (10, 12, 16, 20, 25, …). At the default 4 mm flange this gives
    // 17 mm minimum → 20 mm workshop pick, with ~3 mm thread excess
    // past the nut.
    let min_bolt_length_mm = bolt_traverse_mm + 2.0 + 4.0 + 3.0;
    let recommended = (min_bolt_length_mm / 5.0).ceil() * 5.0;
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "### M5 through-bolt clamp pattern (§B)\n\
         \n\
         **M5 bolt clearance holes** ({clearance_mm:.1} mm Ø) carve \
         through BOTH cup-halves' flange material. The seam-placement \
         solver spaces them evenly around the seam loop (≤30 mm pitch), \
         brackets the pour gate with a bolt on each side, and sizes each \
         bolt's radial offset so the M5 washer footprint stays inside the \
         flange band and clear of the cup-wall step, the dowel holes, and \
         the pour. Identical pattern on both halves of a given layer; the \
         per-layer hole count is emergent.\n\
         \n\
         **Workshop supplies (per cast assembly)**: per bolt hole — one \
         M5 hex bolt (recommend M5×{recommended:.0} mm to cover the \
         {bolt_traverse_mm:.0} mm PLA traverse + washers + nut + head, with \
         a few mm of thread excess), two M5 flat washers (~10 mm OD; one \
         under the head, one under the nut), and one M5 hex nut. Count the \
         holes in the generated `mold_layer_*` pieces (or in cf-view) for \
         the per-layer quantity.\n\
         \n\
         **Assembly order**: register the two halves with the §M dowels \
         FIRST (the dowel-hole pattern provides lateral alignment so the \
         bolt-clearance holes match up across the seam). Then insert each \
         M5 bolt through the matching bolt-clearance holes on the two \
         halves, slip a washer under each head + nut, and hand-tighten \
         crosswise (like a car lug pattern) for even flange clamp \
         pressure (~1 MPa across the flange contact area at \
         hand-torqued M5 — exceeds the silicone hydrostatic leak \
         pressure by ~1000× so PLA-on-PLA seam contact + mold release \
         should seal without a separate gasket). Engine-valve-cover \
         torque level — snug, not stripped; PLA threads in the \
         workshop user's hand-tools strip well before the bolt design \
         load is exceeded.\n\
         \n\
         The bolt clearance is {clearance_mm:.1} mm with no slide-fit \
         slack — the washer compensates for FDM hole dimensional error \
         (~±0.1 mm typical). If a bolt won't seat, lightly ream the hole \
         with a {clearance_mm:.1} mm drill bit before the next iteration.\n",
    );
}

fn write_v2_plug_anchor_note(md: &mut String, ribbon: &Ribbon) {
    let _ = writeln!(md, "### Plug Anchor");
    md.push('\n');
    match &ribbon.plug_pins {
        PlugPinKind::None => {
            let _ = writeln!(
                md,
                "This cast has no plug-floor-lock geometry \
                 (`PlugPinKind::None`). The plug is positioned in \
                 the assembled mold cup by hand and held there \
                 during pour + cure (workshop user braces the plug \
                 manually or jigs against the cavity dome). \
                 `PlugPinKind::Axial` opt-in adds a truncated-\
                 pyramid press-fit lock to the plug's cap-plane face \
                 + a matching socket recessed into each cup-piece's \
                 cap-plane interior surface; recommended for any \
                 cast where the plug's silicone-displacement weight \
                 + curve geometry makes hand-positioning fiddly."
            );
        }
        PlugPinKind::Axial(spec) => {
            // S4 of the FDM-friendly geometry arc migrated this
            // section from cylindrical plug-shaft + T-bar prose
            // (cup-wall penetration leak path on consumer FDM —
            // recon-1 §G-1) to the truncated-pyramid plug-floor
            // lock vocabulary (interior to the cavity, no through-
            // hole, press-fit against the cup floor).
            let lock_spec = &spec.lock_spec;
            let base_lateral_mm = lock_spec.pin_base_half_extents_m.x * 2.0 * 1000.0;
            let base_binormal_mm = lock_spec.pin_base_half_extents_m.y * 2.0 * 1000.0;
            let tip_lateral_mm = lock_spec.pin_tip_half_extents_m.x * 2.0 * 1000.0;
            let tip_binormal_mm = lock_spec.pin_tip_half_extents_m.y * 2.0 * 1000.0;
            let lock_length_mm = lock_spec.pin_half_length_m * 2.0 * 1000.0;
            let chamfer_mm = lock_spec.base_chamfer_m * 1000.0;
            let diametral_mm = lock_spec.diametral_clearance_m * 1000.0;
            let socket_base_lateral_mm = base_lateral_mm + diametral_mm;
            let _ = writeln!(
                md,
                "Each per-layer plug carries a **truncated-pyramid \
                 lock** at its cap-plane face — \
                 {base_lateral_mm:.1} × {base_binormal_mm:.1} mm \
                 rectangular base, tapered to \
                 {tip_lateral_mm:.1} × {tip_binormal_mm:.1} mm flat \
                 tip, {lock_length_mm:.1} mm long along the cap-\
                 normal, {chamfer_mm:.2} mm base-end chamfer as a \
                 lead-in self-centering aid — protruding away from \
                 the plug body (= downward in pour orientation). \
                 Each cup-piece's cap-plane interior surface carries \
                 a matching socket cavity \
                 ({socket_base_lateral_mm:.2} mm base — \
                 {diametral_mm:.2} mm diametral clearance for a \
                 positional sliding fit); the seam plane bisects \
                 each socket laterally through its center, so each \
                 cup half carves one half of the cross-section \
                 (3-piece shared-primitive invariant). The socket \
                 is a recessed cavity NOT a through-hole — no shaft \
                 penetrates the cup wall, eliminating the silicone-\
                 leak failure mode the pre-S4 cylindrical plug-shaft \
                 was prone to on consumer FDM."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "Workshop assembly: apply mold release (Smooth-On \
                 Ease Release 200 standard) to the pyramid before \
                 seating. Lower the plug into one open cup half \
                 (seam plane up) so the pyramid drops into that \
                 half's floor socket; the tapered lateral faces \
                 self-center the pyramid as it descends. Close the \
                 second cup half over the plug, sandwiching the \
                 pyramid between the two socket halves. Press-stop \
                 tactile feedback = the cup-piece seam halves bottom \
                 out flush against each other when the pyramid is \
                 fully seated. The plug is now positionally \
                 constrained against axial drift + lateral wobble; \
                 combined with the cap-into-dome seating at the dome \
                 end, the plug stays centered in 6 DoF during pour + \
                 cure."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "If the lock doesn't seat (too tight, seam won't \
                 close flush): file the pyramid's lateral faces \
                 lightly to relieve, then re-check the seam. If the \
                 plug wobbles (too loose, plug drifts during pour): \
                 wrap the pyramid base with PTFE tape until snug, OR \
                 tighten `PrismaticPinSpec::plug_lock_default()`'s \
                 `diametral_clearance_m` for the next print. \
                 Document fit tolerances for the S7 workshop-physical \
                 calibration pass on Bambu A1 + default + Jayo."
            );
        }
    }
    md.push('\n');
}

// 4-arm match over (FlangeKind, GasketKind) with multi-paragraph
// prose per branch pushes the line count well past clippy's default
// 100; the function is otherwise simple (linear writeln!s, no
// nested control flow), so factoring each branch into its own
// helper would just shuffle the same prose between identifiers.
#[allow(clippy::too_many_lines)]
fn write_v2_cup_half_clamping_note(md: &mut String, ribbon: &Ribbon) {
    // S3 of the seam-flange arc per recon §F-7. Prose adapts to the
    // combination of FlangeKind + GasketKind: the full clamp-and-pour
    // protocol fires only when both are enabled (the workshop
    // iter-3 default); other combinations get a brief fallback note
    // pointing at the hand-clamp / no-gasket degraded paths.
    let header = match (&ribbon.gasket, ribbon.bolt_pattern.spec()) {
        (GasketKind::Mold(_), _) => "## Cup-Half Clamping with Gasket Installation",
        (GasketKind::None, Some(_)) => "## Cup-Half Clamping (M5 Bolt-Pattern Seal)",
        (GasketKind::None, None) => "## Cup-Half Clamping (Gasketless)",
    };
    let _ = writeln!(md, "{header}");
    md.push('\n');
    match (&ribbon.flange, &ribbon.gasket) {
        (FlangeKind::None, GasketKind::None) => {
            let _ = writeln!(
                md,
                "This cast has neither a seam-plane flange \
                 (`FlangeKind::None`) nor a per-layer gasket \
                 (`GasketKind::None`). Cup halves must be hand-clamped \
                 over their contoured outer surface (wide tape, \
                 ratchet straps, or workshop user's preferred \
                 contoured-clamp method; see the assembly note above \
                 for the registration-pin-mediated alignment). Pour \
                 silicone directly through the pour gate; the seam \
                 relies on the cup-piece SDF halfspace intersect's \
                 bit-precise flat seam face (recon-4 (P) §F-2). \
                 Workshop user monitors for leaks at the seam during \
                 pour; flag any leak for the post-iter-3 gasket / \
                 flange enablement decision."
            );
        }
        (FlangeKind::None, GasketKind::Mold(_)) => {
            let _ = writeln!(
                md,
                "This cast carries per-layer gaskets \
                 (`GasketKind::Mold`) but no flange \
                 (`FlangeKind::None`). Pour and cure the gasket \
                 strips per the gasket-mold protocol, peel them out, \
                 and lay each gasket on the Negative cup half's seam \
                 face inside the body cavity perimeter. Close the \
                 Positive half over Negative + gasket, aligning via \
                 the symmetric dowel-hole pattern (or hand-alignment \
                 when `DowelHoleKind::None`). Without a flange to provide \
                 a flat C-clamp grip surface, the cup must be hand-\
                 clamped over its contoured outer surface (wide tape \
                 or ratchet straps at 4+ quadrants). Aim for the \
                 gasket's `predicted_compression_m` (~232 µm at the \
                 `GasketSpec.workshop_clamp_pressure_pa` 20 kPa \
                 default for Ecoflex 00-30); over-tightening extrudes \
                 the gasket and loses the seal. Document hand-clamp \
                 pressure variability for the post-iter-3 flange-\
                 enablement decision."
            );
        }
        (FlangeKind::Plate(flange_spec), GasketKind::None) => {
            let width_mm = flange_spec.flange_width_m * 1000.0;
            let thickness_mm = flange_spec.flange_thickness_m * 1000.0;
            if ribbon.bolt_pattern.spec().is_some() {
                // iter-1 path: flange + bolts, no gasket. The bolts
                // ARE the clamp; defer the protocol to the §B section
                // already rendered above. Emitting C-clamp prose here
                // would conflict with the bolt-pattern instructions.
                let _ = writeln!(
                    md,
                    "This cast carries a seam-plane flange \
                     (`FlangeKind::Plate`: {width_mm:.1} mm lateral × \
                     {thickness_mm:.1} mm per-half thickness) and the \
                     §B M5 through-bolt clamp pattern, but no \
                     per-layer gasket (`GasketKind::None`). The M5 \
                     through-bolts ARE the clamp mechanism — see \
                     `### M5 through-bolt clamp pattern (§B)` above \
                     for the supplies list + crosswise hand-tighten \
                     protocol. Do NOT apply external C-clamps in \
                     addition to the bolts; the bolt-induced flange \
                     contact pressure (~1 MPa) seals PLA-on-PLA at \
                     the seam with mold release standing in for a \
                     compressible gasket. Workshop user monitors for \
                     leaks at the seam during pour; if a leak \
                     develops, the iter-2 path is to re-enable the \
                     per-layer gasket (`[gasket].enabled = true` in \
                     cast.toml)."
                );
            } else {
                let _ = writeln!(
                    md,
                    "This cast carries a seam-plane flange \
                     (`FlangeKind::Plate`: {width_mm:.1} mm lateral × \
                     {thickness_mm:.1} mm per-half thickness) but no \
                     per-layer gasket (`GasketKind::None`) and no §B \
                     bolt pattern. Use the flange as a flat C-clamp \
                     grip surface: after mating the cup halves via \
                     the symmetric dowel-hole pattern, apply C-clamps \
                     to the flange at 4 positions (one per 90° \
                     quadrant around the seam plane perimeter). \
                     Tighten each clamp to hand-tight only — without \
                     a gasket there is no compressible silicone strip \
                     to absorb over-tightening, and PLA-on-PLA flange \
                     contact at high clamp force can stress-crack \
                     the flange. Pour silicone through the pour gate; \
                     the seam relies on the cup-piece SDF halfspace \
                     intersect's bit-precise flat seam face (recon-4 \
                     (P) §F-2). Workshop user monitors for leaks; \
                     flag any leak for the post-iter-3 gasket \
                     enablement decision."
                );
            }
        }
        (FlangeKind::Plate(flange_spec), GasketKind::Mold(gasket_spec)) => {
            // Workshop iter-3 default path — full clamp-and-pour
            // protocol per recon §F-7.
            let width_mm = flange_spec.flange_width_m * 1000.0;
            let thickness_mm = flange_spec.flange_thickness_m * 1000.0;
            let inner_offset_mm = flange_spec.flange_inner_offset_m * 1000.0;
            let gasket_width_mm = gasket_spec.cross_section_width_m * 1000.0;
            let gasket_thickness_mm = gasket_spec.cross_section_thickness_m * 1000.0;
            let clamp_pressure_kpa = gasket_spec.workshop_clamp_pressure_pa / 1000.0;
            let predicted_compression_um = gasket_spec.predicted_compression_m() * 1_000_000.0;
            let gasket_material_label = gasket_spec.material.shore_label();
            let _ = writeln!(
                md,
                "This cast carries both a seam-plane flange \
                 (`FlangeKind::Plate`: {width_mm:.1} mm lateral × \
                 {thickness_mm:.1} mm per-half thickness × \
                 {inner_offset_mm:.1} mm inner offset from body \
                 cavity perimeter) and per-layer gaskets \
                 (`GasketKind::Mold`: {gasket_width_mm:.1} × \
                 {gasket_thickness_mm:.1} mm {gasket_material_label} \
                 cross-section). The flange provides the flat C-clamp \
                 grip surface; the gasket provides the silicone seal \
                 against FDM-tolerance leak per the seam-gasket-mold \
                 arc (recon §G-1). The flange's `inner_offset_m` \
                 ({inner_offset_mm:.1} mm) keeps the flange material \
                 laterally disjoint from the gasket channel per recon \
                 §F-4 — gasket compresses, flange clamps, no lateral \
                 overlap between the two."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "**Per-layer workshop protocol** (repeat for each \
                 layer's pour):"
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "1. **Pour gasket silicone.** Mix and pour the \
                 {gasket_material_label} gasket material into the \
                 per-layer gasket-mold tray \
                 (`gasket_mold_layer_{{N}}.stl`). Cure per the gasket \
                 material's Smooth-On TDS at 23 °C."
            );
            let _ = writeln!(
                md,
                "2. **Peel the cured gasket.** Once cured, peel the \
                 gasket strip out of the mold tray. The strip traces \
                 the body cavity perimeter; handle it as a continuous \
                 loop (don't stretch or twist)."
            );
            let _ = writeln!(
                md,
                "3. **Position the gasket on the Negative cup half.** \
                 Open the cup halves, lay the Negative cup half \
                 (`mold_layer_{{N}}_piece_0.stl`) seam-face-UP on the \
                 workshop bench. Place the gasket strip on the seam \
                 face **along the body cavity perimeter, in the \
                 annular clearance gap between the body cavity edge \
                 (`body_dist = 0`) and the flange's inner edge** — \
                 the flange's {inner_offset_mm:.1} mm \
                 `inner_offset_m` is the width of that gap and keeps \
                 the flange material laterally clear of the gasket \
                 per recon §F-4 gasket-disjoint invariant. The \
                 gasket strip itself is centered on the body \
                 perimeter (half inside body_dist < 0, half outside)."
            );
            let _ = writeln!(
                md,
                "4. **Close the Positive cup half over Negative + \
                 gasket.** Bring the Positive piece \
                 (`mold_layer_{{N}}_piece_1.stl`) down onto the \
                 Negative + gasket assembly, aligning via the \
                 symmetric dowel holes (if enabled — see \
                 `## v2 Mold Assembly` above for the alignment \
                 method when dowel holes are disabled). At this stage \
                 the gasket is only lightly seated (cup halves resting \
                 on the registration features); the cup halves should \
                 seat flush at the seam (flange-to-flange contact \
                 OUTSIDE the gasket strip; gasket-sandwiched lightly \
                 INSIDE). Full gasket compression is achieved in \
                 Step 5 once the C-clamps apply the design pressure."
            );
            let _ = writeln!(
                md,
                "5. **Apply C-clamps to the flange at 4 quadrant \
                 positions.** Place one C-clamp at each 90° quadrant \
                 around the seam-plane perimeter. Tighten each clamp \
                 to **hand-tight + 1/8 turn** — enough to reach the \
                 gasket's design {clamp_pressure_kpa:.0} kPa target \
                 pressure (predicts ~{predicted_compression_um:.0} \
                 µm compression per the \
                 `GasketSpec::predicted_compression_m` Hookean \
                 estimate). Workshop user MUST avoid over-tightening \
                 (gasket extrusion → loss of seal)."
            );
            let _ = writeln!(
                md,
                "6. **Pour main layer silicone through the pour \
                 gate.** With the cup clamped and gasket compressed, \
                 pour the layer silicone through the pour-gate \
                 funnel (see `## Pour Gate + Vent` below). The vent \
                 leg confirms full cavity fill; pour until silicone \
                 wets the vent opening."
            );
            let _ = writeln!(
                md,
                "7. **Cure per layer material TDS.** Leave the \
                 assembly clamped for the full cure window (per \
                 layer material's TDS at 23 °C). Do NOT release \
                 clamps until cure is complete — gasket compression \
                 must hold throughout cure to maintain the seal."
            );
            let _ = writeln!(
                md,
                "8. **Release clamps + open cup halves.** After cure, \
                 release the 4 C-clamps. Separate the cup halves; \
                 any dowels in the symmetric holes slide out \
                 (gravity-held friction-fit — no latch action). Peel \
                 the gasket strip out of the seam; trim at the body \
                 cavity perimeter with a scalpel if the gasket has \
                 chemically bonded to the cured silicone shell at \
                 the lateral interface (platinum-cure silicones can \
                 develop a thin lateral bond where the cured gasket \
                 contacted the fresh main pour at body_dist < 0; the \
                 thin gasket strip tears cleanly under light scalpel \
                 guidance). The gasket does NOT bond to the PLA cup \
                 halves (silicone-non-stick). Demold the cured \
                 silicone tube per `## Post-Cure Assembly + \
                 Disassembly` below."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "**Clamp count + tightness** (recon §F-10): the \
                 4-clamp / hand-tight + 1/8 turn recipe is the iter-3 \
                 starting point. Workshop S6 calibration may dial up \
                 to 6-8 clamps for longer perimeters, or dial down \
                 clamp torque if gasket extrusion is observed. \
                 Document deltas for the S7 post-iter-3 calibration \
                 sweep."
            );
        }
        (FlangeKind::Demand(demand_spec), GasketKind::None) => {
            // The demand-flange print target (recon §4): a scalloped flange —
            // a continuous seal-ring land hugging the cavity + a boss at each
            // fastener — generated to fit the placed bolts/dowels. Bolts ARE the
            // clamp (defer the protocol to the §B section above), exactly like the
            // (Plate, None) + bolts path.
            let land_width_mm = demand_spec.land_width_m * 1000.0;
            let land_inner_mm = demand_spec.land_inner_offset_m * 1000.0;
            let thickness_mm = demand_spec.flange_thickness_m * 1000.0;
            if ribbon.bolt_pattern.spec().is_some() {
                let _ = writeln!(
                    md,
                    "This cast carries the demand-driven (scalloped) flange \
                     (`FlangeKind::Demand`: a continuous {land_width_mm:.1} mm-wide \
                     seal-ring land starting {land_inner_mm:.1} mm out from the \
                     cavity, {thickness_mm:.1} mm per-half thick, with a boss at \
                     each fastener) and the §B M5 through-bolt clamp pattern, no \
                     per-layer gasket (`GasketKind::None`). The M5 through-bolts ARE \
                     the clamp — see `### M5 through-bolt clamp pattern (§B)` above \
                     for supplies + the crosswise hand-tighten protocol. The \
                     **continuous seal-ring land is the PLA-on-PLA seal**; the \
                     bolts sit on the bosses just outboard of it and clamp the land \
                     closed. Do NOT add external C-clamps. Material between bosses \
                     is scalloped away (bays) outboard of the land — that is \
                     intended (mass + print-time saving); the land itself is \
                     unbroken all the way around. Watch the land for leaks BETWEEN \
                     bolts during pour (the mid-bay clamp question, recon §4.3); if \
                     a bay weeps, the iter-2 lever is to re-enable the per-layer \
                     gasket (`[gasket] enabled = true`, with the seal land widened \
                     to clear it) for a compressible seal. (A tighter bolt pitch \
                     would also help, but it is a code-level constant, not yet a \
                     `cast.toml` knob.)"
                );
            } else {
                let _ = writeln!(
                    md,
                    "This cast carries the demand-driven (scalloped) flange \
                     (`FlangeKind::Demand`: continuous {land_width_mm:.1} mm seal \
                     land + per-fastener bosses) but no §B bolt pattern and no \
                     gasket. The demand flange is designed to be clamped BY the \
                     bolts at its bosses; without a bolt pattern there is no \
                     continuous flat C-clamp surface (the flange is scalloped \
                     between bosses), so enable `[bolt_pattern]` for this flange \
                     kind. As a stopgap, C-clamp directly on the bosses (one per \
                     boss, hand-tight) and monitor the seal-ring land for leaks."
                );
            }
        }
        (FlangeKind::Demand(demand_spec), GasketKind::Mold(_)) => {
            // Unusual: the demand flange is designed gasket-None (the land is the
            // seal). Supported for completeness — the gasket sits on the
            // continuous land and the bosses host the clamp.
            let land_width_mm = demand_spec.land_width_m * 1000.0;
            let _ = writeln!(
                md,
                "This cast carries the demand-driven (scalloped) flange \
                 (`FlangeKind::Demand`: continuous {land_width_mm:.1} mm seal land \
                 + per-fastener bosses) AND per-layer gaskets (`GasketKind::Mold`). \
                 The demand flange is normally run gasket-None (the continuous land \
                 IS the PLA-on-PLA seal); with a gasket also present, lay the gasket \
                 strip on the continuous seal land along the body-cavity perimeter, \
                 close the halves aligning on the dowels, and clamp via the §B bolts \
                 at the bosses (or C-clamp the bosses if no bolt pattern). Aim for \
                 the gasket's design compression; do not over-tighten. Reconsider \
                 whether the gasket is needed once the bare-land seal is proven at \
                 the physical gate."
            );
        }
    }
    md.push('\n');
}

/// Apex-axial pour prose (organic-parts §4.3): a single straight bore
/// at the dome apex on the seam, a straight-spout funnel, and
/// hand-drilled carbide vents. Replaces the V-shape pour/vent prose
/// for [`PourGateLayout::ApexAxial`].
fn write_apex_axial_pour_note(md: &mut String, spec: &crate::pour::PourGateSpec) {
    let gate_dia_mm = spec.gate_radius_m * 2.0 * 1000.0;
    let gate_length_mm = spec.gate_half_length_m * 2.0 * 1000.0;
    let _ = writeln!(
        md,
        "This cast uses the **apex pour** layout: a single straight \
         **{gate_dia_mm:.1} mm Ø bore at the dome apex** — the highest \
         point of the cavity when the mold is oriented +Z up — lying ON \
         the seam so it splits evenly between the two cup halves \
         ({gate_length_mm:.1} mm total channel). Pouring at the highest \
         point makes complete fill self-evident: the cavity is full the \
         instant silicone reaches the bore, because no point sits above \
         it, and trapped air migrates up to that same point."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Air vents are NOT modeled — drill them.** After printing, \
         drill tiny (~0.3-1.0 mm) vent holes with a fine bit at the \
         dome apex beside the pour bore and at any other local high \
         spots a test pour reveals air stranding (e.g. over the plug \
         grip rings or suction bulb). Air's very low viscosity escapes \
         a sub-millimetre hole that the honey-thick silicone will not \
         weep through, so the vents stay clean and the residue is a \
         negligible thread. Start with one apex vent; add more only \
         where a pour shows a trapped bubble."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "Because the pour bore is on the seam, separating the two cup \
         halves at demold bisects it lengthwise into open half-troughs \
         — the cured sprue lifts straight out (no pulling through a \
         blind hole); trim it flush off the cast. The seam-placement \
         solver brackets this bore by construction — it excludes the \
         pour as a swept channel, so a bolt lands just outside the \
         clearance on each side and the split flange stays clamped at \
         the apex."
    );
    md.push('\n');
    let nipple_clearance_mm = crate::funnel::NIPPLE_DIAMETRAL_CLEARANCE_M * 1000.0;
    let nipple_outer_dia_mm = gate_dia_mm - nipple_clearance_mm;
    let _ = writeln!(
        md,
        "**Pour funnel** (one-time print: `funnel.stl`). A **straight-\
         spout** funnel (vertical nipple, no bend) drops into the apex \
         bore with its bowl mouth facing straight up — the bore points \
         straight up when the mold is +Z up, so no bent spout is \
         needed. Nipple Ø {nipple_outer_dia_mm:.2} mm = the \
         {gate_dia_mm:.1} mm cup bore minus {nipple_clearance_mm:.2} mm \
         asymmetric diametral clearance (the cup hole stays nominal; \
         the nipple bears the slack). Ladle silicone slowly into the \
         vertical bowl. Apply mold release to the nipple before each \
         pour so cured silicone doesn't lock the funnel onto the cup. \
         Print once for the whole multi-layer device — reused across \
         every layer's pour."
    );
    md.push('\n');
}

fn write_v2_pour_gate_note(md: &mut String, ribbon: &Ribbon) {
    let _ = writeln!(md, "## Pour Gate + Vent");
    md.push('\n');
    match &ribbon.pour_gate {
        PourGateKind::None => {
            let _ = writeln!(
                md,
                "This cast has no integrated pour-gate or air-vent \
                 channels (`PourGateKind::None`). Pour silicone through \
                 the ribbon seam where the two pieces meet, and drill \
                 air-relief holes through the cured cup wall as needed \
                 if bubbles form during cure."
            );
        }
        PourGateKind::Default(spec) if spec.layout == PourGateLayout::ApexAxial => {
            write_apex_axial_pour_note(md, spec);
        }
        PourGateKind::Default(spec) => {
            let gate_dia_mm = spec.gate_radius_m * 2.0 * 1000.0;
            let vent_dia_mm = spec.vent_radius_m * 2.0 * 1000.0;
            let gate_length_mm = spec.gate_half_length_m * 2.0 * 1000.0;
            let vent_length_mm = spec.vent_half_length_m * 2.0 * 1000.0;
            let _ = writeln!(
                md,
                "Integrated pour-gate + air-vent channels form a **V at \
                 the dome end** of the centerline (opposite the cap \
                 plane). The V apex sits on the body's closed end with \
                 both legs splaying outward at ±30° from the body axis \
                 in the (outward + binormal) plane. Workshop orients \
                 the assembled mold **+Z up** during pour + cure; both \
                 holes appear at the top:\n\n\
                 - **{gate_dia_mm:.1} mm Ø pour gate** on the +binormal \
                 side of the seam (Positive piece, file `_piece_1`), \
                 {gate_length_mm:.1} mm total channel length.\n\
                 - **{vent_dia_mm:.1} mm Ø vent** on the -binormal \
                 side of the seam (Negative piece, file `_piece_0`), \
                 {vent_length_mm:.1} mm total channel length.\n\n\
                 Each leg lives entirely on one piece (no seam \
                 straddling), so each piece carves the leg on its own \
                 side and leaves the other untouched."
            );
            md.push('\n');
            if !spec.include_vent {
                let _ = writeln!(
                    md,
                    "**Note**: this cast has the vent leg disabled \
                     (`include_vent = false`). For short straight molds \
                     air escapes back through the pour leg as silicone \
                     fills bottom-up. For any cast where air trapping \
                     is suspected, enable the vent."
                );
                md.push('\n');
            }
            let _ = writeln!(
                md,
                "Pour silicone slowly into the larger {gate_dia_mm:.1} mm Ø \
                 pour leg (+binormal hole, Positive piece). Trapped air \
                 escapes through the smaller {vent_dia_mm:.1} mm Ø vent \
                 leg (-binormal hole, Negative piece) as the cavity fills \
                 bottom-up. Workshop user identifies pour vs vent by \
                 binormal side AND by hole diameter."
            );
            md.push('\n');
            // NIPPLE_DIAMETRAL_CLEARANCE_M is funnel-private; recompute
            // the asymmetric-`/2` cup-vs-nipple Ø delta from the spec so
            // workshop user sees the actual diametral gap.
            let nipple_clearance_mm = crate::funnel::NIPPLE_DIAMETRAL_CLEARANCE_M * 1000.0;
            let nipple_outer_dia_mm = gate_dia_mm - nipple_clearance_mm;
            let _ = writeln!(
                md,
                "**Pour funnel** (one-time print: `funnel.stl`). Honey-\
                 thick workshop silicones (Dragon Skin 10A / 20A / 30A \
                 at ~20-23k cps) splash through a bare \
                 {gate_dia_mm:.1} mm Ø pour leg; a printable funnel \
                 STL ships alongside the mold pieces with a \
                 {nipple_outer_dia_mm:.2} mm Ø self-aligning nipple \
                 that drops into the cup pour-gate hole \
                 ({nipple_clearance_mm:.2} mm asymmetric diametral \
                 clearance — the cup-side hole stays at the nominal \
                 {gate_dia_mm:.1} mm Ø; the funnel nipple bears all the \
                 slack), a 30°-bent spout matching the pour-gate's \
                 splay so the bowl mouth faces straight up when the \
                 mold is oriented +Z up for the pour, and a smoothly-\
                 tapered bowl widening to a workshop-friendly mouth \
                 for ladle-pouring. The bent spout pattern is the \
                 same as a real-world oil/lab funnel; insert the \
                 nipple into the pour-gate hole, rotate the funnel \
                 around the bowl axis until the nipple aligns with \
                 the angled pour leg, then ladle silicone into the \
                 vertical bowl mouth. Print `funnel.stl` once for the \
                 whole multi-layer device — reused across every \
                 layer's pour. The tilted nipple needs **slicer \
                 auto-supports** during print (or rotate the print \
                 so the nipple lies along the build plate). Apply \
                 mold release to the nipple before each pour so \
                 cured silicone doesn't lock the funnel onto the cup."
            );
        }
    }
    md.push('\n');
}

// Per-layer Step 6 branches on (gasket, bolt_pattern) and each
// per-layer block emits 8 numbered steps with embedded mix-ratio +
// cure prose; the function legitimately runs past clippy's default
// 100 lines once those branches landed. Splitting per-step would
// shuffle the same writeln!s into helpers without reducing complexity.
#[allow(clippy::too_many_lines)]
fn write_per_layer_sections_v2(
    md: &mut String,
    spec: &CastSpec,
    pour_volumes: &[PourVolume],
    ribbon: &Ribbon,
) {
    let _ = writeln!(md, "## Per-Layer Procedure");
    md.push('\n');
    for (layer, pour) in spec.layers.iter().zip(pour_volumes) {
        let position = layer_position_label(pour.layer_index, spec.layers.len());
        let _ = writeln!(
            md,
            "### Layer {} — {} ({})",
            pour.layer_index, layer.material.display_name, position
        );
        md.push('\n');
        let mass_g = pour.pour_mass_kg * KG_TO_G;
        let half_g = mass_g / 2.0;
        let protocol = layer.material.anchor_key.and_then(lookup_cure);

        let _ = writeln!(
            md,
            "1. Print STLs `mold_layer_{0}_piece_0.stl` + \
             `mold_layer_{0}_piece_1.stl` + \
             `plug_layer_{0}.stl` (this layer's plug, sized to the \
             previous layer's outer surface or to the innermost \
             cavity for layer 0).",
            pour.layer_index,
        );
        let _ = writeln!(md, "2. Apply mold release to all printed surfaces.");
        let _ = writeln!(
            md,
            "3. Assemble the two pieces along the curve-following seam \
             per the \"v2 Mold Assembly\" section above."
        );
        if let Some(protocol) = protocol {
            let _ = writeln!(
                md,
                "4. Mix {half_g:.2} g Part A + {half_g:.2} g Part B {} ({} mix ratio). \
                 Total {mass_g:.2} g.",
                layer.material.display_name, protocol.mix_ratio_a_to_b,
            );
        } else {
            let _ = writeln!(
                md,
                "4. Mix Part A + Part B {} per the Smooth-On TDS \
                 (total pour mass: {mass_g:.2} g, split per the data-sheet mix ratio).",
                layer.material.display_name,
            );
        }
        let _ = writeln!(md, "5. Vacuum-degas the mix for 2-3 minutes at ≥27 inHg.");
        let pour_sentence = match &ribbon.pour_gate {
            PourGateKind::Default(s) if s.layout == PourGateLayout::ApexAxial => {
                "Orient the assembled mold **+Z up** (dome apex on top). Pour \
                 silicone slowly through the straight funnel into the apex bore \
                 — the highest point of the cavity — so the shell fills \
                 bottom-up; trapped air escapes the hand-drilled vent(s) at the \
                 apex and any high spots. The cast is full the instant silicone \
                 reaches the bore (no point sits above it)."
            }
            PourGateKind::Default(_) => {
                "Orient the assembled mold with **+Z up** so the V's pour + vent \
                 legs are on top. Pour silicone into the pour leg of the V at \
                 the dome end (Positive piece, +binormal side) at a slow steady \
                 rate to avoid splashing through the vent; trapped air rises \
                 into the vent leg (Negative piece, -binormal side) as the \
                 cavity fills."
            }
            PourGateKind::None => {
                "Orient the assembled mold seam roughly vertical. Pour \
                 silicone into the assembled mold cavity slowly; drill \
                 air-relief holes through the cured cup wall as needed."
            }
        };
        let closing_protocol = match (&ribbon.gasket, ribbon.bolt_pattern.spec()) {
            (GasketKind::Mold(_), _) => {
                "Place the cured gasket strip on the Negative half's \
                 seam face per `## Cup-Half Clamping with Gasket \
                 Installation` above BEFORE closing the second cup \
                 half, then close the second half and apply the \
                 clamping protocol from that section."
            }
            (GasketKind::None, Some(_)) => {
                "Close the second cup half over the plug, registering \
                 the §M dowels to seat the two halves flush. Then \
                 install the §B M5 through-bolts per `### M5 \
                 through-bolt clamp pattern (§B)` above — insert each \
                 bolt + washers + nut and hand-tighten crosswise for \
                 even flange clamp pressure. PLA-on-PLA seam contact \
                 + mold release stands in for a gasket; the bolt \
                 clamp force is the seal."
            }
            (GasketKind::None, None) => {
                "Close the second cup half over the plug directly \
                 (seam closes flush = press-stop tactile feedback). \
                 Apply the clamping protocol from the section above."
            }
        };
        let _ = writeln!(
            md,
            "6. Apply mold release to `plug_layer_{0}.stl` (Smooth-On \
             Ease Release 200 standard) and seat the plug into one \
             open cup half so its truncated-pyramid floor lock drops \
             into the cup-piece floor socket. {closing_protocol} \
             {pour_sentence}",
            pour.layer_index,
        );
        if let Some(protocol) = protocol {
            let _ = writeln!(
                md,
                "7. Cure for ≥{} hr at 73 °F (pot life: {} min).",
                protocol.cure_time_hours, protocol.pot_life_minutes,
            );
        } else {
            let _ = writeln!(
                md,
                "7. Cure per the Smooth-On TDS at 73 °F (pot life per TDS)."
            );
        }
        let _ = writeln!(
            md,
            "8. Demold: open the two mold halves along the ribbon \
             seam (remove `piece_0` first, then `piece_1` for clean \
             centerline-axis slide release on curved centerlines). \
             Pull the plug axially out of the cured silicone shell; \
             the truncated-pyramid floor lock slides out of its \
             cap-plane socket-cavity in the silicone (the pyramid's \
             taper releases without interference under axial pull). \
             The cured layer detaches as a standalone silicone tube \
             ready to nest with the other layers post-cure."
        );
        md.push('\n');
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::{TDS_LOOKUP_PLACEHOLDER, cure_protocol_cells, layer_position_label};

    #[test]
    fn cure_protocol_cells_resolves_known_anchor() {
        let (mix, pot_life, cure_time) = cure_protocol_cells(Some("ECOFLEX_00_30"));
        assert_eq!(mix, "1A:1B");
        assert_eq!(pot_life, "45 min");
        assert_eq!(cure_time, "4 hr");
    }

    #[test]
    fn cure_protocol_cells_emits_placeholder_for_none_anchor() {
        let (mix, pot_life, cure_time) = cure_protocol_cells(None);
        assert_eq!(mix, TDS_LOOKUP_PLACEHOLDER);
        assert_eq!(pot_life, TDS_LOOKUP_PLACEHOLDER);
        assert_eq!(cure_time, TDS_LOOKUP_PLACEHOLDER);
    }

    #[test]
    fn cure_protocol_cells_emits_placeholder_for_unknown_anchor() {
        let (mix, pot_life, cure_time) = cure_protocol_cells(Some("MOLD_STAR_30"));
        assert_eq!(mix, TDS_LOOKUP_PLACEHOLDER);
        assert_eq!(pot_life, TDS_LOOKUP_PLACEHOLDER);
        assert_eq!(cure_time, TDS_LOOKUP_PLACEHOLDER);
    }

    #[test]
    fn layer_position_label_three_layer_device() {
        // 3 layers: 0 = innermost, 1 = middle, 2 = outermost.
        assert_eq!(layer_position_label(0, 3), "innermost");
        assert_eq!(layer_position_label(1, 3), "middle");
        assert_eq!(layer_position_label(2, 3), "outermost");
    }

    #[test]
    fn layer_position_label_single_layer_is_outermost_and_innermost() {
        // Edge case: a single-layer device's only layer is both
        // innermost (`index == 0`) AND outermost (`index + 1 ==
        // count`). The check ordering picks innermost — fine,
        // because both are accurate; "innermost" is more
        // load-bearing for the procedure (it's the one that uses
        // the printed plug).
        assert_eq!(layer_position_label(0, 1), "innermost");
    }

    #[test]
    fn layer_position_label_two_layer_device() {
        // 2 layers: no middle position.
        assert_eq!(layer_position_label(0, 2), "innermost");
        assert_eq!(layer_position_label(1, 2), "outermost");
    }
}
