//! F3 procedure-spec markdown generator.
//!
//! [`generate_procedure_markdown`] renders a workshop-ready Markdown
//! procedure for a [`CastSpec`]: per-layer pour masses (from F2),
//! mix ratio + pot life + cure time (from [`crate::cure::lookup`]),
//! generic Smooth-On guidance, and a mass-budget summary. The
//! generated markdown is the starting-point reference the workshop
//! user iterates against bench reality after iter-1.
//!
//! The function is pure (no IO) so tests can assert on its output
//! bit-exactly. [`CastSpec::write_procedure`] is the convenience
//! wrapper that writes the rendered string to disk.

// `writeln!`/`write!` on a `String` go through the `core::fmt::Write`
// trait, which returns `Result<(), fmt::Error>` for generality. The
// `String` impl never fails, so the workspace's
// `let_underscore_must_use` deny is structurally redundant on every
// `let _ = writeln!(md, …);` site in this generator. The
// alternatives (an `.expect("…")` chain, a `push_str(&format!(…))`
// rewrite at every site) trade one form of noise for another;
// scoping the allow to this single template module keeps the
// workspace-wide deny intact for code where Result-discarding
// genuinely could mask failures.
#![allow(clippy::let_underscore_must_use)]

use std::fmt::Write as _;

use crate::cure::lookup as lookup_cure;
use crate::plug::PlugPinKind;
use crate::pour::PourGateKind;
use crate::pour_volume::PourVolume;
use crate::registration::RegistrationKind;
use crate::ribbon::Ribbon;
use crate::spec::CastSpec;

/// Conversion factor — kilograms to grams. Pour masses surface in
/// the markdown table in grams because workshop scales read grams.
const KG_TO_G: f64 = 1000.0;

/// Placeholder text emitted in the materials table when a layer's
/// [`crate::MoldingMaterial::anchor_key`] is `None` or refers to a
/// material outside [`crate::cure::lookup`]'s anchor set
/// (interpolated, measured, or non-Smooth-On).
const TDS_LOOKUP_PLACEHOLDER: &str = "consult Smooth-On TDS";

/// Render the Markdown procedure for `spec` given the per-layer
/// `pour_volumes` (computed by [`CastSpec::compute_pour_volumes`]).
///
/// `pour_volumes` is taken by parameter (not recomputed) so callers
/// can render against a single pour-volume capture even when their
/// flow already has the values in hand (e.g., from a
/// [`crate::MoldExportReport`]).
///
/// The function is pure: no IO, no time-dependent fields. Tests can
/// pin the output bit-exactly.
///
/// # Panics
///
/// Length of `pour_volumes` must equal `spec.layers.len()`. The
/// caller is expected to pass a freshly-computed
/// `compute_pour_volumes` result; mismatched lengths are a programming
/// error and panic via the `length` assertion.
#[must_use]
pub fn generate_procedure_markdown(spec: &CastSpec, pour_volumes: &[PourVolume]) -> String {
    assert_eq!(
        pour_volumes.len(),
        spec.layers.len(),
        "pour_volumes must be parallel to spec.layers"
    );

    let mut md = String::new();
    write_header(&mut md, spec);
    write_materials_table(&mut md, spec, pour_volumes);
    write_generic_guidance(&mut md);
    write_per_layer_sections(&mut md, spec, pour_volumes);
    write_mass_budget_summary(&mut md, spec, pour_volumes);
    md
}

fn write_header(md: &mut String, spec: &CastSpec) {
    let _ = writeln!(md, "# Cast Procedure");
    md.push('\n');
    let _ = writeln!(
        md,
        "Generated by `cf-cast` for a {}-layer cast (innermost-first).",
        spec.layers.len()
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "Workshop procedure starting-point. Mix ratios, pot life, and \
         cure times are per Smooth-On Technical Data Sheets at 73 °F \
         (23 °C). Treat the steps below as a baseline — adjust against \
         bench reality after iter-1."
    );
    md.push('\n');
}

fn write_materials_table(md: &mut String, spec: &CastSpec, pour_volumes: &[PourVolume]) {
    let _ = writeln!(md, "## Materials Summary");
    md.push('\n');
    let _ = writeln!(
        md,
        "| Layer | Material | Pour Mass | Mix Ratio | Pot Life | Cure Time |"
    );
    let _ = writeln!(
        md,
        "|------:|----------|----------:|-----------|---------:|----------:|"
    );
    for (layer, pour) in spec.layers.iter().zip(pour_volumes) {
        let mass_g = pour.pour_mass_kg * KG_TO_G;
        let (mix, pot_life, cure_time) = cure_protocol_cells(layer.material.anchor_key);
        let _ = writeln!(
            md,
            "| {} | {} | {:.2} g | {} | {} | {} |",
            pour.layer_index, layer.material.display_name, mass_g, mix, pot_life, cure_time,
        );
    }
    md.push('\n');
}

fn write_generic_guidance(md: &mut String) {
    let _ = writeln!(md, "## Generic Smooth-On Guidance");
    md.push('\n');
    let _ = writeln!(
        md,
        "- Weigh Part A + Part B on a gram scale. 1A:1B is by weight or \
         volume per TDS — choose the more accurate path for the equipment \
         on hand (weight typically beats volume for low-viscosity \
         silicones)."
    );
    let _ = writeln!(
        md,
        "- Vacuum-degas the mixed silicone at ≥27 inHg for 2-3 minutes \
         before pouring. Bubbles trapped at cavity surfaces or layer \
         interfaces are the #1 first-cast failure mode."
    );
    let _ = writeln!(
        md,
        "- Apply mold release to printed surfaces before each pour. \
         Layer-to-layer adhesion between cured silicones is generally \
         strong without release, but printed-mold-to-silicone separation \
         needs it."
    );
    let _ = writeln!(
        md,
        "- Pour into the deepest point of the cavity and let the silicone \
         self-level outward; pouring across surfaces traps air."
    );
    let _ = writeln!(
        md,
        "- Cure at room temperature (≈23 °C). Cooler slows cure; warmer \
         accelerates. Heat-cure schedules can shorten demold time per \
         TDS but introduce thermal-shrink effects not modeled here."
    );
    md.push('\n');
}

fn write_per_layer_sections(md: &mut String, spec: &CastSpec, pour_volumes: &[PourVolume]) {
    let _ = writeln!(md, "## Per-Layer Procedure");
    md.push('\n');
    for (layer, pour) in spec.layers.iter().zip(pour_volumes) {
        let position = layer_position_label(pour.layer_index, spec.layers.len());
        let _ = writeln!(
            md,
            "### Layer {} — {} ({})",
            pour.layer_index, layer.material.display_name, position
        );
        md.push('\n');
        let mass_g = pour.pour_mass_kg * KG_TO_G;
        let half_g = mass_g / 2.0;
        // Looked up once per layer — both step 3 (mix) and step 6
        // (cure) branch on whether this material has an anchored
        // CureProtocol vs the TDS-fallback prose. Looking it up
        // directly here (rather than via `cure_protocol_cells`)
        // avoids substituting placeholder strings into duration /
        // ratio positions where they read as broken English
        // ("Cure for ≥consult Smooth-On TDS …").
        let protocol = layer.material.anchor_key.and_then(lookup_cure);
        let _ = writeln!(
            md,
            "1. Print STL `mold_layer_{}.stl`{}.",
            pour.layer_index,
            if pour.layer_index == 0 {
                " and the shared `plug.stl`"
            } else {
                ""
            }
        );
        let _ = writeln!(md, "2. Apply mold release to all printed surfaces.");
        if let Some(protocol) = protocol {
            let _ = writeln!(
                md,
                "3. Mix {half_g:.2} g Part A + {half_g:.2} g Part B {} ({} mix ratio). \
                 Total {mass_g:.2} g.",
                layer.material.display_name, protocol.mix_ratio_a_to_b,
            );
        } else {
            let _ = writeln!(
                md,
                "3. Mix Part A + Part B {} per the Smooth-On TDS \
                 (total pour mass: {mass_g:.2} g, split per the data-sheet mix ratio).",
                layer.material.display_name,
            );
        }
        let _ = writeln!(md, "4. Vacuum-degas the mix for 2-3 minutes at ≥27 inHg.");
        if pour.layer_index == 0 {
            let _ = writeln!(
                md,
                "5. Pour into the mold cup. Insert the plug from +z, \
                 displacing silicone to shape the inner cavity."
            );
        } else {
            let _ = writeln!(
                md,
                "5. Place the cured layer {} (from the previous pour) \
                 inside this mold cup as the plug. Pour around it.",
                pour.layer_index - 1,
            );
        }
        if let Some(protocol) = protocol {
            let _ = writeln!(
                md,
                "6. Cure for ≥{} hr at 73 °F (pot life: {} min).",
                protocol.cure_time_hours, protocol.pot_life_minutes,
            );
        } else {
            let _ = writeln!(
                md,
                "6. Cure per the Smooth-On TDS at 73 °F (pot life per TDS)."
            );
        }
        let _ = writeln!(
            md,
            "7. Demold from the mold cup{}.",
            if pour.layer_index == 0 {
                " and carefully extract the plug"
            } else {
                ""
            }
        );
        md.push('\n');
    }
}

fn write_mass_budget_summary(md: &mut String, spec: &CastSpec, pour_volumes: &[PourVolume]) {
    let _ = writeln!(md, "## Mass Budget");
    md.push('\n');
    let total_g: f64 = pour_volumes.iter().map(|p| p.pour_mass_kg * KG_TO_G).sum();
    let budget_g = spec.mass_budget_kg * KG_TO_G;
    let _ = writeln!(
        md,
        "- Total silicone mass across all layers: **{:.2} g** ({} layers).",
        total_g,
        spec.layers.len()
    );
    let _ = writeln!(
        md,
        "- Per-pour budget: **{:.2} g** ({:.4} kg). Every layer's pour mass \
         falls within budget per the F2 export gate.",
        budget_g, spec.mass_budget_kg,
    );
    let _ = writeln!(
        md,
        "- Same-material layers' aggregate may exceed user holdings even \
         when each per-pour mass fits — verify total holdings against \
         per-material sums in the summary table above."
    );
    md.push('\n');
}

/// Return `(mix_ratio, pot_life, cure_time)` rendered cells for a
/// layer. Materials without a Smooth-On anchor (or with an unknown
/// key) collapse all three cells to [`TDS_LOOKUP_PLACEHOLDER`].
fn cure_protocol_cells(anchor_key: Option<&'static str>) -> (String, String, String) {
    if let Some(key) = anchor_key {
        if let Some(protocol) = lookup_cure(key) {
            return (
                protocol.mix_ratio_a_to_b.to_string(),
                format!("{} min", protocol.pot_life_minutes),
                format!("{} hr", protocol.cure_time_hours),
            );
        }
    }
    (
        TDS_LOOKUP_PLACEHOLDER.to_string(),
        TDS_LOOKUP_PLACEHOLDER.to_string(),
        TDS_LOOKUP_PLACEHOLDER.to_string(),
    )
}

/// Label a layer's position for the per-layer procedure heading.
/// Innermost-first ordering means index 0 is "innermost"; the last
/// index is "outermost"; everything between is "middle".
const fn layer_position_label(layer_index: usize, layer_count: usize) -> &'static str {
    if layer_index == 0 {
        "innermost"
    } else if layer_index + 1 == layer_count {
        "outermost"
    } else {
        "middle"
    }
}

// ===== v2 — curve-following multi-piece procedure =================

/// Render the v2 curve-following multi-piece Markdown procedure for
/// `spec` + `ribbon` given the per-layer `pour_volumes`.
///
/// Parallel to [`generate_procedure_markdown`] but for v2's
/// 2-piece-per-layer geometry (per
/// `docs/CURVE_FOLLOWING_DESIGN.md` §"Output artifacts"). The
/// renderer references `mold_layer_{i}_piece_{0|1}.stl` filenames,
/// adds a "Cast Geometry" section that surfaces the centerline
/// arc length + max tangent rotation, replaces v1's
/// straight-pull demold prose with explicit piece-removal order
/// ("piece 0 first, then piece 1 — the part slides out along
/// the centerline"), and adds an iter-1 manual-clamping note
/// (registration features are Step 9; v2 iter-1 uses hand pressure
/// + rubber bands).
///
/// Materials table, generic Smooth-On guidance, and mass-budget
/// summary are shared verbatim with v1 (same pour-volume
/// computation drives the budget gate in both
/// [`CastSpec::export_molds`] and [`CastSpec::export_molds_v2`]).
///
/// The function is pure (no IO, no time-dependent fields) so tests
/// can pin output bit-exactly. [`CastSpec::write_procedure_v2`] is
/// the convenience FS wrapper.
///
/// # Panics
///
/// Length of `pour_volumes` must equal `spec.layers.len()`. The
/// caller is expected to pass a freshly-computed
/// `compute_pour_volumes` result; mismatched lengths are a programming
/// error and panic via the `length` assertion.
#[must_use]
pub fn generate_procedure_markdown_v2(
    spec: &CastSpec,
    pour_volumes: &[PourVolume],
    ribbon: &Ribbon,
) -> String {
    assert_eq!(
        pour_volumes.len(),
        spec.layers.len(),
        "pour_volumes must be parallel to spec.layers"
    );

    let mut md = String::new();
    write_header_v2(&mut md, spec);
    write_cast_geometry_v2(&mut md, ribbon);
    write_materials_table(&mut md, spec, pour_volumes);
    write_generic_guidance(&mut md);
    write_v2_assembly_note(&mut md, ribbon);
    write_v2_pour_gate_note(&mut md, ribbon);
    write_per_layer_sections_v2(&mut md, spec, pour_volumes, ribbon);
    write_v2_post_cure_assembly(&mut md, spec);
    write_mass_budget_summary(&mut md, spec, pour_volumes);
    md
}

fn write_v2_post_cure_assembly(md: &mut String, spec: &CastSpec) {
    let _ = writeln!(md, "## Post-Cure Assembly + Disassembly");
    md.push('\n');
    let _ = writeln!(
        md,
        "After all {} layers cure + demold, you have {} standalone \
         silicone tubes — one per layer — each with the next-inner \
         tube's outer geometry as its inner cavity (innermost = \
         layer 0; outermost = layer {}).",
        spec.layers.len(),
        spec.layers.len(),
        spec.layers.len().saturating_sub(1),
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Assembly**: nest the tubes innermost-first. Slide layer 0 \
         into the inner cavity of layer 1; the cured silicone is \
         flexible enough to flex over the 0.5-1 mm inter-layer \
         interference fit. Apply Smooth-On Silicone Slip (or any \
         silicone-safe lubricant) sparingly to ease insertion if \
         needed. Repeat with each successive outer layer until all \
         tubes are stacked into a single multi-layer device."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Disassembly** (for cleaning or single-layer replacement): \
         reverse the assembly order. Working from the outermost \
         layer inward, peel each tube off the next-inner one. \
         Flexibility allows individual layer extraction without \
         disturbing the others — replace one worn-out layer without \
         re-casting the whole stack."
    );
    md.push('\n');
}

fn write_header_v2(md: &mut String, spec: &CastSpec) {
    let _ = writeln!(
        md,
        "# Cast Procedure (v2.1 curve-following, detachable-shell)"
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "Generated by `cf-cast` for a {}-layer cast (innermost-first) \
         with v2.1 curve-following 2-piece molds + one printed plug \
         per layer. Each layer is cast independently against its own \
         plug, producing a detachable cured silicone tube that nests \
         with the other layers post-cure for assembly + disassembly.",
        spec.layers.len()
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "**Orientation convention**: orient the assembled mold with \
         **+Z up** during pour + cure. The pour gate + vent form a V \
         at the dome end of the centerline (opposite the cap plane); \
         both holes are visible at the TOP of the assembly. Pour leg \
         on the Positive piece (`_piece_1`, +binormal side of the \
         seam), vent leg on the Negative piece (`_piece_0`, -binormal \
         side)."
    );
    md.push('\n');
    let _ = writeln!(
        md,
        "Workshop procedure starting-point. Mix ratios, pot life, and \
         cure times are per Smooth-On Technical Data Sheets at 73 °F \
         (23 °C). Treat the steps below as a baseline — adjust against \
         bench reality after iter-1."
    );
    md.push('\n');
}

fn write_cast_geometry_v2(md: &mut String, ribbon: &Ribbon) {
    let _ = writeln!(md, "## Cast Geometry");
    md.push('\n');
    let arc_length_mm = ribbon.arc_length() * 1000.0;
    let max_rotation_deg = ribbon.max_tangent_rotation_rad().to_degrees();
    let _ = writeln!(
        md,
        "- Centerline arc length: **{arc_length_mm:.1} mm** \
         (informs demold travel — pieces slide along this distance)."
    );
    let _ = writeln!(
        md,
        "- Max tangent rotation along the centerline: **{max_rotation_deg:.1}°** \
         (v2 ships 2 pieces; above 120° the cast is refused as un-demoldable \
         per `CURVE_FOLLOWING_DESIGN.md` §\"Piece count selection\")."
    );
    let _ = writeln!(
        md,
        "- Piece count per layer: **2** (`piece_0` = ribbon-negative side, \
         `piece_1` = ribbon-positive side)."
    );
    md.push('\n');
}

fn write_v2_assembly_note(md: &mut String, ribbon: &Ribbon) {
    let _ = writeln!(md, "## v2 Mold Assembly");
    md.push('\n');
    match &ribbon.registration {
        RegistrationKind::None => {
            let _ = writeln!(
                md,
                "Each layer's mold is two ribbon-cut pieces \
                 (`_piece_0` + `_piece_1`) that meet along the \
                 curve-following seam. This cast has no integral \
                 registration features (`RegistrationKind::None`); \
                 align the pieces by hand and clamp with rubber bands \
                 or wide tape during pour + cure. Post-S4 of the \
                 mating-features arc, each piece's seam face is trimmed \
                 flat to the exact ribbon plane via post-MC mesh-CSG \
                 (see `cf-cast::piece::RIBBON_PIECE_OVERLAP_M` for the \
                 pre-trim SDF over-build extent), so the two halves \
                 seat flush at the seam without bias and hand alignment \
                 only needs to bring the cup outlines into registration."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "If silicone leaks through the seam during pour, add a \
                 small fillet of mold release or putty along the outside \
                 of the seam before the next layer. Document the leak \
                 position for the post-iter-1 registration-feature \
                 decision (pins vs dovetails vs magnets)."
            );
        }
        RegistrationKind::Pins(spec) => {
            let pin_count = spec.arc_fractions.len();
            let pin_dia_mm = spec.pin_radius_m * 2.0 * 1000.0;
            let pin_length_mm = spec.pin_half_length_m * 2.0 * 1000.0;
            let diametral_mm = spec.diametral_clearance_m * 1000.0;
            let socket_dia_mm = pin_dia_mm + diametral_mm;
            let _ = writeln!(
                md,
                "Each layer's mold is two ribbon-cut pieces \
                 (`_piece_0` + `_piece_1`) that meet along the \
                 curve-following seam. **{pin_count} cylindrical pins** \
                 ({pin_dia_mm:.1} mm Ø × {pin_length_mm:.1} mm long, \
                 printed integrally with `_piece_0` and matched by \
                 {socket_dia_mm:.2} mm Ø cylindrical holes in \
                 `_piece_1` — {diametral_mm:.2} mm diametral clearance \
                 for a positional sliding fit) lock the pieces in \
                 alignment along the seam — no manual clamping needed \
                 once the pins are seated."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "Insert each pin from `_piece_0` into the matching \
                 hole in `_piece_1` along the binormal direction (the \
                 hole axis is perpendicular to the seam at the pin \
                 position). Pins are gravity-held; no friction lock. \
                 Post-S4 of the mating-features arc, each piece's \
                 seam face is trimmed flat to the ribbon plane via \
                 mesh-CSG, so the pieces seat flush at the seam; the \
                 workshop-visible pin protrusion past the seam plane \
                 is `cf-cast::piece::RIBBON_PIECE_OVERLAP_M` (0.5 mm), \
                 and the sliding fit comes from the \
                 {diametral_mm:.2} mm diametral clearance above."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "If a pin breaks during demold or assembly, file the \
                 stub flush + drill out the hole if needed; a manual \
                 rubber-band clamp restores the cast for that layer. \
                 Document pin failures for the post-iter-1 \
                 registration-feature decision (revisit dia/length \
                 defaults in `PinSpec::iter1`)."
            );
        }
    }
    md.push('\n');
    write_v2_plug_anchor_note(md, ribbon);
}

fn write_v2_plug_anchor_note(md: &mut String, ribbon: &Ribbon) {
    let _ = writeln!(md, "### Plug Anchor");
    md.push('\n');
    match &ribbon.plug_pins {
        PlugPinKind::None => {
            let _ = writeln!(
                md,
                "This cast has no plug-anchor pin geometry \
                 (`PlugPinKind::None`). The plug is positioned in \
                 the assembled mold cup by hand and held there \
                 during pour + cure (workshop user braces the plug \
                 manually or jigs against the cavity dome). v2.1's \
                 `PlugPinKind::Axial` opt-in adds a printed pin to \
                 the pour end of each layer's plug + a matching \
                 socket in each mold piece; recommended for any \
                 cast where the plug's silicone-displacement weight \
                 + curve geometry makes hand-positioning fiddly."
            );
        }
        PlugPinKind::Axial(spec) => {
            let pin_dia_mm = spec.pin_radius_m * 2.0 * 1000.0;
            let pin_length_mm = spec.pin_length_m * 1000.0;
            // Post-S6 cup-side socket primitive inflates by
            // `shaft_diametral_clearance_m / 2` per radial side
            // (Ø grows by the full diametral clearance) and extends
            // axially past the pin by `shaft_axial_clearance_m / 2`
            // on each face (deep-end relief is the workshop-meaningful
            // half; see `PlugPinSpec::shaft_axial_clearance_m`).
            let socket_diametral_gap_mm = spec.shaft_diametral_clearance_m * 1000.0;
            let socket_axial_relief_mm = spec.shaft_axial_clearance_m * 1000.0;
            let dome_pin_status = if spec.include_dome_pin {
                "**Both** the pour end and the dome end have plug-\
                 anchor pins"
            } else {
                "Only the **pour end** has a plug-anchor pin (the \
                 dome end relies on the plug's hemispherical cap \
                 seating into the cavity's matching dome for \
                 centerline alignment — no through-hole on the \
                 dome side)"
            };
            let _ = writeln!(
                md,
                "Each per-layer plug carries an axial **{pin_dia_mm:.1} mm \
                 Ø × {pin_length_mm:.1} mm long pin** at the pour end \
                 (centerline endpoint with the pour gate; pin extends \
                 outward along the local tangent). The mold pieces \
                 carry a matching cylindrical socket \
                 {socket_diametral_gap_mm:.2} mm wider in diameter than \
                 the pin (positional sliding fit) with \
                 {socket_axial_relief_mm:.2} mm axial pocket-bottom \
                 relief so workshop FDM stair-step doesn't bottom the \
                 pin out before its shoulder seats. {dome_pin_status}."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "Workshop assembly: apply mold release (Smooth-On \
                 Ease Release 200 standard) to the pin before \
                 seating. Lower the plug into the assembled cup; \
                 the pin slides into the socket along the centerline \
                 tangent direction until the pin's shoulder rests \
                 against the cup wall. The plug is now positionally \
                 constrained against axial drift; combined with the \
                 cap-into-dome seating at the un-pinned end, the \
                 plug stays centered in 6 DoF during pour + cure."
            );
            md.push('\n');
            let _ = writeln!(
                md,
                "If the pin doesn't seat (too tight): ream the socket \
                 with a {pin_dia_mm:.1} mm drill bit to remove any \
                 FDM stair-step. If it wobbles (too loose): wrap the \
                 pin with PTFE tape until snug. Document fit \
                 tolerances for the post-iter-1 review of \
                 `PlugPinSpec::iter1` defaults."
            );
        }
    }
    md.push('\n');
}

fn write_v2_pour_gate_note(md: &mut String, ribbon: &Ribbon) {
    let _ = writeln!(md, "## Pour Gate + Vent");
    md.push('\n');
    match &ribbon.pour_gate {
        PourGateKind::None => {
            let _ = writeln!(
                md,
                "This cast has no integrated pour-gate or air-vent \
                 channels (`PourGateKind::None`). Pour silicone through \
                 the ribbon seam where the two pieces meet, and drill \
                 air-relief holes through the cured cup wall as needed \
                 if bubbles form during cure."
            );
        }
        PourGateKind::Default(spec) => {
            let gate_dia_mm = spec.gate_radius_m * 2.0 * 1000.0;
            let vent_dia_mm = spec.vent_radius_m * 2.0 * 1000.0;
            let gate_length_mm = spec.gate_half_length_m * 2.0 * 1000.0;
            let vent_length_mm = spec.vent_half_length_m * 2.0 * 1000.0;
            let _ = writeln!(
                md,
                "Integrated pour-gate + air-vent channels form a **V at \
                 the dome end** of the centerline (opposite the cap \
                 plane). The V apex sits on the body's closed end with \
                 both legs splaying outward at ±30° from the body axis \
                 in the (outward + binormal) plane. Workshop orients \
                 the assembled mold **+Z up** during pour + cure; both \
                 holes appear at the top:\n\n\
                 - **{gate_dia_mm:.1} mm Ø pour gate** on the +binormal \
                 side of the seam (Positive piece, file `_piece_1`), \
                 {gate_length_mm:.1} mm total channel length.\n\
                 - **{vent_dia_mm:.1} mm Ø vent** on the -binormal \
                 side of the seam (Negative piece, file `_piece_0`), \
                 {vent_length_mm:.1} mm total channel length.\n\n\
                 Each leg lives entirely on one piece (no seam \
                 straddling), so each piece carves the leg on its own \
                 side and leaves the other untouched."
            );
            md.push('\n');
            if !spec.include_vent {
                let _ = writeln!(
                    md,
                    "**Note**: this cast has the vent leg disabled \
                     (`include_vent = false`). For short straight molds \
                     air escapes back through the pour leg as silicone \
                     fills bottom-up. For any cast where air trapping \
                     is suspected, enable the vent."
                );
                md.push('\n');
            }
            let _ = writeln!(
                md,
                "Pour silicone slowly into the larger {gate_dia_mm:.1} mm Ø \
                 pour leg (+binormal hole, Positive piece). Trapped air \
                 escapes through the smaller {vent_dia_mm:.1} mm Ø vent \
                 leg (-binormal hole, Negative piece) as the cavity fills \
                 bottom-up. Workshop user identifies pour vs vent by \
                 binormal side AND by hole diameter."
            );
        }
    }
    md.push('\n');
}

fn write_per_layer_sections_v2(
    md: &mut String,
    spec: &CastSpec,
    pour_volumes: &[PourVolume],
    ribbon: &Ribbon,
) {
    let _ = writeln!(md, "## Per-Layer Procedure");
    md.push('\n');
    for (layer, pour) in spec.layers.iter().zip(pour_volumes) {
        let position = layer_position_label(pour.layer_index, spec.layers.len());
        let _ = writeln!(
            md,
            "### Layer {} — {} ({})",
            pour.layer_index, layer.material.display_name, position
        );
        md.push('\n');
        let mass_g = pour.pour_mass_kg * KG_TO_G;
        let half_g = mass_g / 2.0;
        let protocol = layer.material.anchor_key.and_then(lookup_cure);

        let _ = writeln!(
            md,
            "1. Print STLs `mold_layer_{0}_piece_0.stl` + \
             `mold_layer_{0}_piece_1.stl` + \
             `plug_layer_{0}.stl` (this layer's plug, sized to the \
             previous layer's outer surface or to the innermost \
             cavity for layer 0).",
            pour.layer_index,
        );
        let _ = writeln!(md, "2. Apply mold release to all printed surfaces.");
        let _ = writeln!(
            md,
            "3. Assemble the two pieces along the curve-following seam \
             per the \"v2 Mold Assembly\" section above."
        );
        if let Some(protocol) = protocol {
            let _ = writeln!(
                md,
                "4. Mix {half_g:.2} g Part A + {half_g:.2} g Part B {} ({} mix ratio). \
                 Total {mass_g:.2} g.",
                layer.material.display_name, protocol.mix_ratio_a_to_b,
            );
        } else {
            let _ = writeln!(
                md,
                "4. Mix Part A + Part B {} per the Smooth-On TDS \
                 (total pour mass: {mass_g:.2} g, split per the data-sheet mix ratio).",
                layer.material.display_name,
            );
        }
        let _ = writeln!(md, "5. Vacuum-degas the mix for 2-3 minutes at ≥27 inHg.");
        let pour_into = match &ribbon.pour_gate {
            PourGateKind::Default(_) => {
                "the pour leg of the V at the dome end (Positive piece, +binormal side)"
            }
            PourGateKind::None => "the assembled mold cavity",
        };
        let _ = writeln!(
            md,
            "6. Apply mold release to `plug_layer_{0}.stl` (Smooth-On \
             Ease Release 200 standard) and seat the plug into the \
             assembled mold via the plug-anchor pin socket. Orient \
             the mold with **+Z up** so the V's pour + vent legs are \
             on top. Pour silicone into {pour_into} at a slow steady \
             rate to avoid splashing through the vent; trapped air \
             rises into the vent leg (Negative piece, -binormal side) \
             as the cavity fills.",
            pour.layer_index,
        );
        if let Some(protocol) = protocol {
            let _ = writeln!(
                md,
                "7. Cure for ≥{} hr at 73 °F (pot life: {} min).",
                protocol.cure_time_hours, protocol.pot_life_minutes,
            );
        } else {
            let _ = writeln!(
                md,
                "7. Cure per the Smooth-On TDS at 73 °F (pot life per TDS)."
            );
        }
        let _ = writeln!(
            md,
            "8. Demold: open the two mold halves along the ribbon \
             seam (remove `piece_0` first, then `piece_1` for clean \
             centerline-axis slide release on curved centerlines). \
             Pull the plug axially out of the cured silicone shell; \
             the plug-anchor pin slides out of its socket-cavity in \
             the silicone cap. The cured layer detaches as a \
             standalone silicone tube ready to nest with the other \
             layers post-cure."
        );
        md.push('\n');
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::{TDS_LOOKUP_PLACEHOLDER, cure_protocol_cells, layer_position_label};

    #[test]
    fn cure_protocol_cells_resolves_known_anchor() {
        let (mix, pot_life, cure_time) = cure_protocol_cells(Some("ECOFLEX_00_30"));
        assert_eq!(mix, "1A:1B");
        assert_eq!(pot_life, "45 min");
        assert_eq!(cure_time, "4 hr");
    }

    #[test]
    fn cure_protocol_cells_emits_placeholder_for_none_anchor() {
        let (mix, pot_life, cure_time) = cure_protocol_cells(None);
        assert_eq!(mix, TDS_LOOKUP_PLACEHOLDER);
        assert_eq!(pot_life, TDS_LOOKUP_PLACEHOLDER);
        assert_eq!(cure_time, TDS_LOOKUP_PLACEHOLDER);
    }

    #[test]
    fn cure_protocol_cells_emits_placeholder_for_unknown_anchor() {
        let (mix, pot_life, cure_time) = cure_protocol_cells(Some("MOLD_STAR_30"));
        assert_eq!(mix, TDS_LOOKUP_PLACEHOLDER);
        assert_eq!(pot_life, TDS_LOOKUP_PLACEHOLDER);
        assert_eq!(cure_time, TDS_LOOKUP_PLACEHOLDER);
    }

    #[test]
    fn layer_position_label_three_layer_device() {
        // 3 layers: 0 = innermost, 1 = middle, 2 = outermost.
        assert_eq!(layer_position_label(0, 3), "innermost");
        assert_eq!(layer_position_label(1, 3), "middle");
        assert_eq!(layer_position_label(2, 3), "outermost");
    }

    #[test]
    fn layer_position_label_single_layer_is_outermost_and_innermost() {
        // Edge case: a single-layer device's only layer is both
        // innermost (`index == 0`) AND outermost (`index + 1 ==
        // count`). The check ordering picks innermost — fine,
        // because both are accurate; "innermost" is more
        // load-bearing for the procedure (it's the one that uses
        // the printed plug).
        assert_eq!(layer_position_label(0, 1), "innermost");
    }

    #[test]
    fn layer_position_label_two_layer_device() {
        // 2 layers: no middle position.
        assert_eq!(layer_position_label(0, 2), "innermost");
        assert_eq!(layer_position_label(1, 2), "outermost");
    }
}
