//! G2-PR2 dynamics cross-check: our velocity-aware Millard muscle force vs REAL
//! OpenSim 4.6 under NON-zero fiber velocity (force-velocity + fiber damping). The
//! non-isometric companion to `millard_force_cross_check` (which holds the joint
//! still). Runs in CI with NO OpenSim install (grades the vendored JSON reference).
//!
//! Two tiers (both must hold):
//!   (A) FORCE — our `millard_path_force(.., mtu, mtu_vel, act)` reproduces OpenSim's
//!       per-muscle path force across a knee-angle × knee-speed × activation grid
//!       (`muscle_force_velocity_opensim.json`). This exercises the FV curve + the
//!       β·v̄ fiber-damping term, which the isometric (FV=1, damping 0) check could not.
//!   (B) FIBER VELOCITY — our normalized fiber velocity (cos(penn)·v_mt / (L0·vmax))
//!       matches OpenSim's recorded value (unclamped points), so the FV input is
//!       independently validated, not just the resulting force.
//!
//! Reference regenerated by `gen_muscle_force_velocity.py`.

use serde_json::Value;
use sim_core::forward::{MillardCurves, MillardMuscleParams, millard_path_force};

fn asset(name: &str) -> String {
    format!(
        "{}/../../sim/L0/tests/assets/opensim_gait2392/{name}",
        env!("CARGO_MANIFEST_DIR")
    )
}

fn json(name: &str) -> Value {
    serde_json::from_str(&std::fs::read_to_string(asset(name)).unwrap()).unwrap()
}

const MUSCLES: [&str; 4] = ["rect_fem_r", "vas_int_r", "bifemlh_r", "semimem_r"];

#[test]
fn millard_force_velocity_matches_real_opensim() {
    let d = json("muscle_force_velocity_opensim.json");
    let c = MillardCurves::default();

    // Our model IS OpenSim's Millard (rigid tendon, constant-height pennation, the
    // same FV curve to ~1e-12, β=0.1 damping), evaluated at OpenSim's reported MTU
    // length + lengthening speed — so agreement is machine-exact. Generous headroom
    // over cross-platform last-ulp variance. Absolute floor avoids the ~0 N points.
    const REL_TOL: f64 = 1e-6;
    const ABS_FLOOR_N: f64 = 1.0;
    const MIN_NORM_FIB: f64 = 0.4441; // below this OpenSim clamps; skip the geometry check there.

    println!(
        "\n===== Millard force-velocity vs REAL {} (rigid-tendon, non-isometric) =====",
        d["source"].as_str().unwrap()
    );
    let mut overall_worst_rel = 0.0_f64;
    let mut overall_worst_abs = 0.0_f64;
    let mut worst_vnorm = 0.0_f64;
    let mut overall_n = 0usize;

    for m in MUSCLES {
        let p = &d["params"][m];
        let params = MillardMuscleParams {
            f0: p["max_isometric_force_N"].as_f64().unwrap(),
            l0: p["optimal_fiber_length_m"].as_f64().unwrap(),
            lts: p["tendon_slack_length_m"].as_f64().unwrap(),
            penn0: p["pennation_at_optimal_rad"].as_f64().unwrap(),
            vmax: p["max_contraction_velocity_lopt_per_s"].as_f64().unwrap(),
        };

        let mut worst_rel = 0.0_f64;
        for act_key in ["1.00", "0.50"] {
            let act: f64 = act_key.parse().unwrap();
            for row in d["muscles"][m].as_array().unwrap() {
                let mtu = row["mtu_length_m"].as_f64().unwrap();
                let mtu_vel = row["mtu_velocity_m_per_s"].as_f64().unwrap();
                let b = &row["by_activation"][act_key];
                let os = b["force_along_path_N"].as_f64().unwrap();

                let ours = millard_path_force(&c, params, mtu, mtu_vel, act);
                let gap = ours - os;
                worst_rel = worst_rel.max(gap.abs() / os.abs().max(ABS_FLOOR_N));
                overall_worst_abs = overall_worst_abs.max(gap.abs());

                // (B) independent fiber-velocity check (unclamped points only).
                if b["normalized_fiber_length"].as_f64().unwrap() > MIN_NORM_FIB + 1e-4 {
                    let along = mtu - params.lts;
                    let fiber = (along * along + (params.l0 * params.penn0.sin()).powi(2)).sqrt();
                    let our_vnorm = (along / fiber * mtu_vel) / (params.l0 * params.vmax);
                    let os_vnorm = b["normalized_fiber_velocity"].as_f64().unwrap();
                    worst_vnorm = worst_vnorm.max((our_vnorm - os_vnorm).abs());
                }
                overall_n += 1;
            }
        }
        println!("  {m:<11} worst rel {worst_rel:.2e}");
        overall_worst_rel = overall_worst_rel.max(worst_rel);
    }
    println!(
        "  OVERALL worst rel {:.4}%   worst |gap| {overall_worst_abs:.2e} N   worst v̄ {worst_vnorm:.2e}   (n={overall_n})\n",
        overall_worst_rel * 100.0
    );
    assert!(
        overall_worst_rel < REL_TOL,
        "Millard force-velocity worst relative gap {:.3}% exceeds {:.1}%",
        overall_worst_rel * 100.0,
        REL_TOL * 100.0
    );
    assert!(
        worst_vnorm < 1e-6,
        "normalized fiber velocity vs OpenSim worst {worst_vnorm:.2e} exceeds 1e-6"
    );
}
