//! G2 dynamics cross-check: our ported Millard2012 muscle model vs REAL OpenSim
//! 4.6, the force-level analogue of the kinematic `opensim_cross_check`. Runs in
//! CI with NO OpenSim install (grades against vendored JSON references).
//!
//! Two tiers (both must hold):
//!   (A) CURVE unit check — our `MillardCurves` (active-FL, passive-FL,
//!       force-velocity) reproduce OpenSim's densely-sampled default curves
//!       (`millard_curves_opensim.json`) to ~1e-5.
//!   (B) FORCE integration check — our `millard_isometric_path_force` (rigid
//!       tendon, variable-width pennation) reproduces OpenSim's per-muscle
//!       isometric path force across the knee ROM at activations 1.0 / 0.5
//!       (`muscle_forces_opensim.json`) to sub-percent. This is the gap the G2
//!       spike measured at 15–60% for the native Hill model — Millard closes it.
//!
//! References regenerated by `gen_millard_curves.py` / `gen_muscle_forces.py`.

use serde_json::Value;
use sim_core::forward::{MillardCurves, MillardMuscleParams, millard_isometric_path_force};

fn asset(name: &str) -> String {
    format!(
        "{}/../../sim/L0/tests/assets/opensim_gait2392/{name}",
        env!("CARGO_MANIFEST_DIR")
    )
}

fn json(name: &str) -> Value {
    serde_json::from_str(&std::fs::read_to_string(asset(name)).unwrap()).unwrap()
}

const MUSCLES: [&str; 4] = ["rect_fem_r", "vas_int_r", "bifemlh_r", "semimem_r"];

/// (A) Each curve matches OpenSim's sampled values to ~1e-5.
#[test]
fn millard_curves_match_real_opensim() {
    let d = json("millard_curves_opensim.json");
    let c = MillardCurves::default();
    const CURVE_TOL: f64 = 1e-5;

    let check = |key: &str, eval: &dyn Fn(f64) -> f64| -> f64 {
        let mut worst = 0.0_f64;
        for pt in d[key].as_array().unwrap() {
            let x = pt["x"].as_f64().unwrap();
            let want = pt["y"].as_f64().unwrap();
            worst = worst.max((eval(x) - want).abs());
        }
        worst
    };

    let wa = check("active_force_length", &|x| c.active_fl(x));
    let wp = check("passive_force_length", &|x| c.passive_fl(x));
    let wv = check("force_velocity", &|x| c.force_velocity(x));
    println!(
        "\nMillard curves vs REAL {}: worst |Δ| active={wa:.2e} passive={wp:.2e} fv={wv:.2e}",
        d["source"].as_str().unwrap()
    );
    assert!(
        wa < CURVE_TOL,
        "active-FL worst {wa:.2e} exceeds {CURVE_TOL:.0e}"
    );
    assert!(
        wp < CURVE_TOL,
        "passive-FL worst {wp:.2e} exceeds {CURVE_TOL:.0e}"
    );
    assert!(
        wv < CURVE_TOL,
        "force-velocity worst {wv:.2e} exceeds {CURVE_TOL:.0e}"
    );
}

/// (B) Isometric muscle force matches OpenSim's Millard (rigid tendon) to
/// sub-percent — the dynamics analogue of the sub-mm kinematic cross-check.
#[test]
fn millard_isometric_force_matches_real_opensim() {
    let d = json("muscle_forces_opensim.json");
    let c = MillardCurves::default();

    // Our model IS OpenSim's Millard (same curves to ~1e-12, same rigid-tendon +
    // constant-height pennation), evaluated at OpenSim's reported MTU length — so
    // agreement is machine-exact, not merely sub-percent. The gate keeps generous
    // headroom over cross-platform sin/sqrt last-ulp variance while still asserting
    // faithful reproduction (the native Hill model missed this by 15–60%; G2 spike).
    // Absolute floor avoids dividing the ~0 N deep-flexion points (the ~22
    // min-fiber-clamp points where both sides are 0 N — OpenSim clamps normalized
    // fiber length at ~0.4441; our curves extrapolate flat to 0 there, same force.
    // An explicit clamp is a PR3 engine-integration item, immaterial to force here).
    const REL_TOL: f64 = 1e-6;
    const ABS_FLOOR_N: f64 = 1.0;
    // OpenSim's min normalized fiber length (clamp floor); above it, geometry is
    // unclamped and our pennation/fiber formula must match OpenSim's exactly.
    const MIN_NORM_FIB: f64 = 0.4441;
    let mut worst_geom = 0.0_f64;

    println!(
        "\n===== Millard force vs REAL {} (rigid-tendon, isometric) =====",
        d["source"].as_str().unwrap()
    );
    let mut overall_worst_rel = 0.0_f64;
    let mut overall_worst_abs = 0.0_f64;
    let mut overall_sq = 0.0;
    let mut overall_n = 0usize;

    for m in MUSCLES {
        let p = &d["params"][m];
        let params = MillardMuscleParams {
            f0: p["max_isometric_force_N"].as_f64().unwrap(),
            l0: p["optimal_fiber_length_m"].as_f64().unwrap(),
            lts: p["tendon_slack_length_m"].as_f64().unwrap(),
            penn0: p["pennation_at_optimal_rad"].as_f64().unwrap(),
            vmax: p["max_contraction_velocity_lopt_per_s"].as_f64().unwrap(),
        };

        let mut worst_rel = 0.0_f64;
        let mut sq = 0.0;
        let mut n = 0usize;
        for act_key in ["1.00", "0.50"] {
            let act: f64 = act_key.parse().unwrap();
            for row in d["muscles"][m].as_array().unwrap() {
                let mtu = row["mtu_length_m"].as_f64().unwrap();
                let b = &row["by_activation"][act_key];
                let os = b["force_along_path_N"].as_f64().unwrap();

                // Independent geometry check (unclamped points only): our pennation
                // /fiber formula vs OpenSim's recorded MuscleFixedWidthPennationModel
                // output, so a geometry bug can't hide behind a force that cancels.
                let os_normfib = b["normalized_fiber_length"].as_f64().unwrap();
                if os_normfib > MIN_NORM_FIB + 1e-4 {
                    let along = mtu - params.lts;
                    let fiber = (along * along + (params.l0 * params.penn0.sin()).powi(2)).sqrt();
                    let os_cospenn = b["pennation_angle_rad"].as_f64().unwrap().cos();
                    worst_geom = worst_geom.max((fiber / params.l0 - os_normfib).abs());
                    worst_geom = worst_geom.max((along / fiber - os_cospenn).abs());
                }

                let ours = millard_isometric_path_force(&c, params, mtu, act);
                let gap = ours - os;
                let rel = gap.abs() / os.abs().max(ABS_FLOOR_N);
                worst_rel = worst_rel.max(rel);
                overall_worst_abs = overall_worst_abs.max(gap.abs());
                sq += gap * gap;
                n += 1;
            }
        }
        let rmse = (sq / n as f64).sqrt();
        println!("  {m:<11} worst rel {:.2e}   RMSE {rmse:.2e} N", worst_rel);
        overall_worst_rel = overall_worst_rel.max(worst_rel);
        overall_sq += sq;
        overall_n += n;
    }
    let overall_rmse = (overall_sq / overall_n as f64).sqrt();
    println!(
        "  OVERALL worst rel {:.4}%   worst |gap| {overall_worst_abs:.2e} N   RMSE {overall_rmse:.2e} N   worst geom {worst_geom:.2e}   (n={overall_n})\n",
        overall_worst_rel * 100.0
    );
    assert!(
        overall_worst_rel < REL_TOL,
        "Millard isometric force worst relative gap {:.3}% exceeds {:.1}%",
        overall_worst_rel * 100.0,
        REL_TOL * 100.0
    );
    assert!(
        worst_geom < 1e-6,
        "fiber geometry / pennation vs OpenSim worst {worst_geom:.2e} exceeds 1e-6"
    );
}
