//! The independent anchor: cf-osim's oracle vs REAL OpenSim 4.6.
//!
//! Every other cf-osim test compares the engine against our *re-derivation* of
//! OpenSim's GeometryPath geometry — a self-consistency loop. This test closes
//! that loop by grading our oracle (`Variant::TRUTH`, natural-cubic SimmSplines)
//! against moment arms computed by real OpenSim 4.6 on the same gait2392 model.
//!
//! The reference `knee_moment_arms_opensim.json` is vendored next to the model
//! (generated by `tools/.../osim_moment_arms.py` via the `opensim` PyPI wheel),
//! so this runs in CI with no OpenSim install. If it passes, our oracle IS a
//! faithful reproduction of OpenSim's knee muscle geometry — which is what every
//! "vs oracle" figure elsewhere ultimately leans on.

use cf_osim::oracle::{Kinematics, Variant};
use cf_osim::parse_leg_chain;
use std::f64::consts::PI;

fn asset(name: &str) -> String {
    format!(
        "{}/../../sim/L0/tests/assets/opensim_gait2392/{name}",
        env!("CARGO_MANIFEST_DIR")
    )
}

#[test]
fn oracle_matches_real_opensim() {
    let model = parse_leg_chain(&std::fs::read_to_string(asset("gait2392.osim")).unwrap());
    let kin = Kinematics::new(&model);
    let eps = 0.5 * PI / 180.0;

    let reference: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(asset("knee_moment_arms_opensim.json")).unwrap(),
    )
    .unwrap();
    println!(
        "\n===== cf-osim oracle vs REAL {} =====",
        reference["source"].as_str().unwrap()
    );
    println!(
        "{:<11} {:>8} {:>8} {:>8}",
        "muscle", "RMSE", "max|Δ|", "@deg"
    );

    let mut worst = 0.0_f64;
    for m in &model.muscles {
        let rows = reference["muscles"][&m.name].as_array().unwrap();
        let (mut sse, mut maxd, mut maxa, mut n) = (0.0, 0.0, 0.0, 0.0);
        for row in rows {
            let theta = row["angle_rad"].as_f64().unwrap();
            let osim_mm = row["moment_arm_m"].as_f64().unwrap() * 1000.0;
            let ours_mm = kin.moment_arm(m, theta, eps, Variant::TRUTH) * 1000.0;
            let d = (osim_mm - ours_mm).abs();
            sse += d * d;
            n += 1.0;
            if d > maxd {
                maxd = d;
                maxa = -theta * 180.0 / PI;
            }
        }
        let rmse = (sse / n).sqrt();
        worst = worst.max(rmse);
        println!(
            "{:<11} {:>6.3}mm {:>6.3}mm {:>6.0}",
            m.name, rmse, maxd, maxa
        );

        // Our oracle must reproduce real OpenSim moment arms. Residuals come only
        // from SimmSpline-evaluator details + our central-difference vs OpenSim's
        // analytic derivative — both small.
        assert!(
            rmse < 2.0,
            "{}: oracle vs real OpenSim RMSE {rmse:.3}mm exceeds 2mm — \
             our re-derivation diverges from OpenSim",
            m.name
        );
    }
    println!("worst-muscle RMSE: {worst:.3}mm\n");
}
