//! Design validation warnings.
//!
//! [`DesignWarning`] variants identify manufacturing constraint violations
//! and geometric issues in a mechanism. Generated by
//! [`super::Mechanism::validate()`] after checking wall thickness, hole
//! diameter, feature resolution, and joint anchor placement.

use std::collections::{HashMap, HashSet};

use nalgebra::Point3;

use super::joint::JointDef;
use super::part::Part;
use super::print::PrintProfile;
use super::tendon::TendonDef;

/// A design issue detected during mechanism validation.
///
/// Manufacturing checks ([`WallTooThin`](Self::WallTooThin),
/// [`HoleTooSmall`](Self::HoleTooSmall), [`FeatureBelowResolution`](Self::FeatureBelowResolution))
/// require a [`PrintProfile`](super::PrintProfile) and are skipped without one.
/// Geometric checks ([`JointAnchorOutOfBounds`](Self::JointAnchorOutOfBounds))
/// always run.
///
/// [`InsufficientClearance`](Self::InsufficientClearance) is defined but not
/// currently populated — it requires world-frame part positions which cf-design
/// does not yet assign. The [`to_stl_kit`](super::Mechanism::to_stl_kit)
/// clearance offset handles the manufacturing side.
#[derive(Debug, Clone, PartialEq)]
pub enum DesignWarning {
    /// A wall section is thinner than the process can produce.
    WallTooThin {
        /// Affected part name.
        part: String,
        /// Location of the thin section.
        location: Point3<f64>,
        /// Measured wall thickness (mm).
        thickness: f64,
        /// Minimum required by print profile (mm).
        min: f64,
    },
    /// A hole is smaller than the process can produce.
    HoleTooSmall {
        /// Affected part name.
        part: String,
        /// Location of the small hole.
        location: Point3<f64>,
        /// Measured hole diameter (mm).
        diameter: f64,
        /// Minimum required by print profile (mm).
        min: f64,
    },
    /// Two parts are closer together than the required clearance.
    ///
    /// TODO(clearance): populate when Parts gain world-frame positions.
    /// Currently all parts are at the origin — pairwise distance is meaningless.
    InsufficientClearance {
        /// First part name.
        part_a: String,
        /// Second part name.
        part_b: String,
        /// Measured gap between parts (mm).
        gap: f64,
        /// Minimum required by print profile (mm).
        min: f64,
    },
    /// A geometric feature is smaller than the meshing resolution can capture.
    FeatureBelowResolution {
        /// Affected part name.
        part: String,
        /// Estimated feature size (mm).
        feature_size: f64,
        /// Meshing resolution needed to capture this feature (mm).
        resolution: f64,
    },
    /// A joint anchor is outside its parent part's geometry.
    JointAnchorOutOfBounds {
        /// Joint name.
        joint: String,
        /// Parent part name.
        part: String,
        /// Anchor position (world frame, mm).
        anchor: Point3<f64>,
        /// Distance outside the part surface (mm, positive = outside).
        distance: f64,
    },
}

// ── Validation entry point ──────────────────────────────────────────────

/// Run all validation checks on a mechanism.
///
/// Manufacturing checks require a [`PrintProfile`] and are skipped without one.
/// Geometric checks (joint anchors) always run.
pub(super) fn validate_mechanism(
    parts: &[Part],
    joints: &[JointDef],
    tendons: &[TendonDef],
    profile: Option<&PrintProfile>,
) -> Vec<DesignWarning> {
    let mut warnings = Vec::new();

    check_joint_anchors(parts, joints, &mut warnings);

    if let Some(profile) = profile {
        check_wall_thickness(parts, profile, &mut warnings);
        check_hole_diameter(parts, tendons, profile, &mut warnings);
        // TODO(clearance): add check_clearance(parts, profile, &mut warnings)
        // when Parts gain world-frame positions.
    }

    warnings
}

// ── Joint anchor bounds ─────────────────────────────────────────────────

/// Check that each joint anchor is inside its parent part's geometry.
///
/// Evaluates the parent part's implicit field at the anchor point. A positive
/// value means the anchor is outside the parent's surface.
fn check_joint_anchors(parts: &[Part], joints: &[JointDef], warnings: &mut Vec<DesignWarning>) {
    let part_by_name: HashMap<&str, &Part> = parts.iter().map(|p| (p.name(), p)).collect();

    for joint in joints {
        if let Some(parent) = part_by_name.get(joint.parent()) {
            let value = parent.solid().evaluate(joint.anchor());
            if value > 0.0 {
                warnings.push(DesignWarning::JointAnchorOutOfBounds {
                    joint: joint.name().to_owned(),
                    part: joint.parent().to_owned(),
                    anchor: *joint.anchor(),
                    distance: value,
                });
            }
        }
    }
}

// ── Wall thickness + feature resolution ─────────────────────────────────

/// Check wall thickness by grid-sampling each part's interior.
///
/// At each interior grid point, the field value gives the distance to the
/// nearest surface. The wall thickness at a point is only meaningful at
/// the **medial axis** — where the inscribed sphere is locally maximal.
/// At convex surface regions (capsule tips, cuboid edges), the field value
/// is small but the actual wall thickness is large.
///
/// Algorithm: evaluate the field on a grid, then check only at **local
/// maxima** of `|field|` (medial axis points). At these points,
/// `2 × |field|` equals the local wall thickness. This correctly ignores
/// convex surface regions.
///
/// Reports the thinnest violation per part. Also emits
/// [`DesignWarning::FeatureBelowResolution`] if any medial-axis point's
/// local thickness is below `min_wall / 2`.
fn check_wall_thickness(parts: &[Part], profile: &PrintProfile, warnings: &mut Vec<DesignWarning>) {
    let cell_size = profile.min_wall;

    for part in parts {
        let Some(bounds) = part.solid().bounds() else {
            continue;
        };

        let expanded = bounds.expanded(cell_size * 0.5);
        let size = expanded.size();

        #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
        let nx = (size.x / cell_size).ceil().max(1.0) as usize;
        #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
        let ny = (size.y / cell_size).ceil().max(1.0) as usize;
        #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
        let nz = (size.z / cell_size).ceil().max(1.0) as usize;

        // Phase 1: evaluate field on full grid.
        let half_step = cell_size * 0.5;
        let mut grid = vec![0.0_f64; nx * ny * nz];

        for iz in 0..nz {
            #[allow(clippy::cast_precision_loss)]
            let pz = expanded.min.z + (iz as f64).mul_add(cell_size, half_step);

            for iy in 0..ny {
                #[allow(clippy::cast_precision_loss)]
                let py = expanded.min.y + (iy as f64).mul_add(cell_size, half_step);

                for ix in 0..nx {
                    #[allow(clippy::cast_precision_loss)]
                    let px = expanded.min.x + (ix as f64).mul_add(cell_size, half_step);

                    grid[iz * ny * nx + iy * nx + ix] =
                        part.solid().evaluate(&Point3::new(px, py, pz));
                }
            }
        }

        // Phase 2: find medial-axis points (local maxima of |field|) and
        // check wall thickness there.
        let mut thinnest_wall: Option<(Point3<f64>, f64)> = None;
        let mut smallest_feature: Option<f64> = None;

        for iz in 0..nz {
            for iy in 0..ny {
                for ix in 0..nx {
                    let idx = iz * ny * nx + iy * nx + ix;
                    let value = grid[idx];

                    // Skip exterior and near-surface points.
                    if value >= 0.0 {
                        continue;
                    }

                    let abs_val = value.abs();

                    // Check if this is a local maximum of |field| among
                    // the 6 axis-aligned neighbors. At medial axis points,
                    // |field| is maximal; at convex surface regions, |field|
                    // increases toward the interior.
                    let is_local_max = is_local_max_abs(&grid, abs_val, [ix, iy, iz], [nx, ny, nz]);

                    if !is_local_max {
                        continue;
                    }

                    let wall_estimate = 2.0 * abs_val;

                    if wall_estimate < profile.min_wall {
                        let is_thinner = thinnest_wall.is_none_or(|(_, prev)| wall_estimate < prev);
                        if is_thinner {
                            #[allow(clippy::cast_precision_loss)]
                            let point = Point3::new(
                                expanded.min.x + (ix as f64).mul_add(cell_size, half_step),
                                expanded.min.y + (iy as f64).mul_add(cell_size, half_step),
                                expanded.min.z + (iz as f64).mul_add(cell_size, half_step),
                            );
                            thinnest_wall = Some((point, wall_estimate));
                        }
                    }

                    let is_smaller = smallest_feature.is_none_or(|prev| wall_estimate < prev);
                    if is_smaller {
                        smallest_feature = Some(wall_estimate);
                    }
                }
            }
        }

        if let Some((location, thickness)) = thinnest_wall {
            warnings.push(DesignWarning::WallTooThin {
                part: part.name().to_owned(),
                location,
                thickness,
                min: profile.min_wall,
            });
        }

        let resolution = profile.min_wall / 2.0;
        if let Some(feature_size) = smallest_feature {
            if feature_size < resolution {
                warnings.push(DesignWarning::FeatureBelowResolution {
                    part: part.name().to_owned(),
                    feature_size,
                    resolution,
                });
            }
        }
    }
}

/// Check if `abs_val` is ≥ all 6 axis-aligned neighbors' absolute values.
///
/// Only considers interior neighbors (field < 0). Boundary cells (at grid
/// edges) are considered local maxima by default for those missing neighbors.
fn is_local_max_abs(grid: &[f64], abs_val: f64, pos: [usize; 3], dims: [usize; 3]) -> bool {
    let [ix, iy, iz] = pos;
    let [nx, ny, nz] = dims;

    let neighbors = [
        if ix > 0 {
            Some(iz * ny * nx + iy * nx + (ix - 1))
        } else {
            None
        },
        if ix + 1 < nx {
            Some(iz * ny * nx + iy * nx + (ix + 1))
        } else {
            None
        },
        if iy > 0 {
            Some(iz * ny * nx + (iy - 1) * nx + ix)
        } else {
            None
        },
        if iy + 1 < ny {
            Some(iz * ny * nx + (iy + 1) * nx + ix)
        } else {
            None
        },
        if iz > 0 {
            Some((iz - 1) * ny * nx + iy * nx + ix)
        } else {
            None
        },
        if iz + 1 < nz {
            Some((iz + 1) * ny * nx + iy * nx + ix)
        } else {
            None
        },
    ];

    for ni in neighbors.into_iter().flatten() {
        let nval = grid[ni];
        // Only compare against interior neighbors.
        if nval < 0.0 && nval.abs() > abs_val {
            return false;
        }
    }

    true
}

// ── Hole diameter ───────────────────────────────────────────────────────

/// Check tendon channel diameters against `min_hole`.
///
/// Compares `2 × channel_radius` for each tendon against the print profile's
/// minimum hole diameter. Surface-routed tendons (radius = 0) are skipped.
/// Reports one warning per tendon-part pair where a channel exists.
fn check_hole_diameter(
    parts: &[Part],
    tendons: &[TendonDef],
    profile: &PrintProfile,
    warnings: &mut Vec<DesignWarning>,
) {
    let part_names: HashSet<&str> = parts.iter().map(Part::name).collect();

    for tendon in tendons {
        let diameter = 2.0 * tendon.channel_radius();
        if diameter <= 0.0 || diameter >= profile.min_hole {
            continue;
        }

        // Collect waypoints per part to find which parts have channels.
        let mut wp_per_part: HashMap<&str, Vec<&Point3<f64>>> = HashMap::new();
        for wp in tendon.waypoints() {
            if part_names.contains(wp.part()) {
                wp_per_part
                    .entry(wp.part())
                    .or_default()
                    .push(wp.position());
            }
        }

        for (part_name, wps) in &wp_per_part {
            if wps.len() < 2 {
                continue; // not enough waypoints for a channel
            }
            // Use the midpoint of this part's waypoints as the location.
            let mid = wps[wps.len() / 2];
            warnings.push(DesignWarning::HoleTooSmall {
                part: (*part_name).to_owned(),
                location: *mid,
                diameter,
                min: profile.min_hole,
            });
        }
    }
}

// ── Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use nalgebra::{Point3, Vector3};

    use super::*;
    use crate::{JointKind, Material, Mechanism, Solid, TendonWaypoint};

    fn pla() -> Material {
        Material::new("PLA", 1250.0)
    }

    fn fdm_profile() -> PrintProfile {
        PrintProfile::new(0.3, 0.8, 1.5)
    }

    // ── Variant construction (existing tests, updated) ──────────────

    #[test]
    fn warning_wall_too_thin() {
        let w = DesignWarning::WallTooThin {
            part: "finger".into(),
            location: Point3::new(1.0, 2.0, 3.0),
            thickness: 0.3,
            min: 0.8,
        };
        assert!(matches!(w, DesignWarning::WallTooThin { thickness, min, .. } if thickness < min));
    }

    #[test]
    fn warning_hole_too_small() {
        let w = DesignWarning::HoleTooSmall {
            part: "palm".into(),
            location: Point3::origin(),
            diameter: 0.5,
            min: 1.5,
        };
        assert!(matches!(w, DesignWarning::HoleTooSmall { diameter, min, .. } if diameter < min));
    }

    #[test]
    fn warning_insufficient_clearance() {
        let w = DesignWarning::InsufficientClearance {
            part_a: "finger_1".into(),
            part_b: "finger_2".into(),
            gap: 0.1,
            min: 0.3,
        };
        assert!(matches!(w, DesignWarning::InsufficientClearance { gap, min, .. } if gap < min));
    }

    #[test]
    fn warning_feature_below_resolution() {
        let w = DesignWarning::FeatureBelowResolution {
            part: "tip".into(),
            feature_size: 0.05,
            resolution: 0.1,
        };
        assert!(
            matches!(w, DesignWarning::FeatureBelowResolution { feature_size, resolution, .. } if feature_size < resolution)
        );
    }

    #[test]
    fn warning_joint_anchor_out_of_bounds() {
        let w = DesignWarning::JointAnchorOutOfBounds {
            joint: "knuckle".into(),
            part: "palm".into(),
            anchor: Point3::new(100.0, 0.0, 0.0),
            distance: 95.0,
        };
        assert!(
            matches!(w, DesignWarning::JointAnchorOutOfBounds { distance, .. } if distance > 0.0)
        );
    }

    // ── Wall thickness checks ───────────────────────────────────────

    #[test]
    fn thin_wall_detected() {
        // A sphere shell with wall thickness 0.3 mm — well below min_wall=0.8.
        let shell = Solid::sphere(5.0).shell(0.3);
        let m = Mechanism::builder("thin")
            .part(crate::Part::new("shell_part", shell, pla()))
            .print_profile(fdm_profile())
            .build();

        let warnings = m.validate();
        let has_wall = warnings
            .iter()
            .any(|w| matches!(w, DesignWarning::WallTooThin { part, .. } if part == "shell_part"));
        assert!(
            has_wall,
            "expected WallTooThin for shell part, got: {warnings:?}"
        );
    }

    #[test]
    fn thick_wall_passes() {
        // A solid cuboid with half-extents 10×10×10 — wall thickness ~20 mm.
        let m = Mechanism::builder("thick")
            .part(crate::Part::new(
                "block",
                Solid::cuboid(Vector3::new(10.0, 10.0, 10.0)),
                pla(),
            ))
            .print_profile(PrintProfile::new(0.3, 0.5, 1.5))
            .build();

        let warnings = m.validate();
        let has_wall = warnings
            .iter()
            .any(|w| matches!(w, DesignWarning::WallTooThin { .. }));
        assert!(
            !has_wall,
            "solid block should have no thin walls: {warnings:?}"
        );
    }

    // ── Hole diameter checks ────────────────────────────────────────

    #[test]
    fn small_hole_detected() {
        // Tendon channel radius 0.5 → diameter 1.0 < min_hole 1.5.
        let m = Mechanism::builder("small_hole")
            .part(crate::Part::new(
                "palm",
                Solid::cuboid(Vector3::new(20.0, 30.0, 10.0)),
                pla(),
            ))
            .part(crate::Part::new("finger", Solid::capsule(3.0, 12.0), pla()))
            .joint(crate::JointDef::new(
                "j",
                "palm",
                "finger",
                JointKind::Revolute,
                Point3::origin(),
                Vector3::z(),
            ))
            .tendon(crate::TendonDef::new(
                "thin_tendon",
                vec![
                    TendonWaypoint::new("palm", Point3::new(5.0, -10.0, 0.0)),
                    TendonWaypoint::new("palm", Point3::new(5.0, 10.0, 0.0)),
                ],
                0.5, // diameter = 1.0 < min_hole = 1.5
            ))
            .print_profile(fdm_profile())
            .build();

        let warnings = m.validate();
        let has_hole = warnings.iter().any(|w| {
            matches!(w, DesignWarning::HoleTooSmall { part, diameter, .. }
                if part == "palm" && *diameter < 1.5)
        });
        assert!(
            has_hole,
            "expected HoleTooSmall for thin tendon, got: {warnings:?}"
        );
    }

    #[test]
    fn adequate_hole_passes() {
        // Tendon channel radius 2.0 → diameter 4.0 > min_hole 1.5.
        let m = Mechanism::builder("ok_hole")
            .part(crate::Part::new(
                "palm",
                Solid::cuboid(Vector3::new(20.0, 30.0, 10.0)),
                pla(),
            ))
            .part(crate::Part::new("finger", Solid::capsule(3.0, 12.0), pla()))
            .joint(crate::JointDef::new(
                "j",
                "palm",
                "finger",
                JointKind::Revolute,
                Point3::origin(),
                Vector3::z(),
            ))
            .tendon(crate::TendonDef::new(
                "fat_tendon",
                vec![
                    TendonWaypoint::new("palm", Point3::new(5.0, -10.0, 0.0)),
                    TendonWaypoint::new("palm", Point3::new(5.0, 10.0, 0.0)),
                ],
                2.0, // diameter = 4.0 > min_hole = 1.5
            ))
            .print_profile(fdm_profile())
            .build();

        let warnings = m.validate();
        let has_hole = warnings
            .iter()
            .any(|w| matches!(w, DesignWarning::HoleTooSmall { .. }));
        assert!(!has_hole, "adequate hole should pass: {warnings:?}");
    }

    // ── Joint anchor bounds ─────────────────────────────────────────

    #[test]
    fn joint_anchor_outside_parent() {
        // Anchor at (100, 0, 0) is way outside sphere(5).
        let m = Mechanism::builder("bad_anchor")
            .part(crate::Part::new("ball", Solid::sphere(5.0), pla()))
            .part(crate::Part::new("arm", Solid::capsule(2.0, 10.0), pla()))
            .joint(crate::JointDef::new(
                "bad_joint",
                "ball",
                "arm",
                JointKind::Revolute,
                Point3::new(100.0, 0.0, 0.0),
                Vector3::z(),
            ))
            .build();

        let warnings = m.validate();
        let has_anchor = warnings.iter().any(|w| {
            matches!(w, DesignWarning::JointAnchorOutOfBounds { joint, .. } if joint == "bad_joint")
        });
        assert!(
            has_anchor,
            "expected JointAnchorOutOfBounds, got: {warnings:?}"
        );
    }

    #[test]
    fn joint_anchor_inside_parent() {
        // Anchor at (3, 0, 0) is inside sphere(5).
        let m = Mechanism::builder("ok_anchor")
            .part(crate::Part::new("ball", Solid::sphere(5.0), pla()))
            .part(crate::Part::new("arm", Solid::capsule(2.0, 10.0), pla()))
            .joint(crate::JointDef::new(
                "good_joint",
                "ball",
                "arm",
                JointKind::Revolute,
                Point3::new(3.0, 0.0, 0.0),
                Vector3::z(),
            ))
            .build();

        let warnings = m.validate();
        let has_anchor = warnings
            .iter()
            .any(|w| matches!(w, DesignWarning::JointAnchorOutOfBounds { .. }));
        assert!(
            !has_anchor,
            "anchor inside parent should not warn: {warnings:?}"
        );
    }

    // ── No print profile ────────────────────────────────────────────

    #[test]
    fn no_profile_only_checks_anchors() {
        // No print profile → manufacturing checks skipped.
        // Bad anchor should still be caught.
        let m = Mechanism::builder("no_profile")
            .part(crate::Part::new("ball", Solid::sphere(5.0), pla()))
            .part(crate::Part::new("arm", Solid::capsule(2.0, 10.0), pla()))
            .joint(crate::JointDef::new(
                "bad",
                "ball",
                "arm",
                JointKind::Revolute,
                Point3::new(100.0, 0.0, 0.0),
                Vector3::z(),
            ))
            .build();

        let warnings = m.validate();

        // Should have anchor warning.
        assert!(
            warnings
                .iter()
                .any(|w| matches!(w, DesignWarning::JointAnchorOutOfBounds { .. }))
        );
        // Should NOT have any manufacturing warnings.
        assert!(
            !warnings
                .iter()
                .any(|w| matches!(w, DesignWarning::WallTooThin { .. }))
        );
        assert!(
            !warnings
                .iter()
                .any(|w| matches!(w, DesignWarning::HoleTooSmall { .. }))
        );
    }

    // ── Bio-gripper clean validation ────────────────────────────────

    #[test]
    fn bio_gripper_validates_clean() {
        // Well-designed gripper with generous profile should produce no warnings.
        let palm = Solid::cuboid(Vector3::new(18.0, 22.0, 4.0));
        let finger = Solid::capsule(3.0, 12.0);
        let mat = pla();

        let m = Mechanism::builder("bio_gripper")
            .part(crate::Part::new("palm", palm, mat.clone()))
            .part(crate::Part::new("finger_1", finger.clone(), mat.clone()))
            .part(crate::Part::new("finger_2", finger, mat))
            .joint(
                crate::JointDef::new(
                    "knuckle_1",
                    "palm",
                    "finger_1",
                    JointKind::Revolute,
                    Point3::new(10.0, 20.0, 0.0),
                    Vector3::x(),
                )
                .with_range(-0.1, 1.8),
            )
            .joint(
                crate::JointDef::new(
                    "knuckle_2",
                    "palm",
                    "finger_2",
                    JointKind::Revolute,
                    Point3::new(-10.0, 20.0, 0.0),
                    Vector3::x(),
                )
                .with_range(-0.1, 1.8),
            )
            .tendon(
                crate::TendonDef::new(
                    "flexor_1",
                    vec![
                        TendonWaypoint::new("palm", Point3::new(8.0, -10.0, 0.0)),
                        TendonWaypoint::new("palm", Point3::new(8.0, 18.0, 0.0)),
                        TendonWaypoint::new("finger_1", Point3::new(0.0, 5.0, 0.0)),
                        TendonWaypoint::new("finger_1", Point3::new(0.0, 20.0, 0.0)),
                    ],
                    1.5,
                )
                .with_stiffness(100.0)
                .with_damping(5.0),
            )
            .actuator(
                crate::ActuatorDef::new(
                    "motor_1",
                    "flexor_1",
                    crate::ActuatorKind::Motor,
                    (-50.0, 50.0),
                )
                .with_ctrl_range(-1.0, 1.0),
            )
            // FDM-realistic profile. min_wall=0.5 is below the actual
            // thinnest wall (channel-to-surface ≈ 2.5mm). min_hole=1.0 is
            // below the channel diameter (3.0mm).
            .print_profile(PrintProfile::new(0.3, 0.5, 1.0))
            .build();

        let warnings = m.validate();

        // The gripper should have no WallTooThin (min_wall=0.05 is below
        // any real wall), no HoleTooSmall (channel diameter 3.0 > min_hole
        // 1.0), and no JointAnchorOutOfBounds (anchors at ±10,20,0 are
        // inside the palm cuboid ±18,22,4).
        let critical: Vec<_> = warnings
            .iter()
            .filter(|w| !matches!(w, DesignWarning::FeatureBelowResolution { .. }))
            .collect();
        assert!(
            critical.is_empty(),
            "well-designed gripper should validate clean, got: {critical:?}"
        );
    }
}
