//! Design validation warnings.
//!
//! [`DesignWarning`] variants identify manufacturing constraint violations
//! in a mechanism. Generated by `Mechanism::validate()` (Session 12) after
//! checking wall thickness, hole diameter, inter-part clearances, and
//! feature resolution.

use nalgebra::Point3;

/// A manufacturing constraint violation detected during mechanism validation.
///
/// Each variant identifies a specific issue, the affected part(s), and both
/// the measured value and the minimum required by the [`super::PrintProfile`].
#[derive(Debug, Clone, PartialEq)]
pub enum DesignWarning {
    /// A wall section is thinner than the process can produce.
    WallTooThin {
        /// Affected part name.
        part: String,
        /// Location of the thin section.
        location: Point3<f64>,
        /// Measured wall thickness (mm).
        thickness: f64,
        /// Minimum required by print profile (mm).
        min: f64,
    },
    /// A hole is smaller than the process can produce.
    HoleTooSmall {
        /// Affected part name.
        part: String,
        /// Location of the small hole.
        location: Point3<f64>,
        /// Measured hole diameter (mm).
        diameter: f64,
        /// Minimum required by print profile (mm).
        min: f64,
    },
    /// Two parts are closer together than the required clearance.
    InsufficientClearance {
        /// First part name.
        part_a: String,
        /// Second part name.
        part_b: String,
        /// Measured gap between parts (mm).
        gap: f64,
        /// Minimum required by print profile (mm).
        min: f64,
    },
    /// A geometric feature is smaller than the meshing resolution can capture.
    FeatureBelowResolution {
        /// Affected part name.
        part: String,
        /// Estimated feature size (mm).
        feature_size: f64,
        /// Meshing resolution (mm).
        resolution: f64,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn warning_wall_too_thin() {
        let w = DesignWarning::WallTooThin {
            part: "finger".into(),
            location: Point3::new(1.0, 2.0, 3.0),
            thickness: 0.3,
            min: 0.8,
        };
        assert!(matches!(w, DesignWarning::WallTooThin { thickness, min, .. } if thickness < min));
    }

    #[test]
    fn warning_hole_too_small() {
        let w = DesignWarning::HoleTooSmall {
            part: "palm".into(),
            location: Point3::origin(),
            diameter: 0.5,
            min: 1.5,
        };
        assert!(matches!(w, DesignWarning::HoleTooSmall { diameter, min, .. } if diameter < min));
    }

    #[test]
    fn warning_insufficient_clearance() {
        let w = DesignWarning::InsufficientClearance {
            part_a: "finger_1".into(),
            part_b: "finger_2".into(),
            gap: 0.1,
            min: 0.3,
        };
        assert!(matches!(w, DesignWarning::InsufficientClearance { gap, min, .. } if gap < min));
    }

    #[test]
    fn warning_feature_below_resolution() {
        let w = DesignWarning::FeatureBelowResolution {
            part: "tip".into(),
            feature_size: 0.05,
            resolution: 0.1,
        };
        assert!(
            matches!(w, DesignWarning::FeatureBelowResolution { feature_size, resolution, .. } if feature_size < resolution)
        );
    }
}
