//! The translator: a syntax-directed walk from `syn`'s tree to WGSL text.
//!
//! Every construct outside the subset is refused where it is met, with its
//! line and column. Type errors inside the subset are left to naga, which
//! validates the whole module afterwards.

use std::collections::{BTreeMap, BTreeSet};

use proc_macro2::Span;
use syn::spanned::Spanned;
use syn::{
    Attribute, BinOp, Block, Expr, ExprIf, Fields, FnArg, Item, ItemConst, ItemFn, ItemStruct, Lit,
    Local, Member, Pat, ReturnType, Stmt, Type, UnOp,
};

use crate::{Error, Source};

/// The methods the subset accepts, as `(Rust name, WGSL builtin, argument
/// count besides the receiver)`. `x.min(y)` becomes `min(x, y)`.
///
/// Left out on purpose: `round` and `signum`, whose Rust and WGSL results
/// differ (Rust rounds half away from zero, WGSL to even; `signum(0.0)` is 1
/// in Rust and `sign(0.0)` is 0 in WGSL), and `mul_add`, which WGSL's `fma`
/// does not promise to fuse.
pub const METHODS: &[(&str, &str, usize)] = &[
    ("abs", "abs", 0),
    ("sqrt", "sqrt", 0),
    ("ln", "log", 0),
    ("exp", "exp", 0),
    ("sin", "sin", 0),
    ("cos", "cos", 0),
    ("acos", "acos", 0),
    ("floor", "floor", 0),
    ("min", "min", 1),
    ("max", "max", 1),
    ("clamp", "clamp", 2),
];

/// Names the emitted WGSL relies on meaning the builtin. A source item or
/// binding with one of these names would silently capture the call.
const BUILTINS_USED: &[&str] = &["select", "array", "f32", "u32", "i32", "bool"];

/// The line length past which a statement's array or struct literal is
/// broken into one element per line.
const MAX_LINE: usize = 100;

/// The WGSL module for `sources`, not yet validated.
pub fn module(sources: &[Source<'_>]) -> Result<String, Error> {
    let files = sources
        .iter()
        .map(|source| syn::parse_file(source.text).map_err(|e| refusal(source.path, e.span(), &e)))
        .collect::<Result<Vec<_>, _>>()?;

    let mut structs = BTreeMap::new();
    for (source, file) in sources.iter().zip(&files) {
        for item in &file.items {
            if let Item::Struct(s) = item {
                let name = s.ident.to_string();
                let fields = s
                    .fields
                    .iter()
                    .filter_map(|f| f.ident.as_ref().map(ToString::to_string))
                    .collect();
                if structs.insert(name.clone(), fields).is_some() {
                    return Err(refusal(
                        source.path,
                        s.ident.span(),
                        &format!("struct `{name}` is declared twice"),
                    ));
                }
            }
        }
    }

    let mut out = String::from(
        "// GENERATED by sim-wgsl-gen from the Rust sources listed below. Do not edit\n\
         // this file: edit the sources and regenerate it (the freshness test that\n\
         // fails names the command). The Rust scalar type `R` is written as `f32`.\n\
         //\n\
         // Sources:\n",
    );
    for source in sources {
        push_line(&mut out, &format!("//   {}", source.path));
    }
    for (source, file) in sources.iter().zip(&files) {
        let translator = Translator {
            path: source.path,
            structs: &structs,
        };
        push_line(&mut out, &format!("\n// ---- {} ----", source.path));
        for item in &file.items {
            out.push('\n');
            translator.item(item, &mut out)?;
        }
    }
    Ok(out)
}

fn refusal(path: &str, span: Span, message: &dyn std::fmt::Display) -> Error {
    let start = span.start();
    Error::Refused {
        path: path.to_string(),
        line: start.line,
        column: start.column + 1,
        message: message.to_string(),
    }
}

struct Translator<'a> {
    path: &'a str,
    /// Every struct in the sources, with its field names in declared order.
    structs: &'a BTreeMap<String, Vec<String>>,
}

/// The names bound in one function, which WGSL forbids redeclaring.
#[derive(Default)]
struct Scope {
    names: BTreeSet<String>,
    temporaries: usize,
}

/// Where an attribute sits, which decides the attributes allowed on it.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Site {
    Function,
    Struct,
    Field,
    Constant,
    Statement,
}

impl Translator<'_> {
    fn refuse(&self, span: Span, message: impl std::fmt::Display) -> Error {
        refusal(self.path, span, &message)
    }

    // ---- items ----

    fn item(&self, item: &Item, out: &mut String) -> Result<(), Error> {
        match item {
            Item::Fn(f) => self.function(f, out),
            Item::Struct(s) => self.structure(s, out),
            Item::Const(c) => self.constant(c, out),
            other => Err(self.refuse(
                other.span(),
                "only `fn`, `struct` and `const` items are in the subset",
            )),
        }
    }

    /// Checks `attrs` for `site` and returns the doc-comment lines.
    fn attributes(&self, attrs: &[Attribute], site: Site) -> Result<Vec<String>, Error> {
        let mut docs = Vec::new();
        let mut repr_c = false;
        for attr in attrs {
            let name = attr
                .path()
                .get_ident()
                .map(ToString::to_string)
                .unwrap_or_default();
            match name.as_str() {
                "doc" if site != Site::Statement => {
                    if let syn::Meta::NameValue(nv) = &attr.meta
                        && let Expr::Lit(lit) = &nv.value
                        && let Lit::Str(text) = &lit.lit
                    {
                        let text = text.value();
                        docs.push(text.strip_prefix(' ').unwrap_or(&text).to_string());
                    }
                }
                "allow" | "expect" => {}
                "must_use" | "inline" if site == Site::Function => {}
                "derive" if site == Site::Struct => {}
                "repr" if site == Site::Struct => {
                    let is_c = attr
                        .parse_args::<syn::Ident>()
                        .is_ok_and(|ident| ident == "C");
                    if !is_c {
                        return Err(self.refuse(attr.span(), "only `#[repr(C)]` is in the subset"));
                    }
                    repr_c = true;
                }
                _ => {
                    return Err(self.refuse(
                        attr.span(),
                        "this attribute is not in the subset: it could make the Rust and the \
                         WGSL differ",
                    ));
                }
            }
        }
        if site == Site::Struct && !repr_c {
            return Err(self.refuse(
                attrs.first().map_or_else(Span::call_site, Spanned::span),
                "a shared struct needs `#[repr(C)]`, so its layout is the one the GPU reads",
            ));
        }
        Ok(docs)
    }

    fn declare_item_name(&self, ident: &syn::Ident) -> Result<String, Error> {
        let name = ident.to_string();
        if BUILTINS_USED.contains(&name.as_str()) || METHODS.iter().any(|m| m.1 == name) {
            return Err(self.refuse(
                ident.span(),
                format!("`{name}` is a WGSL builtin the translation calls; rename it"),
            ));
        }
        Ok(name)
    }

    fn function(&self, f: &ItemFn, out: &mut String) -> Result<(), Error> {
        let docs = self.attributes(&f.attrs, Site::Function)?;
        let sig = &f.sig;
        if sig.asyncness.is_some() || sig.unsafety.is_some() || sig.abi.is_some() {
            return Err(self.refuse(
                sig.span(),
                "`async`, `unsafe` and `extern` functions are not in the subset",
            ));
        }
        if !sig.generics.params.is_empty() || sig.generics.where_clause.is_some() {
            return Err(self.refuse(
                sig.generics.span(),
                "generics are not in the subset: write against `R`",
            ));
        }
        let name = self.declare_item_name(&sig.ident)?;
        let mut scope = Scope::default();
        let mut params = Vec::new();
        for input in &sig.inputs {
            match input {
                FnArg::Receiver(r) => {
                    return Err(self.refuse(r.span(), "`self` is not in the subset: pass values"));
                }
                FnArg::Typed(typed) => {
                    let param = self.binding(&typed.pat, &mut scope)?;
                    params.push(format!("{param}: {}", self.ty(&typed.ty)?));
                }
            }
        }
        let ReturnType::Type(_, returns) = &sig.output else {
            return Err(self.refuse(
                sig.span(),
                "a shared function must return a value: it has no side effects",
            ));
        };
        let returns = self.ty(returns)?;

        comments(out, &docs, "");
        push_line(
            out,
            &format!("fn {name}({}) -> {returns} {{", params.join(", ")),
        );
        self.body(&f.block, &mut scope, out)?;
        out.push_str("}\n");
        Ok(())
    }

    fn structure(&self, s: &ItemStruct, out: &mut String) -> Result<(), Error> {
        let docs = self.attributes(&s.attrs, Site::Struct)?;
        if !s.generics.params.is_empty() {
            return Err(self.refuse(s.generics.span(), "generic structs are not in the subset"));
        }
        let name = self.declare_item_name(&s.ident)?;
        let Fields::Named(fields) = &s.fields else {
            return Err(self.refuse(s.span(), "a shared struct needs named fields"));
        };
        comments(out, &docs, "");
        push_line(out, &format!("struct {name} {{"));
        for field in &fields.named {
            let field_docs = self.attributes(&field.attrs, Site::Field)?;
            comments(out, &field_docs, "    ");
            let ident = field
                .ident
                .as_ref()
                .ok_or_else(|| self.refuse(field.span(), "a shared struct needs named fields"))?;
            push_line(out, &format!("    {ident}: {},", self.ty(&field.ty)?));
        }
        out.push_str("}\n");
        Ok(())
    }

    fn constant(&self, c: &ItemConst, out: &mut String) -> Result<(), Error> {
        let docs = self.attributes(&c.attrs, Site::Constant)?;
        let name = self.declare_item_name(&c.ident)?;
        comments(out, &docs, "");
        push_line(
            out,
            &format!(
                "const {name}: {} = {};",
                self.ty(&c.ty)?,
                self.expr(&c.expr)?
            ),
        );
        Ok(())
    }

    // ---- statements ----

    fn body(&self, block: &Block, scope: &mut Scope, out: &mut String) -> Result<(), Error> {
        let Some((last, lets)) = block.stmts.split_last() else {
            return Err(self.refuse(block.span(), "an empty body has no value"));
        };
        for stmt in lets {
            match stmt {
                Stmt::Local(local) => self.local(local, scope, out)?,
                Stmt::Expr(e, _) => {
                    return Err(self.refuse(
                        e.span(),
                        "only `let` bindings may come before the final expression",
                    ));
                }
                other => {
                    return Err(self.refuse(
                        other.span(),
                        "nested items and macros are not in the subset",
                    ));
                }
            }
        }
        match last {
            Stmt::Expr(e, None) => {
                let value = self.statement_value(e, "    return ".len())?;
                push_line(out, &format!("    return {value};"));
                Ok(())
            }
            other => Err(self.refuse(
                other.span(),
                "the body must end in an expression without `;`: the function's value",
            )),
        }
    }

    fn local(&self, local: &Local, scope: &mut Scope, out: &mut String) -> Result<(), Error> {
        self.attributes(&local.attrs, Site::Statement)?;
        let Some(init) = &local.init else {
            return Err(self.refuse(
                local.span(),
                "a `let` needs a value: nothing is assigned later",
            ));
        };
        if let Some((_, diverge)) = &init.diverge {
            return Err(self.refuse(diverge.span(), "`let … else` is not in the subset"));
        }
        let value = self.statement_value(&init.expr, "    let ".len() + 16)?;
        match &local.pat {
            Pat::Ident(_) => {
                let name = self.binding(&local.pat, scope)?;
                push_line(out, &format!("    let {name} = {value};"));
            }
            Pat::Type(typed) => {
                let name = self.binding(&typed.pat, scope)?;
                push_line(
                    out,
                    &format!("    let {name}: {} = {value};", self.ty(&typed.ty)?),
                );
            }
            Pat::Slice(slice) => {
                // A name or a field is indexed in place; anything else is bound
                // once, so it is not evaluated once per element.
                let base = if matches!(init.expr.as_ref(), Expr::Path(_) | Expr::Field(_)) {
                    value
                } else {
                    scope.temporaries += 1;
                    let temporary = format!("destructured_{}", scope.temporaries);
                    self.declare(&temporary, local.span(), scope)?;
                    push_line(out, &format!("    let {temporary} = {value};"));
                    temporary
                };
                for (index, element) in slice.elems.iter().enumerate() {
                    if let Pat::Wild(_) = element {
                        continue;
                    }
                    let name = self.binding(element, scope)?;
                    push_line(out, &format!("    let {name} = {base}[{index}];"));
                }
            }
            other => {
                return Err(self.refuse(
                    other.span(),
                    "only `let name`, `let name: T` and `let [a, b, …]` bindings are in the subset",
                ));
            }
        }
        Ok(())
    }

    /// A plain name pattern, declared in `scope`.
    fn binding(&self, pat: &Pat, scope: &mut Scope) -> Result<String, Error> {
        let Pat::Ident(ident) = pat else {
            return Err(self.refuse(pat.span(), "only a plain name can be bound here"));
        };
        if let Some(mutability) = &ident.mutability {
            return Err(self.refuse(
                mutability.span(),
                "`mut` is not in the subset: nothing is mutated",
            ));
        }
        if ident.by_ref.is_some() || ident.subpat.is_some() {
            return Err(self.refuse(ident.span(), "only a plain name can be bound here"));
        }
        let name = ident.ident.to_string();
        self.declare(&name, ident.span(), scope)?;
        Ok(name)
    }

    fn declare(&self, name: &str, span: Span, scope: &mut Scope) -> Result<(), Error> {
        if BUILTINS_USED.contains(&name) || METHODS.iter().any(|m| m.1 == name) {
            return Err(self.refuse(
                span,
                format!("`{name}` is a WGSL builtin the translation calls; rename it"),
            ));
        }
        if !scope.names.insert(name.to_string()) {
            return Err(self.refuse(
                span,
                format!("`{name}` is already bound in this function, and WGSL cannot redeclare it"),
            ));
        }
        Ok(())
    }

    // ---- expressions ----

    fn expr(&self, e: &Expr) -> Result<String, Error> {
        match e {
            Expr::Lit(lit) => self.literal(&lit.lit),
            Expr::Path(path) => self.name(path),
            Expr::Paren(inner) => Ok(format!("({})", self.expr(&inner.expr)?)),
            Expr::Binary(binary) => {
                let op = binary_operator(&binary.op).ok_or_else(|| {
                    self.refuse(
                        binary.op.span(),
                        "compound assignment is mutation, which is not in the subset",
                    )
                })?;
                Ok(format!(
                    "{} {op} {}",
                    self.operand(&binary.left)?,
                    self.operand(&binary.right)?
                ))
            }
            Expr::Unary(unary) => self.unary(unary),
            Expr::Call(call) => self.call(call),
            Expr::MethodCall(call) => self.method(call),
            Expr::Field(field) => match &field.member {
                Member::Named(member) => Ok(format!("{}.{member}", self.operand(&field.base)?)),
                Member::Unnamed(_) => {
                    Err(self.refuse(field.span(), "tuple fields are not in the subset"))
                }
            },
            Expr::Index(index) => self.index(index),
            Expr::Array(array) => {
                if array.elems.is_empty() {
                    return Err(self.refuse(array.span(), "an empty array has no WGSL type"));
                }
                Ok(format!("array({})", self.arguments(array.elems.iter())?))
            }
            Expr::Struct(literal) => self.struct_literal(literal),
            Expr::If(conditional) => self.conditional(conditional),
            Expr::Cast(cast) => {
                let target = self.ty(&cast.ty)?;
                if !matches!(target.as_str(), "f32" | "u32" | "i32") {
                    return Err(
                        self.refuse(cast.ty.span(), "a cast must be to `R`, `u32` or `i32`")
                    );
                }
                Ok(format!("{target}({})", self.delimited(&cast.expr)?))
            }
            _ => Err(self.refused(e)),
        }
    }

    fn unary(&self, unary: &syn::ExprUnary) -> Result<String, Error> {
        let op = match unary.op {
            UnOp::Neg(_) => "-",
            UnOp::Not(_) => "!",
            _ => return Err(self.refuse(unary.span(), "dereferencing is not in the subset")),
        };
        let operand = match unary.expr.as_ref() {
            Expr::Unary(_) => format!("({})", self.expr(&unary.expr)?),
            other => self.operand(other)?,
        };
        Ok(format!("{op}{operand}"))
    }

    fn call(&self, call: &syn::ExprCall) -> Result<String, Error> {
        let Expr::Path(path) = call.func.as_ref() else {
            return Err(self.refuse(
                call.func.span(),
                "only a function named directly can be called",
            ));
        };
        Ok(format!(
            "{}({})",
            self.name(path)?,
            self.arguments(call.args.iter())?
        ))
    }

    fn index(&self, index: &syn::ExprIndex) -> Result<String, Error> {
        let Expr::Lit(syn::ExprLit {
            lit: Lit::Int(position),
            ..
        }) = index.index.as_ref()
        else {
            return Err(self.refuse(
                index.index.span(),
                "an index must be an integer literal: a runtime index is storage access, \
                 which belongs to the executor",
            ));
        };
        Ok(format!(
            "{}[{}]",
            self.operand(&index.expr)?,
            position.base10_digits()
        ))
    }

    /// The refusal for an expression outside the subset.
    fn refused(&self, e: &Expr) -> Error {
        let message = match e {
            Expr::ForLoop(_) | Expr::While(_) | Expr::Loop(_) => {
                "loops are not in the subset: shared math is written loop-free (plan §13d rule 1)"
            }
            Expr::Assign(_) => "assignment is mutation, which is not in the subset",
            Expr::Match(_) => "`match` is not in the subset: use `if`/`else`",
            Expr::Return(_) => "`return` is not in the subset: end the body in its value",
            Expr::Closure(_) => "closures are not in the subset",
            Expr::Macro(_) => "macros are not in the subset",
            Expr::Reference(_) => "references are not in the subset: pass values",
            _ => "this expression is not in the subset",
        };
        self.refuse(e.span(), message)
    }

    /// `e`, parenthesized when it is itself an operation, so the WGSL groups
    /// exactly as the Rust did (WGSL also refuses some unparenthesized mixes,
    /// such as `a && b || c`).
    fn operand(&self, e: &Expr) -> Result<String, Error> {
        let text = self.expr(e)?;
        Ok(if matches!(e, Expr::Binary(_)) {
            format!("({text})")
        } else {
            text
        })
    }

    fn arguments<'e>(&self, args: impl Iterator<Item = &'e Expr>) -> Result<String, Error> {
        Ok(args
            .map(|a| self.delimited(a))
            .collect::<Result<Vec<_>, _>>()?
            .join(", "))
    }

    fn literal(&self, lit: &Lit) -> Result<String, Error> {
        match lit {
            Lit::Float(float) => {
                let digits = float.base10_digits();
                Ok(if digits.contains(['.', 'e', 'E']) {
                    digits.to_string()
                } else {
                    format!("{digits}.0")
                })
            }
            Lit::Int(int) => match int.suffix() {
                "" => Ok(int.base10_digits().to_string()),
                "u32" => Ok(format!("{}u", int.base10_digits())),
                "i32" => Ok(format!("{}i", int.base10_digits())),
                _ => Err(self.refuse(
                    int.span(),
                    "an integer literal must be untyped, `u32` or `i32`",
                )),
            },
            Lit::Bool(b) => Ok(b.value.to_string()),
            other => Err(self.refuse(
                other.span(),
                "only numbers and booleans are literals in the subset",
            )),
        }
    }

    /// A value named by a single identifier.
    fn name(&self, path: &syn::ExprPath) -> Result<String, Error> {
        let single = path.qself.is_none()
            && path.path.leading_colon.is_none()
            && path.path.segments.len() == 1
            && path.path.segments[0].arguments.is_empty();
        if !single {
            return Err(self.refuse(
                path.span(),
                "only a plain name is in the subset: shared math has one namespace, as WGSL does",
            ));
        }
        let name = path.path.segments[0].ident.to_string();
        match name.as_str() {
            "self" => Err(self.refuse(path.span(), "`self` is not in the subset: pass values")),
            "R" => Err(self.refuse(path.span(), "`R` is a type, not a value")),
            _ => Ok(name),
        }
    }

    fn method(&self, call: &syn::ExprMethodCall) -> Result<String, Error> {
        if call.turbofish.is_some() {
            return Err(self.refuse(call.span(), "turbofish is not in the subset"));
        }
        let method = call.method.to_string();
        let Some((_, builtin, arity)) = METHODS.iter().find(|m| m.0 == method) else {
            let known: Vec<&str> = METHODS.iter().map(|m| m.0).collect();
            return Err(self.refuse(
                call.method.span(),
                format!(
                    "`.{method}()` is not in the subset's method table ({})",
                    known.join(", ")
                ),
            ));
        };
        if call.args.len() != *arity {
            return Err(self.refuse(
                call.span(),
                format!("`.{method}()` takes {arity} argument(s) besides its receiver"),
            ));
        }
        let receiver = self.delimited(&call.receiver)?;
        if call.args.is_empty() {
            Ok(format!("{builtin}({receiver})"))
        } else {
            Ok(format!(
                "{builtin}({receiver}, {})",
                self.arguments(call.args.iter())?
            ))
        }
    }

    fn struct_literal(&self, literal: &syn::ExprStruct) -> Result<String, Error> {
        let (name, arguments) = self.struct_arguments(literal)?;
        Ok(format!("{name}({})", arguments.join(", ")))
    }

    /// A struct literal's name and its field values in declared order.
    fn struct_arguments(&self, literal: &syn::ExprStruct) -> Result<(String, Vec<String>), Error> {
        if let Some(rest) = &literal.rest {
            return Err(self.refuse(
                rest.span(),
                "`..base` is not in the subset: name every field",
            ));
        }
        let name = literal
            .path
            .get_ident()
            .map(ToString::to_string)
            .unwrap_or_default();
        let Some(order) = self.structs.get(&name) else {
            return Err(self.refuse(
                literal.path.span(),
                "only a struct declared in the sources can be built",
            ));
        };
        let mut values = BTreeMap::new();
        for field in &literal.fields {
            let Member::Named(member) = &field.member else {
                return Err(self.refuse(field.span(), "tuple fields are not in the subset"));
            };
            values.insert(member.to_string(), self.delimited(&field.expr)?);
        }
        let mut arguments = Vec::new();
        for field in order {
            let value = values.remove(field).ok_or_else(|| {
                self.refuse(
                    literal.span(),
                    format!("field `{field}` of `{name}` is missing"),
                )
            })?;
            arguments.push(value);
        }
        Ok((name, arguments))
    }

    /// `e` where its position already delimits it (an argument, a `let`
    /// value, a returned value), so redundant outer parentheses are dropped.
    fn delimited(&self, mut e: &Expr) -> Result<String, Error> {
        while let Expr::Paren(inner) = e {
            e = &inner.expr;
        }
        self.expr(e)
    }

    /// A statement's value. An array or struct literal too long for one line
    /// (after `lead` characters) gets one element per line.
    fn statement_value(&self, e: &Expr, lead: usize) -> Result<String, Error> {
        let one_line = self.delimited(e)?;
        if lead + one_line.len() <= MAX_LINE {
            return Ok(one_line);
        }
        let (head, items) = match e {
            Expr::Array(array) => (
                "array".to_string(),
                array
                    .elems
                    .iter()
                    .map(|element| self.delimited(element))
                    .collect::<Result<Vec<_>, _>>()?,
            ),
            Expr::Struct(literal) => self.struct_arguments(literal)?,
            _ => return Ok(one_line),
        };
        let mut text = format!("{head}(\n");
        for item in items {
            text.push_str("        ");
            text.push_str(&item);
            text.push_str(",\n");
        }
        text.push_str("    )");
        Ok(text)
    }

    fn conditional(&self, conditional: &ExprIf) -> Result<String, Error> {
        let condition = self.delimited(&conditional.cond)?;
        let then = self.branch(&conditional.then_branch)?;
        let Some((_, otherwise)) = &conditional.else_branch else {
            return Err(self.refuse(
                conditional.span(),
                "an `if` needs an `else`: in the subset it is an expression",
            ));
        };
        let otherwise = match otherwise.as_ref() {
            Expr::Block(block) if block.attrs.is_empty() && block.label.is_none() => {
                self.branch(&block.block)?
            }
            Expr::If(nested) => self.conditional(nested)?,
            other => return Err(self.refuse(other.span(), "this `else` is not in the subset")),
        };
        Ok(format!("select({otherwise}, {then}, {condition})"))
    }

    /// An `if` arm: a block holding one expression.
    fn branch(&self, block: &Block) -> Result<String, Error> {
        match block.stmts.as_slice() {
            [Stmt::Expr(e, None)] => self.delimited(e),
            _ => Err(self.refuse(
                block.span(),
                "an `if` arm must be a single expression: both arms become WGSL `select` operands",
            )),
        }
    }

    // ---- types ----

    fn ty(&self, ty: &Type) -> Result<String, Error> {
        match ty {
            Type::Path(path)
                if path.qself.is_none()
                    && path.path.segments.len() == 1
                    && path.path.segments[0].arguments.is_empty() =>
            {
                let name = path.path.segments[0].ident.to_string();
                match name.as_str() {
                    "R" => Ok("f32".to_string()),
                    "u32" | "i32" | "bool" => Ok(name),
                    "f32" | "f64" => Err(self.refuse(
                        ty.span(),
                        format!("`{name}` is not in the subset: write `R`, or the f32 and f64 builds differ"),
                    )),
                    _ if self.structs.contains_key(&name) => Ok(name),
                    _ => Err(self.refuse(ty.span(), format!("type `{name}` is not in the subset"))),
                }
            }
            Type::Array(array) => {
                let Expr::Lit(syn::ExprLit {
                    lit: Lit::Int(len), ..
                }) = &array.len
                else {
                    return Err(self.refuse(
                        array.len.span(),
                        "an array length must be an integer literal",
                    ));
                };
                Ok(format!(
                    "array<{}, {}>",
                    self.ty(&array.elem)?,
                    len.base10_digits()
                ))
            }
            Type::Paren(inner) => self.ty(&inner.elem),
            other => Err(self.refuse(other.span(), "this type is not in the subset")),
        }
    }
}

const fn binary_operator(op: &BinOp) -> Option<&'static str> {
    Some(match op {
        BinOp::Add(_) => "+",
        BinOp::Sub(_) => "-",
        BinOp::Mul(_) => "*",
        BinOp::Div(_) => "/",
        BinOp::Rem(_) => "%",
        BinOp::And(_) => "&&",
        BinOp::Or(_) => "||",
        BinOp::BitXor(_) => "^",
        BinOp::BitAnd(_) => "&",
        BinOp::BitOr(_) => "|",
        BinOp::Shl(_) => "<<",
        BinOp::Shr(_) => ">>",
        BinOp::Eq(_) => "==",
        BinOp::Lt(_) => "<",
        BinOp::Le(_) => "<=",
        BinOp::Ne(_) => "!=",
        BinOp::Ge(_) => ">=",
        BinOp::Gt(_) => ">",
        _ => return None,
    })
}

fn comments(out: &mut String, lines: &[String], indent: &str) {
    for line in lines {
        if line.is_empty() {
            push_line(out, &format!("{indent}//"));
        } else {
            push_line(out, &format!("{indent}// {line}"));
        }
    }
}

fn push_line(out: &mut String, line: &str) {
    out.push_str(line);
    out.push('\n');
}
