//! DT-97 Golden-File Flag Conformance Tests.
//!
//! Compares CortenForge simulation output against MuJoCo 3.4.0-generated .npy
//! golden files for all 25 disable/enable flags. Each test loads the enriched
//! canonical MJCF model, sets a single flag, sets ctrl[0]=2.0 (outside
//! ctrlrange [-1,1] for DISABLE_CLAMPCTRL observability), steps 10 times, and
//! compares `qacc` element-wise against the golden data at 1e-8 tolerance.
//!
//! Golden files are generated by `sim/L0/tests/scripts/gen_flag_golden.py`.
//! See `sim/L0/tests/assets/golden/flags/README.md` for regeneration instructions.

use sim_core::{
    DISABLE_ACTUATION, DISABLE_AUTORESET, DISABLE_CLAMPCTRL, DISABLE_CONSTRAINT, DISABLE_CONTACT,
    DISABLE_DAMPER, DISABLE_EQUALITY, DISABLE_EULERDAMP, DISABLE_FILTERPARENT,
    DISABLE_FRICTIONLOSS, DISABLE_GRAVITY, DISABLE_ISLAND, DISABLE_LIMIT, DISABLE_MIDPHASE,
    DISABLE_NATIVECCD, DISABLE_REFSAFE, DISABLE_SENSOR, DISABLE_SPRING, DISABLE_WARMSTART,
    ENABLE_ENERGY, ENABLE_FWDINV, ENABLE_INVDISCRETE, ENABLE_MULTICCD, ENABLE_OVERRIDE,
    ENABLE_SLEEP,
};
use sim_mjcf::load_model;

const TOLERANCE: f64 = 1e-8;
const NSTEPS: usize = 10;
const CTRL_VALUE: f64 = 2.0;

// ============================================================================
// .npy parser (intentionally duplicated — separate test binary from
// mujoco_conformance/common.rs; cannot share code across [[test]] targets)
// ============================================================================

/// Parse a NumPy .npy v1.0 file into shape + f64 data.
///
/// Supports only v1.0 format, little-endian float64 (`<f8`), C-contiguous.
/// Returns `None` if the file doesn't exist or can't be parsed.
fn parse_npy(path: &std::path::Path) -> Option<(Vec<usize>, Vec<f64>)> {
    let bytes = std::fs::read(path).ok()?;

    // Magic: \x93NUMPY
    if bytes.len() < 10 || &bytes[0..6] != b"\x93NUMPY" {
        panic!("invalid .npy magic");
    }
    let major = bytes[6];
    let minor = bytes[7];
    assert!(major == 1 && minor == 0, "only .npy v1.0 supported");

    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header_end = 10 + header_len;
    let header = std::str::from_utf8(&bytes[10..header_end]).expect("header not utf-8");

    // Parse dtype — must be '<f8' (little-endian float64)
    assert!(
        header.contains("'<f8'") || header.contains("'float64'"),
        "only float64 dtype supported, got: {header}"
    );

    // Parse Fortran order — must be False
    assert!(
        header.contains("'fortran_order': False"),
        "only C-contiguous arrays supported"
    );

    // Parse shape: 'shape': (10, 1) or 'shape': (10,)
    let shape_start = header.find("'shape': (").expect("no shape in header") + 10;
    let shape_end = header[shape_start..].find(')').expect("no shape end") + shape_start;
    let shape_str = &header[shape_start..shape_end];
    let shape: Vec<usize> = shape_str
        .split(',')
        .filter(|s| !s.trim().is_empty())
        .map(|s| s.trim().parse().expect("bad shape dim"))
        .collect();

    // Parse data
    let data_bytes = &bytes[header_end..];
    let n_elements: usize = shape.iter().product();
    assert_eq!(
        data_bytes.len(),
        n_elements * 8,
        "data size mismatch: {} bytes for {} elements",
        data_bytes.len(),
        n_elements
    );

    let data: Vec<f64> = data_bytes
        .chunks_exact(8)
        .map(|chunk| f64::from_le_bytes(chunk.try_into().unwrap()))
        .collect();

    Some((shape, data))
}

/// Path to golden file assets.
fn golden_path(filename: &str) -> std::path::PathBuf {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    std::path::Path::new(manifest_dir)
        .join("assets")
        .join("golden")
        .join("flags")
        .join(filename)
}

// ============================================================================
// Shared test infrastructure
// ============================================================================

/// Run a golden-file flag test: load model, set one flag, step, compare qacc.
fn run_flag_test(flag: u32, is_enable: bool, npy_file: &str) {
    let npy_path = golden_path(npy_file);
    let (golden_shape, golden_data) = match parse_npy(&npy_path) {
        Some(v) => v,
        None => {
            eprintln!(
                "SKIP {npy_file}: golden file not found at {}",
                npy_path.display()
            );
            eprintln!("  Regenerate with: uv run sim/L0/tests/scripts/gen_flag_golden.py");
            return;
        }
    };

    let nsteps = golden_shape[0];
    let nv_golden = golden_shape[1];
    assert_eq!(nsteps, NSTEPS, "golden file should have {NSTEPS} steps");

    let model_path = golden_path("flag_golden_test.xml");
    let xml = std::fs::read_to_string(&model_path).expect("failed to read golden model XML");
    let mut model = load_model(&xml).expect("failed to load golden model");
    assert_eq!(
        model.nv, nv_golden,
        "model nv ({}) != golden nv ({nv_golden})",
        model.nv
    );

    if is_enable {
        model.enableflags |= flag;
    } else {
        model.disableflags |= flag;
    }

    let mut data = model.make_data();
    data.ctrl[0] = CTRL_VALUE;

    for step in 0..nsteps {
        data.step(&model).expect("step failed");

        let row_start = step * nv_golden;
        for dof in 0..nv_golden {
            let expected = golden_data[row_start + dof];
            let actual = data.qacc[dof];
            let diff = (actual - expected).abs();
            assert!(
                diff < TOLERANCE,
                "qacc mismatch at step {step}, dof {dof}: \
                 actual={actual}, expected={expected}, diff={diff}, file={npy_file}"
            );
        }
    }
}

// ============================================================================
// Test generation macro
// ============================================================================

macro_rules! flag_test {
    ($name:ident, disable, $flag:expr, $file:literal) => {
        #[test]
        fn $name() {
            run_flag_test($flag, false, $file);
        }
    };
    ($name:ident, disable, $flag:expr, $file:literal, ignore = $reason:literal) => {
        #[test]
        #[ignore = $reason]
        fn $name() {
            run_flag_test($flag, false, $file);
        }
    };
    ($name:ident, enable, $flag:expr, $file:literal) => {
        #[test]
        fn $name() {
            run_flag_test($flag, true, $file);
        }
    };
    ($name:ident, enable, $flag:expr, $file:literal, ignore = $reason:literal) => {
        #[test]
        #[ignore = $reason]
        fn $name() {
            run_flag_test($flag, true, $file);
        }
    };
}

// ============================================================================
// Baseline (no flags)
// ============================================================================

#[test]
#[ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 step 0 — equality constraint solver"]
fn golden_baseline() {
    // Flag=0 with is_enable=false → disableflags |= 0 → no-op → baseline.
    run_flag_test(0, false, "baseline_qacc.npy");
}

// ============================================================================
// Disable flag tests (19 flags)
// ============================================================================

flag_test!(
    golden_disable_constraint,
    disable,
    DISABLE_CONSTRAINT,
    "disable_constraint_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~25.9 dof 0 step 1 — constraint solver divergence"
);
flag_test!(
    golden_disable_equality,
    disable,
    DISABLE_EQUALITY,
    "disable_equality_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~0.002 dof 0 — residual dynamics gap without equality"
);
flag_test!(
    golden_disable_frictionloss,
    disable,
    DISABLE_FRICTIONLOSS,
    "disable_frictionloss_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~3.99 dof 0 — frictionloss computation"
);
flag_test!(
    golden_disable_limit,
    disable,
    DISABLE_LIMIT,
    "disable_limit_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_contact,
    disable,
    DISABLE_CONTACT,
    "disable_contact_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_spring,
    disable,
    DISABLE_SPRING,
    "disable_spring_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_damper,
    disable,
    DISABLE_DAMPER,
    "disable_damper_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_gravity,
    disable,
    DISABLE_GRAVITY,
    "disable_gravity_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~0.40 dof 0 — equality constraint solver (gravity-off)"
);
flag_test!(
    golden_disable_clampctrl,
    disable,
    DISABLE_CLAMPCTRL,
    "disable_clampctrl_qacc.npy",
    ignore =
        "CONFORMANCE GAP: qacc diff ~2.48 dof 0 — equality constraint + ctrl clamp interaction"
);
flag_test!(
    golden_disable_warmstart,
    disable,
    DISABLE_WARMSTART,
    "disable_warmstart_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_filterparent,
    disable,
    DISABLE_FILTERPARENT,
    "disable_filterparent_qacc.npy",
    ignore =
        "CONFORMANCE GAP: qacc diff ~51.9 dof 0 — parent-child collision filter implementation"
);
flag_test!(
    golden_disable_actuation,
    disable,
    DISABLE_ACTUATION,
    "disable_actuation_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_refsafe,
    disable,
    DISABLE_REFSAFE,
    "disable_refsafe_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_sensor,
    disable,
    DISABLE_SENSOR,
    "disable_sensor_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_midphase,
    disable,
    DISABLE_MIDPHASE,
    "disable_midphase_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_eulerdamp,
    disable,
    DISABLE_EULERDAMP,
    "disable_eulerdamp_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_autoreset,
    disable,
    DISABLE_AUTORESET,
    "disable_autoreset_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_nativeccd,
    disable,
    DISABLE_NATIVECCD,
    "disable_nativeccd_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_disable_island,
    disable,
    DISABLE_ISLAND,
    "disable_island_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);

// ============================================================================
// Enable flag tests (6 flags)
// ============================================================================

flag_test!(
    golden_enable_override,
    enable,
    ENABLE_OVERRIDE,
    "enable_override_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_enable_energy,
    enable,
    ENABLE_ENERGY,
    "enable_energy_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_enable_fwdinv,
    enable,
    ENABLE_FWDINV,
    "enable_fwdinv_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_enable_invdiscrete,
    enable,
    ENABLE_INVDISCRETE,
    "enable_invdiscrete_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_enable_multiccd,
    enable,
    ENABLE_MULTICCD,
    "enable_multiccd_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
flag_test!(
    golden_enable_sleep,
    enable,
    ENABLE_SLEEP,
    "enable_sleep_qacc.npy",
    ignore = "CONFORMANCE GAP: qacc diff ~1.69 dof 0 — equality constraint solver"
);
