//! `cf-viewer` library — PLY loading + the [`ViewerInput`] data type.
//!
//! Wraps [`mesh_io::load_ply_attributed`] in a Bevy-friendly resource that
//! carries the loaded geometry plus a deterministically-ordered list of
//! per-vertex scalar names. Submodules:
//!
//! - [`mesh`] — `AttributedMesh → Bevy Mesh` conversion (face case) and
//!   the point-cloud sizing constant.
//! - [`colormap`] — Q5 distribution detection + per-vertex RGBA mapping
//!   (commit 4).
//! - [`camera`] — mouse-driven orbit camera (commit 5).
//! - [`ui`] — scalar + colormap dropdowns via `bevy_egui` (commit 5).
//! - [`cli`] — `clap`-derived `--scalar` / `--colormap` / `--up` flags
//!   that seed [`ui::Selection`] + [`UpAxis`] before the dropdowns see
//!   them (commit 6).

pub mod camera;
pub mod cli;
pub mod colormap;
pub mod mesh;
pub mod ui;

use std::path::Path;

use anyhow::{Context, Result};
use bevy::prelude::Resource;
use mesh_io::load_ply_attributed;
use mesh_types::AttributedMesh;

/// Loaded artifact ready for visualization.
///
/// `scalar_names` is the alphabetically-ordered list of per-vertex
/// `extras` keys (Q4 lock — see `docs/VIEWER_DESIGN.md`). Auto-selection
/// picks the first; the [`ui::scalar_and_colormap_panel`] dropdown
/// (commit 5) and the `--scalar=<name>` CLI flag (commit 6) override.
///
/// [`ui::scalar_and_colormap_panel`]: crate::ui::scalar_and_colormap_panel
#[derive(Resource)]
pub struct ViewerInput {
    /// Geometry plus per-vertex attributes loaded from the PLY.
    pub mesh: AttributedMesh,

    /// Sorted names of per-vertex scalar extras (`mesh.extras` keys).
    pub scalar_names: Vec<String>,
}

/// Which input axis maps to Bevy's +Y. Z-up is the workspace default
/// (mesh-v1.0 build-plate convention; sphere-sdf-eval is rotation-symmetric);
/// the `--up=<+X|+Y|+Z>` CLI flag (commit 6) parameterizes it for non-default
/// inputs.
///
/// The mapping is an axis swap that re-uses the reflection convention from
/// commit 3:
///
/// - [`UpAxis::PlusZ`]: input `(x, y, z)` → Bevy `(x, z, y)` — today's
///   default; Y↔Z swap inverts handedness, so triangle winding flips.
/// - [`UpAxis::PlusY`]: input `(x, y, z)` → Bevy `(x, y, z)` — identity;
///   no winding flip.
/// - [`UpAxis::PlusX`]: input `(x, y, z)` → Bevy `(y, x, z)` — X↔Y swap
///   inverts handedness, so triangle winding flips.
///
/// Stored as a Bevy `Resource`; systems read `Res<UpAxis>` and pass it to
/// the pure helpers in [`mesh`] / [`camera`].
#[derive(Resource, Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum UpAxis {
    /// Input X axis is up — `(x, y, z)` → Bevy `(y, x, z)`. Winding flips.
    PlusX,
    /// Input Y axis is up — identity. Winding does not flip.
    PlusY,
    /// Input Z axis is up — `(x, y, z)` → Bevy `(x, z, y)`. Winding flips.
    /// Workspace default.
    #[default]
    PlusZ,
}

impl UpAxis {
    /// `true` when the swap inverts handedness (parity-flipping). Triangle
    /// winding must be reversed in this case to keep CCW front-facing.
    #[must_use]
    pub fn flips_winding(self) -> bool {
        !matches!(self, Self::PlusY)
    }
}

/// Load a PLY file into a [`ViewerInput`].
///
/// Wraps [`mesh_io::load_ply_attributed`] and projects the `extras` map
/// keys into `scalar_names`. `BTreeMap` iteration is alphabetical, so
/// the order is deterministic across loads.
///
/// # Errors
///
/// Returns an error if the file cannot be read or the PLY is malformed.
pub fn load_input(path: &Path) -> Result<ViewerInput> {
    let mesh = load_ply_attributed(path)
        .with_context(|| format!("loading PLY from {}", path.display()))?;
    let scalar_names: Vec<String> = mesh.extras.keys().cloned().collect();
    Ok(ViewerInput { mesh, scalar_names })
}

#[cfg(test)]
mod tests {
    use super::*;

    use mesh_io::save_ply_attributed;
    use mesh_types::{IndexedMesh, Point3};

    /// Round-trip a synthetic point-cloud PLY (faces empty, two scalars)
    /// through `save_ply_attributed` → [`load_input`] and verify shape.
    ///
    /// Synthetic rather than fixture-based: the natural sphere-sdf-eval
    /// fixture under `examples/sim-soft/sphere-sdf-eval/out/` is gitignored
    /// and regenerated by `cargo run -p sphere-sdf-eval`. The user-facing
    /// fixture smoke check happens via the stdout vertex/scalar print in
    /// `main.rs` during the visual-review cadence step.
    #[test]
    fn round_trip_point_cloud_with_scalars() -> Result<()> {
        let geometry = IndexedMesh::from_parts(
            vec![
                Point3::new(0.0, 0.0, 0.0),
                Point3::new(1.0, 0.0, 0.0),
                Point3::new(0.0, 1.0, 0.0),
                Point3::new(0.0, 0.0, 1.0),
            ],
            Vec::new(),
        );
        let mut mesh = AttributedMesh::new(geometry);
        // Two extras inserted in reverse-alphabetical order; the loader
        // should still surface them sorted via the `BTreeMap` projection.
        mesh.insert_extra("zeta", vec![-1.0, -2.0, -3.0, -4.0])?;
        mesh.insert_extra("phi", vec![1.0, 2.0, 3.0, 4.0])?;

        let dir = tempfile::tempdir()?;
        let out_path = dir.path().join("test.ply");
        save_ply_attributed(&mesh, &out_path, true)?;

        let input = load_input(&out_path)?;
        assert_eq!(input.mesh.vertex_count(), 4);
        assert_eq!(input.mesh.face_count(), 0);
        assert_eq!(
            input.scalar_names,
            vec!["phi".to_string(), "zeta".to_string()],
        );
        Ok(())
    }

    #[test]
    fn up_axis_default_is_plus_z() {
        assert_eq!(UpAxis::default(), UpAxis::PlusZ);
    }

    #[test]
    fn up_axis_flips_winding_for_reflective_swaps_only() {
        assert!(UpAxis::PlusX.flips_winding());
        assert!(!UpAxis::PlusY.flips_winding());
        assert!(UpAxis::PlusZ.flips_winding());
    }
}
