//! ModelBuilder field initialization.
//!
//! Separated from `builder/mod.rs` to keep the orchestration module under 800
//! production lines (see MARGIN WARNING in STRUCTURAL_REFACTOR_EXECUTION.md).

use nalgebra::{UnitQuaternion, Vector3};
use sim_core::{Integrator, SolverType};
use std::collections::{HashMap, HashSet};

use super::ModelBuilder;

impl ModelBuilder {
    pub(super) fn new() -> Self {
        // Initialize with world body (body 0)
        Self {
            name: String::new(),
            resolver: crate::defaults::DefaultResolver::default(),
            compiler: crate::types::MjcfCompiler::default(),
            nq: 0,
            nv: 0,

            // World body initialized
            body_parent: vec![0],
            body_rootid: vec![0],
            body_jnt_adr: vec![0],
            body_jnt_num: vec![0],
            body_dof_adr: vec![0],
            body_dof_num: vec![0],
            body_geom_adr: vec![0],
            body_geom_num: vec![0],
            body_pos: vec![Vector3::zeros()],
            body_quat: vec![UnitQuaternion::identity()],
            body_ipos: vec![Vector3::zeros()],
            body_iquat: vec![UnitQuaternion::identity()],
            body_mass: vec![0.0],
            body_inertia: vec![Vector3::zeros()],
            body_name: vec![Some("world".to_string())],
            body_mocapid: vec![None],      // world body is not mocap
            body_sleep_policy: vec![None], // world body has no sleep policy
            body_gravcomp: vec![0.0],      // world body has no gravcomp
            nmocap: 0,

            jnt_type: vec![],
            jnt_body: vec![],
            jnt_qpos_adr: vec![],
            jnt_dof_adr: vec![],
            jnt_pos: vec![],
            jnt_axis: vec![],
            jnt_limited: vec![],
            jnt_range: vec![],
            jnt_stiffness: vec![],
            jnt_springref: vec![],
            jnt_damping: vec![],
            jnt_armature: vec![],
            jnt_solref: vec![],
            jnt_solimp: vec![],
            jnt_name: vec![],
            jnt_group: vec![],
            jnt_actgravcomp: vec![],

            dof_body: vec![],
            dof_jnt: vec![],
            dof_parent: vec![],
            dof_armature: vec![],
            dof_damping: vec![],
            dof_frictionloss: vec![],
            dof_solref: vec![],
            dof_solimp: vec![],

            geom_type: vec![],
            geom_body: vec![],
            geom_pos: vec![],
            geom_quat: vec![],
            geom_size: vec![],
            geom_friction: vec![],
            geom_condim: vec![],
            geom_contype: vec![],
            geom_conaffinity: vec![],
            geom_name: vec![],
            geom_mesh: vec![],
            geom_solref: vec![],
            geom_solimp: vec![],
            geom_priority: vec![],
            geom_solmix: vec![],
            geom_margin: vec![],
            geom_gap: vec![],
            geom_group: vec![],
            geom_rgba: vec![],
            geom_fluid: vec![],

            mesh_name_to_id: HashMap::new(),
            mesh_name: vec![],
            mesh_data: vec![],

            hfield_name_to_id: HashMap::new(),
            hfield_name: vec![],
            hfield_data: vec![],
            hfield_size: vec![],
            geom_hfield: vec![],
            geom_sdf: vec![],

            site_body: vec![],
            site_type: vec![],
            site_pos: vec![],
            site_quat: vec![],
            site_size: vec![],
            site_name: vec![],
            site_group: vec![],
            site_rgba: vec![],

            // World frame tracking (world body at origin)
            body_world_pos: vec![],
            body_world_quat: vec![],

            actuator_trntype: vec![],
            actuator_dyntype: vec![],
            actuator_trnid: vec![],
            actuator_gear: vec![],
            actuator_ctrlrange: vec![],
            actuator_forcerange: vec![],
            actuator_name: vec![],
            actuator_act_adr: vec![],
            actuator_act_num: vec![],
            actuator_gaintype: vec![],
            actuator_biastype: vec![],
            actuator_dynprm: vec![],
            actuator_gainprm: vec![],
            actuator_biasprm: vec![],
            actuator_lengthrange: vec![],
            actuator_acc0: vec![],
            actuator_actlimited: vec![],
            actuator_actrange: vec![],
            actuator_actearly: vec![],

            na: 0,

            // MuJoCo defaults
            timestep: 0.002,
            gravity: Vector3::new(0.0, 0.0, -9.81),
            wind: Vector3::zeros(),
            magnetic: Vector3::zeros(),
            density: 0.0,
            viscosity: 0.0,
            solver_iterations: 100,
            solver_tolerance: 1e-8,
            impratio: 1.0,
            regularization: 1e-6,
            friction_smoothing: 1000.0,
            cone: 0,
            ls_iterations: 50,
            ls_tolerance: 0.01,
            noslip_iterations: 0,
            noslip_tolerance: 1e-6,
            disableflags: 0,
            enableflags: 0,
            disableactuator: 0,
            actuator_group: Vec::new(),
            o_margin: 0.0,
            o_solref: [0.02, 1.0],
            o_solimp: [0.9, 0.95, 0.001, 0.5, 2.0],
            o_friction: [1.0, 1.0, 0.005, 0.0001, 0.0001],
            integrator: Integrator::Euler,
            solver_type: SolverType::PGS,
            sleep_tolerance: 1e-4,

            qpos0_values: vec![],

            joint_name_to_id: HashMap::new(),
            body_name_to_id: HashMap::from([("world".to_string(), 0)]),
            site_name_to_id: HashMap::new(),
            geom_name_to_id: HashMap::new(),

            // Tendons (populated by process_tendons)
            tendon_name_to_id: HashMap::new(),
            tendon_type: vec![],
            tendon_range: vec![],
            tendon_limited: vec![],
            tendon_stiffness: vec![],
            tendon_damping: vec![],
            tendon_frictionloss: vec![],
            tendon_solref_fri: vec![],
            tendon_solimp_fri: vec![],
            tendon_lengthspring: vec![],
            tendon_length0: vec![],
            tendon_name: vec![],
            tendon_solref: vec![],
            tendon_solimp: vec![],
            tendon_num: vec![],
            tendon_adr: vec![],
            tendon_group: vec![],
            tendon_rgba: vec![],
            wrap_type: vec![],
            wrap_objid: vec![],
            wrap_prm: vec![],
            wrap_sidesite: vec![],

            // Actuator name lookup
            actuator_name_to_id: HashMap::new(),

            // Sensor/equality name lookup (§59)
            sensor_name_to_id: HashMap::new(),
            eq_name_to_id: HashMap::new(),

            // Equality constraints (populated by process_equality_constraints)
            eq_type: vec![],
            eq_obj1id: vec![],
            eq_obj2id: vec![],
            eq_data: vec![],
            eq_active: vec![],
            eq_solimp: vec![],
            eq_solref: vec![],
            eq_name: vec![],

            // Sensors (populated by process_sensors)
            sensor_type: vec![],
            sensor_datatype: vec![],
            sensor_objtype: vec![],
            sensor_objid: vec![],
            sensor_reftype: vec![],
            sensor_refid: vec![],
            sensor_adr: vec![],
            sensor_dim: vec![],
            sensor_noise: vec![],
            sensor_cutoff: vec![],
            sensor_name_list: vec![],
            nsensor: 0,
            nsensordata: 0,

            // Contact pairs / excludes (populated by process_contact)
            contact_pairs: vec![],
            contact_pair_set: HashSet::new(),
            contact_excludes: HashSet::new(),

            nflex: 0,
            nflexvert: 0,
            nflexedge: 0,
            nflexelem: 0,
            nflexhinge: 0,
            flex_dim: vec![],
            flex_vertadr: vec![],
            flex_vertnum: vec![],
            flex_damping: vec![],
            flex_friction: vec![],
            flex_condim: vec![],
            flex_margin: vec![],
            flex_gap: vec![],
            flex_priority: vec![],
            flex_solmix: vec![],
            flex_solref: vec![],
            flex_solimp: vec![],
            flex_edge_solref: vec![],
            flex_edge_solimp: vec![],
            flex_bend_stiffness: vec![],
            flex_bend_damping: vec![],
            flex_young: vec![],
            flex_poisson: vec![],
            flex_thickness: vec![],
            flex_density: vec![],
            flex_group: vec![],
            flex_contype: vec![],
            flex_conaffinity: vec![],
            flex_selfcollide: vec![],
            flex_edgestiffness: vec![],
            flex_edgedamping: vec![],
            flexvert_qposadr: vec![],
            flexvert_dofadr: vec![],
            flexvert_mass: vec![],
            flexvert_invmass: vec![],
            flexvert_radius: vec![],
            flexvert_flexid: vec![],
            flexvert_bodyid: vec![],
            flexvert_initial_pos: vec![],
            flexedge_vert: vec![],
            flexedge_length0: vec![],
            flexedge_flexid: vec![],
            flexelem_data: vec![],
            flexelem_dataadr: vec![],
            flexelem_datanum: vec![],
            flexelem_volume0: vec![],
            flexelem_flexid: vec![],
            flexhinge_vert: vec![],
            flexhinge_angle0: vec![],
            flexhinge_flexid: vec![],
        }
    }
}
