// Generated by `uv run docs/soft_contact/thick_tube_reference.py --golden <this file>`.
// Do not edit: regenerate it, and review the change (plan §16g).

//! The thick-tube oracle's golden values: K2's corners and the confined case
//! (plan §15a, 15d.8), from `docs/soft_contact/thick_tube_reference.py`.

use super::tube::{TubeCase, Walls};

/// The cases, in the oracle's units (`A = 1`, `mu = 1`).
#[allow(clippy::unreadable_literal)]
pub const THICK_TUBE: [TubeCase; 5] = [
    TubeCase {
        mandrel_ratio: 1.1,
        thickness_ratio: 2.0,
        poisson: 0.49,
        walls: Walls::Free,
        pressure_over_mu: 0.12351821063584904,
        axial_stretch: 0.9852292451135847,
        pressure_per_mandrel_ratio: 1.1784585966789773,
        pressure_per_axial_stretch: 0.519721756901681,
    },
    TubeCase {
        mandrel_ratio: 1.1,
        thickness_ratio: 2.0,
        poisson: 0.495,
        walls: Walls::Free,
        pressure_over_mu: 0.1236528984005159,
        axial_stretch: 0.9851145759873879,
        pressure_per_mandrel_ratio: 1.1814663438067252,
        pressure_per_axial_stretch: 0.5277014094792754,
    },
    TubeCase {
        mandrel_ratio: 1.3,
        thickness_ratio: 2.0,
        poisson: 0.49,
        walls: Walls::Free,
        pressure_over_mu: 0.3050711467388505,
        axial_stretch: 0.9577944072437973,
        pressure_per_mandrel_ratio: 0.7710030907881471,
        pressure_per_axial_stretch: 0.1951236307806692,
    },
    TubeCase {
        mandrel_ratio: 1.3,
        thickness_ratio: 2.0,
        poisson: 0.495,
        walls: Walls::Free,
        pressure_over_mu: 0.3054400888402091,
        axial_stretch: 0.9574748003378925,
        pressure_per_mandrel_ratio: 0.7730370571723544,
        pressure_per_axial_stretch: 0.2009794340396276,
    },
    TubeCase {
        mandrel_ratio: 1.1,
        thickness_ratio: 2.0,
        poisson: 0.49,
        walls: Walls::Cased,
        pressure_over_mu: 4.141663914852232,
        axial_stretch: 1.0,
        pressure_per_mandrel_ratio: 47.622910313016575,
        pressure_per_axial_stretch: -56.82984014310222,
    },
];
